#!/usr/bin/env bash
#
# Copyright 2019, Intel Corporation
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in
#       the documentation and/or other materials provided with the
#       distribution.
#
#     * Neither the name of the copyright holder nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

#
# src/test/rpmem_fip/TEST5 -- test WQ size evaluation
#


. ../unittest/unittest.sh

require_test_type medium

setup

. setup.sh

function rpmem_fip_test()
{
	local wq_size=$1
	expect_normal_exit run_on_node 1 ./rpmem_fip$EXESUFFIX\
		client_wq_size ${NODE_ADDR[0]} $RPMEM_PROVIDER $RPMEM_PM\
		$wq_size
}

# WQ size is common for all lanes
export RPMEM_WORK_QUEUE_SIZE=1
export_vars_node 1 RPMEM_WORK_QUEUE_SIZE

UINT_MAX=$((2**32))
TOO_LARGE=$((UINT_MAX + 1))
WQ_SIZE_VALUES=(8 -1 0 1 $TOO_LARGE)

for wq_size in ${wq_SIZE_VALUES[@]}; do
	# limit size of WQ queue
	export RPMEM_WORK_QUEUE_SIZE=$wq_size
	export_vars_node 1 RPMEM_WORK_QUEUE_SIZE

	rpmem_fip_test $wq_size
done

# relative values
WQ_SIZE_VALUES=("LT_MAX_WQ_SIZE" "EQ_MAX_WQ_SIZE" "GT_MAX_WQ_SIZE")

for wq_size in ${WQ_SIZE_VALUES[@]}; do
	# RPMEM_WORK_QUEUE_SIZE will be set according to maximum supported WQ size
	rpmem_fip_test $wq_size
done

pass
