#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/rpmem_fip/TEST2 -- tests for rpmem_fip and rpmemd_fip modules
#

. $UNITTEST_SH

require_test_type medium

setup

. setup.sh

expect_normal_exit run_on_node 1 ./rpmem_fip$EXESUFFIX\
	client_persist ${NODE_ADDR[0]} $RPMEM_PROVIDER $RPMEM_PM

pass
