#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2019, Intel Corporation

#
# src/test/rpmem_fip/TEST7 -- rpmem_fip_flush and rpmem_fip_drain
# multi-threaded
#
# single-threaded in TEST6
#

. $UNITTEST_SH

require_test_type medium

setup

. setup.sh

expect_normal_exit run_on_node 1 ./rpmem_fip$EXESUFFIX\
	client_flush_mt ${NODE_ADDR[0]} $RPMEM_PROVIDER $RPMEM_PM

pass
