# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2022, Intel Corporation

#
# src/test/obj_heap_reopen/Makefile -- build obj_heap_reopen test
#
TARGET = obj_heap_reopen
OBJS = obj_heap_reopen.o

LIBPMEMOBJ=y

include ../Makefile.inc
INCS += -I../../libpmemobj
