# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_constructor/Makefile -- build obj_constructor test
#
TARGET = obj_constructor
OBJS = obj_constructor.o

LIBPMEMOBJ=y

include ../Makefile.inc
