# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/libpmempool_sync/Makefile -- build libpmempool sync tests
#
TARGET = libpmempool_sync
OBJS = libpmempool_sync.o

LIBPMEMPOOL=y
USE_PMEMSPOIL=y
USE_PMEMOBJCLI=y

include ../Makefile.inc
