# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2014-2019, Intel Corporation

#
# src/test/blk_recovery/Makefile -- build blk_recovery unit test
#
TARGET = blk_recovery
OBJS = blk_recovery.o

LIBPMEMBLK=y

include ../Makefile.inc
CFLAGS += -I../../libpmemblk
