# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2020, Intel Corporation

#
# examples/libpmem2/log/Makefile -- build the log example
#
PROGS = log

LIBS = -lpmem2

include ../../Makefile.inc

log: log.o
