# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_realloc/Makefile -- build obj_realloc unit test
#
TARGET = obj_realloc
OBJS = obj_realloc.o

LIBPMEMOBJ=internal-debug

include ../Makefile.inc
