#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_realloc/TEST0 -- unit test for pmemobj_realloc and
# pmemobj_zrealloc
#

. ../unittest/unittest.sh

require_test_type medium

require_fs_type any

setup

expect_normal_exit $PMEMPOOL$EXESUFFIX\
	create obj --layout realloc --size=512M $DIR/testfile1

export PMEM_IS_PMEM_FORCE=1
expect_normal_exit ./obj_realloc$EXESUFFIX $DIR/testfile1

check

pass
