#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_debug/TEST0 -- unit test for debug features
#

. $UNITTEST_SH

require_test_type medium
require_build_type debug static-debug
require_fs_type any

setup

export PMEMOBJ_LOG_LEVEL=4
expect_normal_exit ./obj_debug$EXESUFFIX $DIR/testfile1 f

$GREP _pobj_debug_notice ./pmemobj$UNITTEST_NUM.log > grep$UNITTEST_NUM.log

check

pass
