#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/obj_debug/TEST5 -- unit test for debug features
#

. $UNITTEST_SH

require_test_type medium
require_build_type debug static-debug
require_fs_type any

FUNCS=17

setup

for op_index in $(seq 0 $FUNCS); do
	expect_abnormal_exit ./obj_debug$EXESUFFIX $DIR/testfile1 s $op_index 2> /dev/null
done

pass
