# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/obj_include/Makefile -- build include tests
#
TARGET = obj_include
OBJS = obj_atomic_base_include.o obj_atomic_include.o \
       obj_base_include.o obj_iterator_base_include.o obj_iterator_include.o \
       obj_lists_atomic_base_include.o obj_lists_atomic_include.o \
       obj_pool_base_include.o obj_pool_include.o obj_thread_include.o \
       obj_tx_base_include.o obj_tx_include.o obj_types_include.o

LIBPMEMOBJ=y

include ../Makefile.inc

