# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/obj_tx_invalid/Makefile -- build obj_tx_invalid unit test
#
TARGET = obj_tx_invalid
OBJS = obj_tx_invalid.o

LIBPMEMOBJ=y
LIBPMEMCOMMON=y

include ../Makefile.inc
