# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_pmalloc_mt/Makefile -- build obj_pmalloc_mt unit test
#
TARGET = obj_pmalloc_mt
OBJS = obj_pmalloc_mt.o

LIBPMEMOBJ=internal-debug

include ../Makefile.inc
