#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2023, Intel Corporation

#
# src/test/obj_pmalloc_mt/TEST8 -- multithreaded allocator test
#	(short) w/ iterations
#

. ../unittest/unittest.sh

require_fs_type pmem
require_test_type short

setup

TEST_FILE_PATH=$DIR/testfile

rm -f $TEST_FILE_PATH

PMEM_IS_PMEM_FORCE=1 expect_normal_exit\
	./obj_pmalloc_mt$EXESUFFIX 32 1000 100 $TEST_FILE_PATH

rm $TEST_FILE_PATH

PMEM_IS_PMEM_FORCE=1 expect_normal_exit\
	./obj_pmalloc_mt$EXESUFFIX 32 1000 100 $TEST_FILE_PATH

pass
