#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/obj_pmalloc_mt/TEST1 -- multithreaded allocator test
#	(medium non-helgrind/drd version)
#

. ../unittest/unittest.sh

require_fs_type any
require_test_type medium
configure_valgrind drd force-disable
configure_valgrind helgrind force-disable
setup

PMEM_IS_PMEM_FORCE=1 expect_normal_exit\
	./obj_pmalloc_mt$EXESUFFIX 32 1000 $DIR/testfile

pass
