# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2019, Intel Corporation

#
# src/test/ctl_cow/Makefile -- build ctl_cow test
#
TARGET = ctl_cow
OBJS = ctl_cow.o

LIBPMEMBLK=y
LIBPMEMLOG=y
LIBPMEMOBJ=y

include ../Makefile.inc
