# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2019-2020, Intel Corporation

#
# examples/libpmem2/Makefile -- build the libpmem2 examples
#

PROGS = basic advanced unsafe_shutdowns

LIBS = -lpmem2

include ../Makefile.inc

basic: basic.o

advanced: advanced.o

unsafe_shutdowns: unsafe_shutdowns.o
