# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2019, Intel Corporation

#
# examples/libpmem2/Makefile -- build the libpmem2 examples
#

PROGS = basic advanced

LIBS = -lpmem2

include ../Makefile.inc

basic: basic.o

advanced: advanced.o
