#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_critnib/TEST0 -- unit test for critnib hash table
#

. ../unittest/unittest.sh

require_test_type medium
require_fs_type none

setup

expect_normal_exit ./obj_critnib$EXESUFFIX

pass
