# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/obj_tx_lock/Makefile -- build obj_tx_locks unit test
#

TARGET = obj_tx_lock
OBJS = obj_tx_lock.o

LIBPMEMOBJ=internal-debug

include ../Makefile.inc
