#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2023, Intel Corporation

#
# src/test/obj_tx_lock/TEST0 -- unit test for pmemobj_tx_lock()
#                               with DRD disabled
#

. ../unittest/unittest.sh

require_test_type medium
set_test_labels fault_injection

configure_valgrind drd force-disable

setup

expect_normal_exit ./obj_tx_lock$EXESUFFIX $DIR/testfile1 f

expect_normal_exit ./obj_tx_lock$EXESUFFIX $DIR/testfile2 l n a

pass
