#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2019, Intel Corporation

#
# src/test/obj_tx_lock/TEST1 -- unit test for pmemobj_tx_lock() with DRD
#                               and Helgrind disabled
#

. ../unittest/unittest.sh

require_test_type medium

configure_valgrind drd force-disable
configure_valgrind helgrind force-disable

setup

expect_normal_exit ./obj_tx_lock$EXESUFFIX $DIR/testfile1 t w

pass
