# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2022, Intel Corporation

#
# src/test/pmem2_mover/Makefile -- build pmem2_mover test
#
TOP = ../../..

vpath %.c $(TOP)/src/test/unittest

TARGET = blk_future
OBJS = blk_future.o

LIBPMEMBLK=y
LIBMINIASYNC=y

include ../Makefile.inc
