# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018, Intel Corporation

#
# src/test/util_badblock/Makefile -- build util_badblock test
#
#
TARGET = util_badblock
OBJS = util_badblock.o

LIBPMEMCOMMON=y

include ../Makefile.inc
