#!/usr/bin/env bash
#
# Copyright 2018-2019, Intel Corporation
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in
#       the documentation and/or other materials provided with the
#       distribution.
#
#     * Neither the name of the copyright holder nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

#
# src/test/util_badblock/TEST10 -- unit test for util_badblock
#                                 - regular file with no bad blocks
#                                   on a pmem filesystem
#

. ../unittest/unittest.sh

require_test_type medium
require_linked_with_ndctl ./util_badblock$EXESUFFIX

#
# Listing bad blocks on a pmem filesystem requires superuser privileges.
#
require_fs_type pmem
require_sudo_allowed

# it's not possible to run sudo under Valgrind
configure_valgrind force-disable

setup

$FALLOCATE 100M $DIR/testfile1

ENV="\
LD_LIBRARY_PATH=${LD_LIBRARY_PATH} \
UNITTEST_NUM=${UNITTEST_NUM} \
UNITTEST_NAME=${UNITTEST_NAME} \
UNITTEST_LOG_LEVEL=${UNITTEST_LOG_LEVEL}"

expect_normal_exit sudo bash -c \"${ENV} \
	./util_badblock$EXESUFFIX $DIR/testfile1 l \"

check

pass
