#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018-2019, Intel Corporation

#
# src/test/util_badblock/TEST8 -- unit test for util_badblock
#                                 - create and open a pool
#                                   on dax device with bad blocks
#

. ../unittest/unittest.sh

require_test_type medium

require_badblock_tests_enabled dax_device
require_linked_with_ndctl ./util_badblock$EXESUFFIX

setup

. ../common_badblock.sh

badblock_test_init dax_device

# create a pool
expect_normal_exit ./util_badblock$EXESUFFIX $FULLDEV r

turn_on_checking_bad_blocks $FULLDEV

# inject bad block: OFF=11 LEN=1
ndctl_inject_error $NAMESPACE 11 1

expect_bad_blocks $NAMESPACE

# open a pool with bad blocks
expect_abnormal_exit ./util_badblock$EXESUFFIX $FULLDEV o

ndctl_uninject_error $FULLDEV $NAMESPACE 11 1

badblock_test_fini

check

pass
