#!/usr/bin/env bash
#
# Copyright 2017, Intel Corporation
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in
#       the documentation and/or other materials provided with the
#       distribution.
#
#     * Neither the name of the copyright holder nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

#
# src/test/util_badblock/TEST2 -- unit test for util_badblock
#
export UNITTEST_NAME=util_badblock/TEST2
export UNITTEST_NUM=2

# standard unit test setup
. ../unittest/unittest.sh

DEVDAX_BADBLOCK=../../tools/plugins/plugin_badblocks_devdax

require_test_type medium
require_kernel_module nfit_test_iomap
require_command ndctl
require_superuser

require_binary $DEVDAX_BADBLOCK/plugin_badblocks_devdax.so

setup

ndctl disable-region all &> /dev/null

modprobe -r nfit_test

modprobe nfit_test
ndctl disable-region all &> /dev/null
ndctl zero-labels all &> /dev/null
ndctl enable-region all &> /dev/null

BUS="nfit_test.0"
REGION=`ndctl list -b $BUS -t pmem -Ri | sed '/dev/!d;s/[", ]//g;s/dev://g' | tail -1`
DEVICE=`ndctl create-namespace -b $BUS -r $REGION -f -m dax -a 4096 | sed '/chardev/!d;s/[", ]//g;s/chardev://g'`

FULLDEV="/dev/$DEVICE"

NBADBLOCKS=`cat /sys/bus/platform/devices/$BUS/ndbus1/$REGION/badblocks | wc -l`

expect_normal_exit ./util_badblock$EXESUFFIX $FULLDEV $NBADBLOCKS $DEVDAX_BADBLOCK

NBADBLOCKS=`cat /sys/bus/platform/devices/$BUS/ndbus1/$REGION/badblocks | wc -l`

ndctl disable-region all &> /dev/null
modprobe -r nfit_test

if [ "$NBADBLOCKS" -ne 0 ]; then
	exit 1
fi

pass
