#!/usr/bin/env bash
#
# Copyright 2018-2019, Intel Corporation
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in
#       the documentation and/or other materials provided with the
#       distribution.
#
#     * Neither the name of the copyright holder nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

#
# src/test/util_badblock/TEST5 -- unit test for util_badblock
#                                 - regular file with no bad blocks
#                                 - only list bad blocks
#

. ../unittest/unittest.sh

require_test_type medium
require_fs_type non-pmem
require_linked_with_ndctl ./util_badblock$EXESUFFIX

require_nfit_tests_enabled
require_sudo_allowed
require_kernel_module nfit_test
require_linked_with_ndctl ./util_badblock$EXESUFFIX
require_command ndctl

setup

. ../common_badblock.sh

ndctl_nfit_test_init

DEVICE=$(ndctl_nfit_test_get_block_device)
NAMESPACE=$(ndctl_nfit_test_get_namespace_of_device $DEVICE)

FULLDEV="/dev/$DEVICE"
MOUNT_DIR="$DIR/mnt-pmem"

ndctl_nfit_test_mount_pmem $FULLDEV $MOUNT_DIR

FILE="$MOUNT_DIR/file"
fallocate -l 1M $FILE

expect_normal_exit ./util_badblock$EXESUFFIX $FILE l

ndctl_nfit_test_fini $MOUNT_DIR

check

pass
