#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018-2019, Intel Corporation

#
# src/test/util_badblock/TEST1 -- unit test for util_badblock
#                                 - dax device with no bad blocks
#

. ../unittest/unittest.sh

require_test_type medium
require_fs_type any
require_linked_with_ndctl ./util_badblock$EXESUFFIX

require_dax_devices 1

setup

expect_normal_exit ./util_badblock$EXESUFFIX ${DEVICE_DAX_PATH[0]} l

check

pass
