#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018-2019, Intel Corporation

#
# src/test/util_badblock/TEST0 -- unit test for util_badblock
#                                 - regular file with no bad blocks
#                                   on a non-pmem filesystem
#

. $UNITTEST_SH

require_test_type medium

# pmem FS is tested in TEST10
require_fs_type non-pmem

require_linked_with_ndctl ./util_badblock$EXESUFFIX

setup

$FALLOCATE 100M $DIR/testfile1

expect_normal_exit ./util_badblock$EXESUFFIX $DIR/testfile1 l

check

pass
