#!/usr/bin/env bash
#
# Copyright 2017, Intel Corporation
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in
#       the documentation and/or other materials provided with the
#       distribution.
#
#     * Neither the name of the copyright holder nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

#
# src/test/util_badblock/TEST4 -- unit test for util_badblock
#
export UNITTEST_NAME=util_badblock/TEST4
export UNITTEST_NUM=4

# standard unit test setup
. ../unittest/unittest.sh

require_test_type medium
require_fs_type any
require_build_type debug nondebug

setup

require_fs_name ext4

TEST_BADBLOCK=../../tools/plugins/plugin_badblocks_test

fallocate -l 100M $DIR/testfile11
fallocate -l 100M $DIR/testfile12

create_poolset $DIR/testset1 64M:$DIR/testfile11:x 64M:$DIR/testfile12:x

echo "1 1
2 2
3 3
4 4
" > $DIR/testfile11_badblock_config

echo "5 5
6 6
" > $DIR/testfile12_badblock_config

expect_normal_exit ./util_badblock$EXESUFFIX $DIR/testset1 6 $TEST_BADBLOCK

expect_normal_exit ./util_badblock$EXESUFFIX $DIR/testset1 0 $TEST_BADBLOCK

pass
