#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2014-2023, Intel Corporation

#
# src/test/traces_pmem/TEST0 -- unit test traces for libraries pmem
#

. ../unittest/unittest.sh

require_test_type medium

require_fs_type none
require_build_type debug static-debug

setup

export PMEM_LOG_LEVEL=4
export PMEM_LOG_FILE=./trace_pmem$UNITTEST_NUM.log
export PMEMOBJ_LOG_LEVEL=4
export PMEMOBJ_LOG_FILE=./trace_pmemobj$UNITTEST_NUM.log

expect_normal_exit ./traces_pmem$EXESUFFIX

# We want to check if traces are enabled and correctness of printed
# string format. We can't rely on full output (because of different
# machines configurations), hence comparison of only first 3 lines.
head -n 3 $PMEM_LOG_FILE > ./trace_pmem_head$UNITTEST_NUM.log
head -n 3 $PMEMOBJ_LOG_FILE > ./trace_pmemobj_head$UNITTEST_NUM.log

check

pass
