# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_tx_add_range_direct/Makefile -- build obj_tx_add_range_direct
# unit test
#
TARGET = obj_tx_add_range_direct
OBJS = obj_tx_add_range_direct.o

LIBPMEMCOMMON=y
LIBPMEMOBJ=y

include ../Makefile.inc
INCS += -I$(TOP)/src/libpmemobj/
