# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2016, Intel Corporation

#
# src/test/ex_libpmemlog/Makefile -- build ex_libpmemlog unittest
#

all: $(EXAMPLES)
	$(MAKE) -C $(EX_LIBPMEMLOG)

include ../Makefile.inc

EXAMPLES=$(EX_LIBPMEMLOG)/logfile/addlog \
	$(EX_LIBPMEMLOG)/logfile/printlog

