# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2020-2021, Intel Corporation
#

#
# src/test/pmem_eADR_functions/Makefile -- build pmem_eADR_functions unit test
#
TOP = ../../..

include ../../common.inc

LIBPMEM=y

TARGET = pmem_eADR_functions
OBJS += pmem_eADR_functions.o

include ../Makefile.inc
