# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2020, Intel Corporation

#
# examples/libpmem2/redo/Makefile -- simple redo log implementation
PROGS = redo

LIBS = -lpmem2

include ../../Makefile.inc

redo: redo.o
