# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/remote_obj_basic/Makefile -- build remote_obj_basic unit test
#
SCP_TO_REMOTE_NODES = y

TARGET = remote_obj_basic
OBJS = remote_obj_basic.o

LIBPMEMOBJ=y

include ../Makefile.inc
