#!/usr/bin/env bash
#
# Copyright 2016-2019, Intel Corporation
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in
#       the documentation and/or other materials provided with the
#       distribution.
#
#     * Neither the name of the copyright holder nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

#
# src/test/remote_obj_basic/TEST3 -- unit test for remote tests support
#

# timeout value for this test in seconds
TIMEOUT=5

. ../unittest/unittest.sh

require_test_type medium

setup

# how much remote nodes are required
require_nodes 1

# create a unique name for pool file
POOL_FILE=${NODE_DIR[0]}/pool-remote_obj_basic-TEST$UNITTEST_NUM-$$-`$DATE +%s`

# create poolset file
POOLSET_FILE=pool$UNITTEST_NUM.set
create_poolset $POOLSET_FILE 10M:$POOL_FILE:x

# copy required files to remote nodes
copy_files_to_node 0 ${NODE_DIR[0]} $POOLSET_FILE

# remove local poolset file
rm -f $POOLSET_FILE

# PID file name for remote test run in background
PID_FILE="pid-file-$$.txt"

# register the list of PID files to be cleaned in case of an error
clean_remote_node 0 $PID_FILE

#
# Run commands on remote nodes
# (run_on_node or run_on_node_background can be used here).
#
# LD_LIBRARY_PATH for the n-th remote node can be provided
# in the array NODE_LD_LIBRARY_PATH[n].
#
expect_normal_exit run_on_node_background 0 $PID_FILE ./remote_obj_basic$EXESUFFIX create ${NODE_DIR[0]}$POOLSET_FILE
expect_normal_exit wait_on_node 0 $PID_FILE $TIMEOUT
expect_normal_exit run_on_node_background 0 $PID_FILE ./remote_obj_basic$EXESUFFIX open ${NODE_DIR[0]}$POOLSET_FILE
expect_normal_exit wait_on_node 0 $PID_FILE $TIMEOUT
expect_normal_exit run_on_node 0 rm -f $POOL_FILE

check

pass
