#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/remote_obj_basic/TEST1 -- unit test for remote tests support
#

. $UNITTEST_SH

require_test_type medium

setup

# how much remote nodes are required
require_nodes 1

# create a unique name for pool file
POOL_FILE=${NODE_DIR[0]}/pool-remote_obj_basic-TEST$UNITTEST_NUM-$$-`$DATE +%s`

# create poolset file
POOLSET_FILE=pool$UNITTEST_NUM.set
create_poolset $POOLSET_FILE 10M:$POOL_FILE:x

# copy required files to remote nodes
copy_files_to_node 0 ${NODE_DIR[0]} $POOLSET_FILE

# remove local poolset file
rm -f $POOLSET_FILE

#
# Run commands on remote nodes
# (run_on_node or run_on_node_background can be used here).
#
# LD_LIBRARY_PATH for the n-th remote node can be provided
# in the array NODE_LD_LIBRARY_PATH[n].
#
expect_normal_exit run_on_node 0 ./remote_obj_basic$EXESUFFIX create ${NODE_DIR[0]}$POOLSET_FILE
expect_normal_exit run_on_node 0 ./remote_obj_basic$EXESUFFIX open ${NODE_DIR[0]}$POOLSET_FILE
expect_normal_exit run_on_node 0 rm -f $POOL_FILE

check

pass
