# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/libpmempool_rm/Makefile -- build libpmempool rm tests
#
TARGET = libpmempool_rm
OBJS = libpmempool_rm.o

LIBPMEMOBJ=y
LIBPMEMPOOL=y

include ../Makefile.inc
