#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2023, Intel Corporation
#
#
# libpmempool_rm/TEST0 -- test for pmempool_rm with single-file pool
#

. ../unittest/unittest.sh

require_test_type medium

require_fs_type any

setup

enable_log_append

expect_normal_exit $PMEMPOOL$EXESUFFIX create obj $DIR/pool1.obj
expect_normal_exit $PMEMPOOL$EXESUFFIX create obj $DIR/pool2.obj
check_files $DIR/pool1.obj $DIR/pool2.obj

# this should remove all the pool files
expect_normal_exit ./libpmempool_rm$EXESUFFIX $DIR/pool1.obj $DIR/pool2.obj

# check if all pool files are removed
check_no_files $DIR/pool1.obj $DIR/pool2.obj

# this should report errors for all files
expect_normal_exit ./libpmempool_rm$EXESUFFIX $DIR/pool1.obj $DIR/pool2.obj
# this should ignore all errors
expect_normal_exit ./libpmempool_rm$EXESUFFIX -f $DIR/pool1.obj $DIR/pool2.obj

check

pass
