#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2018, Intel Corporation
#
#
# libpmempool_rm/TEST3 -- test for pmempool_rm with directories
#

. ../unittest/unittest.sh

require_test_type medium

require_fs_type any

setup

enable_log_append

mkdir $DIR/dir.1
mkdir $DIR/dir.2
mkdir $DIR/dir.2/dir.3

expect_normal_exit ./libpmempool_rm$EXESUFFIX $DIR/dir.1 $DIR/dir.2 $DIR/dir.2/dir.3
expect_normal_exit ./libpmempool_rm$EXESUFFIX -f $DIR/dir.1 $DIR/dir.2 $DIR/dir.2/dir.3

check

pass
