# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/obj_fragmentation2/Makefile -- build obj_fragmentation2 test
#
TARGET = obj_fragmentation2
OBJS = obj_fragmentation2.o

LIBPMEMOBJ=y

include ../Makefile.inc
