#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2019, Intel Corporation

#
# src/test/ex_librpmem_hello/TEST0 -- hello example unittest
#

. $UNITTEST_SH

require_test_type short

require_nodes 2

require_node_libfabric 0 $RPMEM_PROVIDER
require_node_libfabric 1 $RPMEM_PROVIDER

setup

init_rpmem_on_node 1 0

POOLSET=pool.set
TEST_FILE_REMOTE="testfile_remote"

create_poolset $DIR/$POOLSET \
	32M:${NODE_DIR[0]}/$TEST_FILE_REMOTE:x

copy_files_to_node 0 ${NODE_DIR[0]} $DIR/$POOLSET

rm_files_from_node 0 ${NODE_DIR[0]}$TEST_FILE_REMOTE

LOG=stdout0.log
rm_files_from_node 1 ${NODE_DIR[1]}/../$LOG

for i in `seq 1 4`; do
	expect_normal_exit run_on_node 1 \""./hello \
			${NODE_ADDR[0]} $POOLSET >> $LOG\""
done

check

pass
