# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/pmempool_sync/Makefile -- build pmempool sync test
#

USE_DDMAP=y
USE_PMEMOBJCLI=y
USE_PMEMSPOIL=y
USE_OBJ_VERIFY=y

include ../Makefile.inc
