#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2017-2024, Intel Corporation
#
#
# pmempool_sync/TEST12 -- test for checking pmempool sync;
#                         a case with incorrect part's uuid and correct checksum
#

. ../unittest/unittest.sh

require_test_type medium

require_fs_type any

setup

LOG=out${UNITTEST_NUM}.log
LOG_TEMP=out${UNITTEST_NUM}_part.log
rm -f $LOG && touch $LOG
rm -f $LOG_TEMP && touch $LOG_TEMP

LAYOUT=OBJ_LAYOUT
POOLSET=$DIR/pool0.set

# Create poolset file
create_poolset $POOLSET \
	20M:$DIR/testfile1:x \
	20M:$DIR/testfile2:x \
	21M:$DIR/testfile3:x \
	R \
	40M:$DIR/testfile4:x \
	20M:$DIR/testfile5:x

# Create poolset
expect_normal_exit $PMEMPOOL$EXESUFFIX create --layout=$LAYOUT\
	obj $POOLSET
cat $LOG >> $LOG_TEMP

# Corrupt metadata in primary replica, recalculate checksum
expect_normal_exit $PMEMSPOIL $DIR/testfile1 pool_hdr.uuid=0000000000000000\
	"pool_hdr.f:checksum_gen" >> $LOG_TEMP

# Try to synchronize replicas
expect_abnormal_exit $PMEMPOOL$EXESUFFIX sync $POOLSET &>> $LOG_TEMP

mv $LOG_TEMP $LOG

check

pass
