#!/usr/bin/env bash
#
# Copyright 2018, Intel Corporation
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in
#       the documentation and/or other materials provided with the
#       distribution.
#
#     * Neither the name of the copyright holder nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
#
# pmempool_sync/TEST53 -- test for sync command with badblocks
#                         - overlapping but fixable bad blocks:
#
# replica #0 part #0 & replica #1 part #1: blocks: offset: 8000 length: 1000
# replica #0 part #1 & replica #1 part #0: blocks: offset: 7992 length: 16
# replica #0 part #1 & replica #1 part #0: blocks: offset: 8016 8032 8048 8064 8080 length: 8
# replica #0 part #1 & replica #1 part #0: blocks: offset: 8992 length: 16
# replica #2 part #0 & replica #2 part #1: blocks: offset: 7000 9000 length: 32
#

# standard unit test setup
. ../unittest/unittest.sh

require_test_type medium
require_fs_type any
require_build_type debug nondebug
require_linked_with_ndctl $PMEMPOOL$EXESUFFIX

setup

export PMEMPOOL_LOG_LEVEL=10

LOG=out${UNITTEST_NUM}.log
rm -rf $LOG && touch $LOG

POOLSET=$DIR/testset1
create_poolset $POOLSET 10M:$DIR/testfile_r0_p0:z 10M:$DIR/testfile_r0_p1:z 10M:$DIR/testfile_r0_p2:z \
			R \
			10M:$DIR/testfile_r1_p0:z 10M:$DIR/testfile_r1_p1:z 10M:$DIR/testfile_r1_p2:z \
			R \
			10M:$DIR/testfile_r2_p0:z 10M:$DIR/testfile_r2_p1:z 10M:$DIR/testfile_r2_p2:z

expect_normal_exit $PMEMPOOL$EXESUFFIX rm $POOLSET
expect_normal_exit $PMEMPOOL$EXESUFFIX create obj --layout pmempool$SUFFIX $POOLSET

expect_normal_exit "$OBJ_VERIFY$EXESUFFIX $POOLSET pmempool$SUFFIX c v &>> $LOG"

# inject errors - zero blocks:
dd if=/dev/zero of=$DIR/testfile_r0_p0 bs=512 seek=8000 count=1000 conv=notrunc status=none
dd if=/dev/zero of=$DIR/testfile_r1_p1 bs=512 seek=8000 count=1000 conv=notrunc status=none

dd if=/dev/zero of=$DIR/testfile_r0_p1 bs=512 seek=7992 count=16 conv=notrunc status=none
dd if=/dev/zero of=$DIR/testfile_r1_p0 bs=512 seek=7992 count=16 conv=notrunc status=none

dd if=/dev/zero of=$DIR/testfile_r0_p1 bs=512 seek=8016 count=8 conv=notrunc status=none
dd if=/dev/zero of=$DIR/testfile_r1_p0 bs=512 seek=8016 count=8 conv=notrunc status=none

dd if=/dev/zero of=$DIR/testfile_r0_p1 bs=512 seek=8032 count=8 conv=notrunc status=none
dd if=/dev/zero of=$DIR/testfile_r1_p0 bs=512 seek=8032 count=8 conv=notrunc status=none

dd if=/dev/zero of=$DIR/testfile_r0_p1 bs=512 seek=8048 count=8 conv=notrunc status=none
dd if=/dev/zero of=$DIR/testfile_r1_p0 bs=512 seek=8048 count=8 conv=notrunc status=none

dd if=/dev/zero of=$DIR/testfile_r0_p1 bs=512 seek=8064 count=8 conv=notrunc status=none
dd if=/dev/zero of=$DIR/testfile_r1_p0 bs=512 seek=8064 count=8 conv=notrunc status=none

dd if=/dev/zero of=$DIR/testfile_r0_p1 bs=512 seek=8080 count=8 conv=notrunc status=none
dd if=/dev/zero of=$DIR/testfile_r1_p0 bs=512 seek=8080 count=8 conv=notrunc status=none

dd if=/dev/zero of=$DIR/testfile_r0_p1 bs=512 seek=8992 count=16 conv=notrunc status=none
dd if=/dev/zero of=$DIR/testfile_r1_p0 bs=512 seek=8992 count=16 conv=notrunc status=none

dd if=/dev/zero of=$DIR/testfile_r2_p0 bs=512 seek=7000 count=32 conv=notrunc status=none
dd if=/dev/zero of=$DIR/testfile_r2_p1 bs=512 seek=7000 count=32 conv=notrunc status=none

dd if=/dev/zero of=$DIR/testfile_r2_p0 bs=512 seek=9000 count=32 conv=notrunc status=none
dd if=/dev/zero of=$DIR/testfile_r2_p1 bs=512 seek=9000 count=32 conv=notrunc status=none

# create recovery files with bad blocks

# r0_p0 & r1_p1
echo "$((8000 * 512)) $((1000 * 512))" > $DIR/testset1_r0_p0_badblocks.txt
echo "$((8000 * 512)) $((1000 * 512))" > $DIR/testset1_r1_p1_badblocks.txt

# r0_p1 & r1_p0
echo "$((7992 * 512)) $((16 * 512))" > $DIR/testset1_r0_p1_badblocks.txt
echo "$((7992 * 512)) $((16 * 512))" > $DIR/testset1_r1_p0_badblocks.txt

echo "$((8016 * 512)) $((8 * 512))" >> $DIR/testset1_r0_p1_badblocks.txt
echo "$((8016 * 512)) $((8 * 512))" >> $DIR/testset1_r1_p0_badblocks.txt

echo "$((8032 * 512)) $((8 * 512))" >> $DIR/testset1_r0_p1_badblocks.txt
echo "$((8032 * 512)) $((8 * 512))" >> $DIR/testset1_r1_p0_badblocks.txt

echo "$((8048 * 512)) $((8 * 512))" >> $DIR/testset1_r0_p1_badblocks.txt
echo "$((8048 * 512)) $((8 * 512))" >> $DIR/testset1_r1_p0_badblocks.txt

echo "$((8064 * 512)) $((8 * 512))" >> $DIR/testset1_r0_p1_badblocks.txt
echo "$((8064 * 512)) $((8 * 512))" >> $DIR/testset1_r1_p0_badblocks.txt

echo "$((8080 * 512)) $((8 * 512))" >> $DIR/testset1_r0_p1_badblocks.txt
echo "$((8080 * 512)) $((8 * 512))" >> $DIR/testset1_r1_p0_badblocks.txt

echo "$((8992 * 512)) $((16 * 512))" >> $DIR/testset1_r0_p1_badblocks.txt
echo "$((8992 * 512)) $((16 * 512))" >> $DIR/testset1_r1_p0_badblocks.txt

# r2_p0 & r2_p1
echo "$((7000 * 512)) $((32 * 512))" > $DIR/testset1_r2_p0_badblocks.txt
echo "$((7000 * 512)) $((32 * 512))" > $DIR/testset1_r2_p1_badblocks.txt

echo "$((9000 * 512)) $((32 * 512))" >> $DIR/testset1_r2_p0_badblocks.txt
echo "$((9000 * 512)) $((32 * 512))" >> $DIR/testset1_r2_p1_badblocks.txt

echo "0 0" >> $DIR/testset1_r0_p0_badblocks.txt
echo "0 0" >> $DIR/testset1_r0_p1_badblocks.txt
echo "0 0" >> $DIR/testset1_r1_p0_badblocks.txt
echo "0 0" >> $DIR/testset1_r1_p1_badblocks.txt
echo "0 0" >> $DIR/testset1_r2_p0_badblocks.txt
echo "0 0" >> $DIR/testset1_r2_p1_badblocks.txt

# create recovery files - no bad blocks
echo "0 0" > $DIR/testset1_r0_p2_badblocks.txt
echo "0 0" > $DIR/testset1_r1_p2_badblocks.txt
echo "0 0" > $DIR/testset1_r2_p2_badblocks.txt

# fail because of bad blocks
expect_abnormal_exit "$OBJ_VERIFY$EXESUFFIX $POOLSET pmempool$SUFFIX v &>> $LOG"

# fix bad blocks
expect_normal_exit "$PMEMPOOL$EXESUFFIX sync -v -b $POOLSET &>> $LOG"

expect_normal_exit "$PMEMPOOL$EXESUFFIX check -v $POOLSET >> $LOG"
expect_normal_exit "$PMEMPOOL$EXESUFFIX info -k $POOLSET >> $LOG"
expect_normal_exit "$OBJ_VERIFY$EXESUFFIX $POOLSET pmempool$SUFFIX v &>> $LOG"

check

pass
