#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018-2024, Intel Corporation
#
#
# pmempool_sync/TEST23 -- test for pmempool sync
#
# sync with replica with switched parts
# Ref: pmem/issues#730
#

. ../unittest/unittest.sh

require_test_type medium
require_fs_type any

setup

LOG=out${UNITTEST_NUM}.log
LOG_TEMP=out${UNITTEST_NUM}_part.log
rm -f $LOG && touch $LOG
rm -f $LOG_TEMP && touch $LOG_TEMP

LAYOUT=OBJ_LAYOUT$SUFFIX
POOLSET1=$DIR/poolset1
POOLSET2=$DIR/poolset2

# Create poolset files
create_poolset $POOLSET1 \
	8M:$DIR/part00:x \
	8M:$DIR/part01:x \
	r \
	8M:$DIR/part10:x \
	8M:$DIR/part11:x

# polset2 has switched parts in the second replica
create_poolset $POOLSET2 \
	8M:$DIR/part00:x \
	8M:$DIR/part01:x \
	r \
	8M:$DIR/part11:x \
	8M:$DIR/part10:x

# Log poolset structures
echo poolset1: >> $LOG_TEMP
cat $POOLSET1 >> $LOG_TEMP
echo poolset2: >> $LOG_TEMP
cat $POOLSET2 >> $LOG_TEMP

# Create a poolset
expect_normal_exit $PMEMPOOL$EXESUFFIX create --layout=$LAYOUT obj $POOLSET1
cat $LOG >> $LOG_TEMP

# Destroy the master replica
rm -f $DIR/part0*

# Try to synchronize replicas using the second poolset
expect_abnormal_exit $PMEMPOOL$EXESUFFIX sync $POOLSET2 >> $LOG_TEMP 2>&1

# Synchronize replicas using the first poolset
expect_normal_exit $PMEMPOOL$EXESUFFIX sync $POOLSET1 >> $LOG_TEMP

# Check metadata using pmempool info
dump_pool_info $POOLSET1 >> $LOG_TEMP

mv $LOG_TEMP $LOG

check
pass
