# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2021, Intel Corporation

#
# examples/libpmemset/basic/Makefile -- build the basic example
#
PROGS = basic

LIBS = -lpmem2 -lpmemset

include ../../Makefile.inc

basic: basic.o
