# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2014-2016, Intel Corporation

#
# src/test/checksum/Makefile -- build checksum unit test
#
TARGET = checksum
OBJS = checksum.o

LIBPMEMCOMMON=y
include ../Makefile.inc
