# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2017, Intel Corporation

#
# src/test/pmempool_rm_remote/Makefile -- build unittest for pmempool
# rm with remote replicas
#
SCP_TO_REMOTE_NODES=y

include ../Makefile.inc
