#!/usr/bin/env bash
#
# Copyright 2017-2019, Intel Corporation
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in
#       the documentation and/or other materials provided with the
#       distribution.
#
#     * Neither the name of the copyright holder nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
#
# pmempool_rm_remotie/TEST1 -- test for cli rm command with remote replica
#

. ../unittest/unittest.sh

require_test_type medium

require_fs_type any

setup

require_nodes 2

require_node_libfabric 0 $RPMEM_PROVIDER
require_node_libfabric 1 $RPMEM_PROVIDER

init_rpmem_on_node 1 0

OUT=stdout${UNITTEST_NUM}.log

# define files and directories
TEST_SET_LOCAL="testset_local"
TEST_SET_REMOTE="testset_remote"

# create and upload poolset files
create_poolset $DIR/$TEST_SET_LOCAL 20M:${NODE_DIR[1]}test_part0:x  20M:${NODE_DIR[1]}test_part1:x \
		20M:${NODE_DIR[1]}test_part2:x  20M:${NODE_DIR[1]}test_part3:x \
		m ${NODE_ADDR[0]}:$TEST_SET_REMOTE
create_poolset $DIR/$TEST_SET_REMOTE 20M:${NODE_DIR[0]}/test_part_remote0:x  20M:${NODE_DIR[0]}test_part_remote1:x \
		20M:${NODE_DIR[0]}test_part_remote2:x  20M:${NODE_DIR[0]}test_part_remote3:x

copy_files_to_node 0 ${NODE_DIR[0]} $DIR/$TEST_SET_REMOTE
copy_files_to_node 1 ${NODE_DIR[1]} $DIR/$TEST_SET_LOCAL

rm_files_from_node 0 ${NODE_DIR[0]}test_part_remote0  ${NODE_DIR[0]}test_part_remote1 \
		 ${NODE_DIR[0]}test_part_remote2 ${NODE_DIR[0]}test_part_remote3
rm_files_from_node 1  ${NODE_DIR[1]}test_part0 ${NODE_DIR[1]}test_part1 \
		${NODE_DIR[1]}test_part2 ${NODE_DIR[1]}test_part3

expect_normal_exit run_on_node 1 ../pmempool create obj ${NODE_DIR[1]}$TEST_SET_LOCAL

check_files_on_node 0 $TEST_SET_REMOTE test_part_remote0 \
		test_part_remote1 test_part_remote2 test_part_remote3
check_files_on_node 1 $TEST_SET_LOCAL test_part0 test_part1 test_part2 test_part3

# remove one part
rm_files_from_node 0 ${NODE_DIR[0]}test_part_remote2
check_no_files_on_node 0 test_part_remote2

# without force should fail
expect_abnormal_exit run_on_node 1 ../pmempool rm ${NODE_DIR[1]}$TEST_SET_LOCAL 1>> $OUT 2>&1

check_files_on_node 0 $TEST_SET_REMOTE test_part_remote0
check_files_on_node 1 $TEST_SET_LOCAL test_part0 test_part1

# with force should pass
expect_normal_exit run_on_node 1 ../pmempool rm -f ${NODE_DIR[1]}$TEST_SET_LOCAL 1>> $OUT 2>&1

check_no_files_on_node 0 test_part_remote0
check_no_files_on_node 1 test_part0 test_part1

check_local

pass
