#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2017-2018, Intel Corporation
#
#
# pmempool_rm_remotie/TEST0 -- test for cli rm command with remote replica
#

. ../unittest/unittest.sh

require_test_type medium

require_fs_type any

setup

require_nodes 2

require_node_libfabric 0 $RPMEM_PROVIDER
require_node_libfabric 1 $RPMEM_PROVIDER

init_rpmem_on_node 1 0

TEST_SET_LOCAL="testset_local"
TEST_SET_REMOTE="testset_remote"

# create and upload poolset files
create_poolset $DIR/$TEST_SET_LOCAL 20M:${NODE_DIR[1]}test_part0:x  20M:${NODE_DIR[1]}test_part1:x \
		20M:${NODE_DIR[1]}test_part2:x  20M:${NODE_DIR[1]}test_part3:x \
		m ${NODE_ADDR[0]}:$TEST_SET_REMOTE
create_poolset $DIR/$TEST_SET_REMOTE 20M:${NODE_DIR[0]}/test_part_remote0:x  20M:${NODE_DIR[0]}test_part_remote1:x \
		20M:${NODE_DIR[0]}test_part_remote2:x  20M:${NODE_DIR[0]}test_part_remote3:x

copy_files_to_node 0 ${NODE_DIR[0]} $DIR/$TEST_SET_REMOTE
copy_files_to_node 1 ${NODE_DIR[1]} $DIR/$TEST_SET_LOCAL

rm_files_from_node 0 ${NODE_DIR[0]}test_part_remote0  ${NODE_DIR[0]}test_part_remote1 \
		 ${NODE_DIR[0]}test_part_remote2 ${NODE_DIR[0]}test_part_remote3
rm_files_from_node 1  ${NODE_DIR[1]}test_part0 ${NODE_DIR[1]}test_part1 \
		${NODE_DIR[1]}test_part2 ${NODE_DIR[1]}test_part3

expect_normal_exit run_on_node 1 ../pmempool create obj ${NODE_DIR[1]}$TEST_SET_LOCAL

check_files_on_node 0 $TEST_SET_REMOTE test_part_remote0 \
		test_part_remote1 test_part_remote2 test_part_remote3
check_files_on_node 1 $TEST_SET_LOCAL test_part0 test_part1 test_part2 test_part3

# remove one part
rm_files_from_node 0 ${NODE_DIR[0]}test_part_remote2
check_no_files_on_node 0 test_part_remote2

expect_normal_exit run_on_node 1 ../pmempool rm -f ${NODE_DIR[1]}$TEST_SET_LOCAL

pass
