# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_tx_add_range/Makefile -- build obj_tx_add_range unit test
#
TOP = ../../..

TARGET = obj_tx_add_range
OBJS = obj_tx_add_range.o

LIBPMEMCOMMON=y
LIBPMEMOBJ=y

include ../Makefile.inc

INCS += -I$(TOP)/src/libpmemobj/
