#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_tx_add_range/TEST0 -- unit test for pmemobj_tx_add_range
#

. $UNITTEST_SH

require_test_type medium

# Pmemcheck is disabled here. The next test case (TEST1) will run the same test
# under pmemcheck
configure_valgrind pmemcheck force-disable
configure_valgrind memcheck force-disable

setup

expect_normal_exit ./obj_tx_add_range$EXESUFFIX $DIR/testfile0 0

pass
