#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_tx_add_range/TEST2 -- unit test for pmemobj_tx_add_range
#

. ../unittest/unittest.sh

require_test_type medium

configure_valgrind memcheck force-disable
require_fs_type pmem

setup

expect_normal_exit ./obj_tx_add_range$EXESUFFIX $DIR/testfile2 1

pass
