#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2014-2018, Intel Corporation
#
#
# pmempool_dump/TEST6 -- test for dump command
#

. $UNITTEST_SH

require_test_type medium

require_fs_type pmem non-pmem
require_build_type nondebug

setup

POOLSET=$DIR/pool.set
POOL_PART1=$DIR/pool.part1
POOL_PART2=$DIR/pool.part2
LOG=out${UNITTEST_NUM}.log
rm -f $LOG && touch $LOG

create_poolset $POOLSET 32M:$POOL_PART1:z 32M:$POOL_PART2:z

expect_normal_exit $PMEMPOOL create blk 512 $POOLSET
expect_normal_exit $PMEMWRITE $POOLSET 0:w:PMEMPOOL_DUMP_TEST
expect_normal_exit $PMEMPOOL dump -r 0 $POOLSET >> $LOG

check

pass
