#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2014-2018, Intel Corporation
#
#
# pmempool_dump/TEST0 -- test for dump command
#

. ../unittest/unittest.sh

require_test_type medium

require_fs_type pmem non-pmem

setup

POOL=$DIR/file.pool
LOG=out${UNITTEST_NUM}.log
rm -f $LOG && touch $LOG

expect_normal_exit $PMEMPOOL$EXESUFFIX create log $POOL
expect_normal_exit $PMEMWRITE$EXESUFFIX $POOL TEST
expect_normal_exit $PMEMPOOL$EXESUFFIX dump -b -o $LOG $POOL
echo >> $LOG
expect_normal_exit $PMEMPOOL$EXESUFFIX dump -b $POOL >> $LOG
echo >> $LOG

check

pass
