#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2014-2018, Intel Corporation
#
#
# pmempool_dump/TEST4 -- test for dump command
#

. $UNITTEST_SH

require_test_type medium

require_fs_type pmem non-pmem

setup

POOL=$DIR/file.pool
LOG=out${UNITTEST_NUM}.log
rm -f $LOG && touch $LOG

expect_normal_exit $PMEMPOOL$EXESUFFIX create log $POOL
expect_normal_exit $PMEMWRITE$EXESUFFIX $POOL TEST1TEST2TEST3TEST4
expect_normal_exit $PMEMPOOL$EXESUFFIX dump -c5 -o $LOG $POOL
expect_normal_exit $PMEMPOOL$EXESUFFIX dump -c5 $POOL >> $LOG

check

pass
