#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2014-2018, Intel Corporation
#
#
# pmempool_dump/TEST2 -- test for dump command
#

. ../unittest/unittest.sh

require_test_type medium

require_fs_type pmem non-pmem

setup

POOL=$DIR/file.pool
LOG=out${UNITTEST_NUM}.log
rm -f $LOG && touch $LOG

expect_normal_exit $PMEMPOOL$EXESUFFIX create log $POOL
expect_normal_exit $PMEMWRITE$EXESUFFIX $POOL TEST_test
expect_normal_exit $PMEMPOOL$EXESUFFIX dump -r5,6,7,8 -o $LOG $POOL
expect_normal_exit $PMEMPOOL$EXESUFFIX dump -r5-8 $POOL >> $LOG

check

pass
