#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2017-2019, Intel Corporation
#
#
# pmempool_info_remote/TEST0 -- test for info command with remote replica
#

. $UNITTEST_SH

require_test_type medium

require_fs_type any

setup

require_nodes 2

require_node_libfabric 0 $RPMEM_PROVIDER
require_node_libfabric 1 $RPMEM_PROVIDER

init_rpmem_on_node 1 0

# define files and directories
TEST_SET_LOCAL="testset_local"
TEST_SET_REMOTE="testset_remote"

TEST_FILE_LOCAL="testfile_local"
TEST_FILE_REMOTE="testfile_remote"

LOG=out${UNITTEST_NUM}.log

# create and upload poolset files
create_poolset $DIR/$TEST_SET_LOCAL 16M:${NODE_DIR[1]}/$TEST_FILE_LOCAL:x \
        m ${NODE_ADDR[0]}:$TEST_SET_REMOTE

create_poolset $DIR/$TEST_SET_REMOTE 17M:${NODE_DIR[0]}/$TEST_FILE_REMOTE:x

copy_files_to_node 0 ${NODE_DIR[0]} $DIR/$TEST_SET_REMOTE
copy_files_to_node 1 ${NODE_DIR[1]} $DIR/$TEST_SET_LOCAL

rm_files_from_node 0 ${NODE_DIR[0]}$TEST_FILE_REMOTE
rm_files_from_node 1 ${NODE_DIR[1]}$TEST_FILE_LOCAL

expect_normal_exit run_on_node 1 ../pmempool create obj ${NODE_DIR[1]}$TEST_SET_LOCAL
expect_normal_exit run_on_node 1 ../pmempool info ${NODE_DIR[1]}$TEST_SET_LOCAL > ./$LOG

check_local

pass
