# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_strdup/Makefile -- build obj_strdup unit test
#
TARGET = obj_strdup
OBJS = obj_strdup.o

LIBPMEMOBJ=y

include ../Makefile.inc
