#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_strdup/TEST0 -- unit test for pmemobj_strdup
#

. ../unittest/unittest.sh

require_test_type medium

setup

expect_normal_exit ./obj_strdup$EXESUFFIX $DIR/testfile1

pass
