# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_recreate/Makefile -- build obj_recreate test
#
TARGET = obj_recreate
OBJS = obj_recreate.o

LIBPMEMOBJ=y

include ../Makefile.inc
