#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

. $UNITTEST_SH

require_test_type medium

setup

expect_normal_exit\
	./obj_recreate$EXESUFFIX $DIR/testfile1

pass
