# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_lane/Makefile -- build obj_lane unit test
#

TARGET = obj_lane
OBJS = obj_lane.o

LIBPMEMOBJ=internal-debug

include ../Makefile.inc
