#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_lane/TEST1 -- multithreaded unit test for lanes
#

. $UNITTEST_SH

require_test_type medium

setup

expect_normal_exit ./obj_lane$EXESUFFIX m

check

pass
