# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2023, Intel Corporation

# This playbook is designed to install all required packages and
# configure Rocky Linux to execute tests.
# The playbook description and how to use it are available
# in the README.md file.

    - name: "Reboot platform to apply updates"
      reboot:
