# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018-2019, Intel Corporation

#
# src/test/obj_direct_volatile/Makefile -- build obj_direct_volatile unit test
#
TARGET = obj_direct_volatile
OBJS = obj_direct_volatile.o

LIBPMEMOBJ=y

include ../Makefile.inc
