#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018-2019, Intel Corporation

#
# src/test/obj_direct_volatile/TEST1 -- unit test for direct_volatile
#

. $UNITTEST_SH

require_test_type medium
require_fs_type any

# same as TEST0, but with pmemcheck
configure_valgrind pmemcheck force-enable

setup

expect_normal_exit ./obj_direct_volatile$EXESUFFIX $DIR/test1

pass
