ignore:
  - src/jemalloc/
  - src/windows/
  - src/test/

comment:
  layout: "diff"
  behavior: default
  require_changes: yes

parsers:
  gcov:
    branch_detection:
      conditional: false
      loop: false
      method: false
      macro: false
