# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2024, Intel Corporation

# You must instal pre-commit and configure your project to use it:
# $ pip install pre-commit
# $ pre-commit install --config .pre-commit-config.yml (in the repository root directory)
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# Use the following command to verify that pre-commit is installed and configured properly:
# $ pre-commit run --config ./.pre-commit-config.yml --all
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
    exclude: |
      (?x)(\.match$|
           src/test/unicode_match_script/unicodetest|
           src/test/util_poolset_parse/pool32.set|
           src/core/valgrind/drd.h|
           src/core/valgrind/helgrind.h|
           src/core/valgrind/memcheck.h|
           src/core/valgrind/valgrind.h)
  - id: end-of-file-fixer
    exclude: |
      (?x)(\.match$|
           src/core/valgrind/memcheck.h|
           src/test/checksum/file[0-9]|
           ^GIT_VERSION$)
  - id: check-yaml
  - id: check-added-large-files
