# You must instal pre-commit and configure your project to use it:
# $pip install pre-commit
# $pre-commit install (in the repository directory)
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
    exclude: |
      (?x)(\.match$|
           unicode_match_script|
           src\/test\/util_map_proc)
  - id: end-of-file-fixer
    exclude: |
      (?x)(\.match$|
           ^GIT_VERSION$)
  - id: check-yaml
  - id: check-added-large-files
