# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2019, Intel Corporation

#
# src/test/obj_ulog_size/Makefile -- build obj_ulog_size unit test
#

TOP = ../../..

TARGET = obj_ulog_size
OBJS = obj_ulog_size.o

LIBPMEMOBJ=y

include ../Makefile.inc
CFLAGS += -I$(TOP)/src/libpmemobj/
