# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_heap_state/Makefile -- build obj_heap_state test
#
TARGET = obj_heap_state
OBJS = obj_heap_state.o

LIBPMEMOBJ=y

include ../Makefile.inc
