#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

. $UNITTEST_SH

require_test_type medium
exclude_ppc64

setup

export PMEM_IS_PMEM_FORCE=1

create_poolset $DIR/testset1 16M:$DIR/testfile1 16M:$DIR/testfile2

expect_normal_exit\
	./obj_heap_state$EXESUFFIX $DIR/testset1

check

pass
