# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2019-2020, Intel Corporation
#

#
# src/test/obj_tx_user_data/Makefile -- build obj_tx_user_data unit test
#
TARGET = obj_tx_user_data
OBJS = obj_tx_user_data.o

LIBPMEMOBJ=y

include ../Makefile.inc
