#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/util_poolset/TEST2 -- unit test for util_pool_open()
#

. $UNITTEST_SH

require_test_type medium

require_fs_type non-pmem

exclude_ppc64

setup

export TEST_LOG_LEVEL=4
export TEST_LOG_FILE=./test$UNITTEST_NUM.log

MIN_POOL=$((4 * 1024 * 1024)) # 4MiB

# prepare pool sets
create_poolset $DIR/testset1 $MIN_POOL:$DIR/testfile11:x $MIN_POOL:$DIR/testfile12:x
create_poolset $DIR/testset2 $MIN_POOL:$DIR/testfile21:x $MIN_POOL:$DIR/testfile22:x
create_poolset $DIR/testset3 $MIN_POOL:$DIR/testfile31:x $MIN_POOL:$DIR/testfile32:x
create_poolset $DIR/testset4 $MIN_POOL:$DIR/testfile41:x $MIN_POOL:$DIR/testfile42:x
create_poolset $DIR/testset5 $MIN_POOL:$DIR/testfile51:x $MIN_POOL:$DIR/testfile52:x
create_poolset $DIR/testset6 $MIN_POOL:$DIR/testfile61:x $MIN_POOL:$DIR/testfile62:x
create_poolset $DIR/testset7 $MIN_POOL:$DIR/testfile71:x $MIN_POOL:$DIR/testfile72:x
create_poolset $DIR/testset8 $MIN_POOL:$DIR/testfile81:x $MIN_POOL:$DIR/testfile82:x
create_poolset $DIR/testset9 $MIN_POOL:$DIR/testfile91:x $MIN_POOL:$DIR/testfile92:x
create_poolset $DIR/testset10 $MIN_POOL:$DIR/testfile101:x $MIN_POOL:$DIR/testfile102:x
create_poolset $DIR/testset11 $MIN_POOL:$DIR/testfile111:x $MIN_POOL:$DIR/testfile112:x
create_poolset $DIR/testset12 $MIN_POOL:$DIR/testfile121:x $MIN_POOL:$DIR/testfile122:x

# create pool sets
expect_normal_exit ./util_poolset$EXESUFFIX c $MIN_POOL \
	$DIR/testset1 $DIR/testset2\
	$DIR/testset3 $DIR/testset4\
	$DIR/testset5 $DIR/testset6\
	$DIR/testset7 $DIR/testset8\
	$DIR/testset9 $DIR/testset10\
	$DIR/testset11 $DIR/testset12

# inject some errors
$PMEMSPOIL $DIR/testfile22 pool_hdr.checksum=0
$PMEMSPOIL $DIR/testfile32 pool_hdr.signature="ERROR" "pool_hdr.f:checksum_gen"
$PMEMSPOIL $DIR/testfile42 pool_hdr.major=99 "pool_hdr.f:checksum_gen"
$PMEMSPOIL $DIR/testfile52 pool_hdr.arch_flags="0000000000000000" "pool_hdr.f:checksum_gen"
$PMEMSPOIL $DIR/testfile62 pool_hdr.features.compat=0x12345678 "pool_hdr.f:checksum_gen"
$PMEMSPOIL $DIR/testfile72 pool_hdr.features.compat=0x12345678 "pool_hdr.f:checksum_gen"
$PMEMSPOIL $DIR/testfile82 pool_hdr.features.compat=0x12345678 "pool_hdr.f:checksum_gen"
$PMEMSPOIL $DIR/testfile91 pool_hdr.poolset_uuid="0123456789012345" "pool_hdr.f:checksum_gen"
$PMEMSPOIL $DIR/testfile101 pool_hdr.next_part_uuid="0123456789012345" "pool_hdr.f:checksum_gen"
$PMEMSPOIL $DIR/testfile111 pool_hdr.prev_part_uuid="0123456789012345" \
	pool_hdr.next_part_uuid="0123456789012345" "pool_hdr.f:checksum_gen"
$PMEMSPOIL $DIR/testfile121 pool_hdr.next_repl_uuid="0123456789012345" "pool_hdr.f:checksum_gen"

# now check if pool sets may be opened
expect_normal_exit ./util_poolset$EXESUFFIX o $MIN_POOL $MIN_PART\
	$DIR/testset1 $DIR/testset2\
	$DIR/testset3 $DIR/testset4\
	$DIR/testset5 $DIR/testset6\
	$DIR/testset7 $DIR/testset8\
	$DIR/testset9 $DIR/testset10\
	$DIR/testset11 $DIR/testset12

$GREP "<1>" $TEST_LOG_FILE | sed -e "s/^.*\][ ]*//g" > ./grep$UNITTEST_NUM.log

check

pass
