#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2017-2019, Intel Corporation

#
# src/test/util_poolset/TEST7 -- unit test for util_pool_open()
#
# case: negative test for local poolsets with the NOHDRS option
#

. $UNITTEST_SH

require_test_type medium
require_fs_type any

setup

RESVSIZE=$((4 * 1024 * 1024 * 1024)) # 4GiB
MIN_POOL=$((128 * 1024 * 1024)) # 128MiB
require_free_space $(( $MIN_POOL * 6 ))

export TEST_LOG_LEVEL=4
export TEST_LOG_FILE=./test$UNITTEST_NUM.log

# prepare pool sets

create_poolset $DIR/testset1 \
	$MIN_POOL:$DIR/testfile11:x \
	O NOHDRS

create_poolset $DIR/testset2 \
	$MIN_POOL:$DIR/testfile21:x \
	$MIN_POOL:$DIR/testfile22:x \
	O NOHDRS

create_poolset $DIR/testset3 \
	$MIN_POOL:$DIR/testfile31:x \
	r \
	$MIN_POOL:$DIR/testfile32:x \
	O NOHDRS

create_poolset $DIR/testset4\
	$RESVSIZE:$DIR/testdir41:d\
	O NOHDRS

create_poolset $DIR/testset5\
	$RESVSIZE:$DIR/testdir51:d $RESVSIZE:$DIR/testdir52:d\
	O NOHDRS

create_poolset $DIR/testset6\
	$RESVSIZE:$DIR/testdir61:d R $RESVSIZE:$DIR/testdir62:d\
	O NOHDRS

# attempt to create the pool sets

expect_normal_exit ./util_poolset$EXESUFFIX c $MIN_POOL\
	$DIR/testset1\
	$DIR/testset2\
	$DIR/testset3\
	$DIR/testset4\
	$DIR/testset5\
	$DIR/testset6

# Extract level 1 messages from the test log
$GREP "<1>" $TEST_LOG_FILE | sed -e "s/^.*\][ ]*//g" > ./grep$UNITTEST_NUM.log

check

pass
