#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2019, Intel Corporation

#
# src/test/util_poolset/TEST8 -- unit test for util_pool_open()
#

. ../unittest/unittest.sh

require_test_type medium
require_fs_type any

setup

RESVSIZE=$(((128 + 4) * 1024 * 1024))
MIN_POOL=$((128 * 1024 * 1024))

export TEST_LOG_LEVEL=8
export TEST_LOG_FILE=./test$UNITTEST_NUM.log

# prepare pool sets
create_poolset $DIR/testset1\
	$RESVSIZE:$DIR/testdir11:d\
	O SINGLEHDR # pass
create_poolset $DIR/testset2\
	$RESVSIZE:$DIR/testdir21:d $RESVSIZE:$DIR/testdir22:d\
	O SINGLEHDR # pass
create_poolset $DIR/testset3\
	$RESVSIZE:$DIR/testdir31:d R $RESVSIZE:$DIR/testdir32:d\
	O SINGLEHDR # pass
create_poolset $DIR/testset4\
	$RESVSIZE:$DIR/testdir41:d $RESVSIZE:$DIR/testdir42:d\
	R $RESVSIZE:$DIR/testdir43:d $RESVSIZE:$DIR/testdir44:d\
	O SINGLEHDR # pass
create_poolset $DIR/testset9\
	$RESVSIZE:$DIR/testdir91:d R $RESVSIZE:$DIR/testdir91/testdir92:d\
	O SINGLEHDR # pass

# should fail to open
expect_normal_exit ./util_poolset$EXESUFFIX o $MIN_POOL\
	$DIR/testset1\
	$DIR/testset2\
	$DIR/testset3\
	$DIR/testset4\
	$DIR/testset9

$GREP "<1>" $TEST_LOG_FILE | sed -e "s/^.*\][ ]*//g" > ./grep$UNITTEST_NUM.log

check

pass
