#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2017-2023, Intel Corporation

#
# src/test/util_poolset/TEST4 -- unit test for util_pool_open()
#

. ../unittest/unittest.sh

require_test_type medium
set_test_labels fault_injection
require_fs_type any

setup

RESVSIZE=$((4 * 1024 * 1024 * 1024)) # 4GiB
MIN_POOL=$((128 * 1024 * 1024)) # 128MiB
require_free_space $(( $MIN_POOL * 12 ))

export TEST_LOG_LEVEL=4
export TEST_LOG_FILE=./test$UNITTEST_NUM.log

# prepare pool sets
create_poolset $DIR/testset1\
	$RESVSIZE:$DIR/testdir11:d\
	O SINGLEHDR # pass
create_poolset $DIR/testset2\
	$RESVSIZE:$DIR/testdir21:d $RESVSIZE:$DIR/testdir22:d\
	O SINGLEHDR # pass
create_poolset $DIR/testset3\
	$RESVSIZE:$DIR/testdir31:d R $RESVSIZE:$DIR/testdir32:d\
	O SINGLEHDR # pass
create_poolset $DIR/testset4\
	$RESVSIZE:$DIR/testdir41:d $RESVSIZE:$DIR/testdir42:d\
	R $RESVSIZE:$DIR/testdir43:d $RESVSIZE:$DIR/testdir44:d\
	O SINGLEHDR # pass

# create pool sets
expect_normal_exit ./util_poolset$EXESUFFIX c $MIN_POOL\
	$DIR/testset1\
	$DIR/testset2\
	$DIR/testset3\
	$DIR/testset4

# now check if pool sets may be opened
expect_normal_exit ./util_poolset$EXESUFFIX o $MIN_POOL\
	$DIR/testset1\
	$DIR/testset2\
	$DIR/testset3\
	$DIR/testset4

expect_normal_exit ./util_poolset$EXESUFFIX f $MIN_POOL\
	$DIR/testset4

expect_normal_exit ./util_poolset$EXESUFFIX e $MIN_POOL\
	$DIR/testset1\
	$DIR/testset2\
	$DIR/testset3\
	$DIR/testset4

expect_normal_exit ./util_poolset$EXESUFFIX e $MIN_POOL\
	$DIR/testset1\
	$DIR/testset2\
	$DIR/testset3\
	$DIR/testset4

expect_normal_exit ./util_poolset$EXESUFFIX e $MIN_POOL\
	$DIR/testset1\
	$DIR/testset2\
	$DIR/testset3\
	$DIR/testset4

expect_normal_exit ./util_poolset$EXESUFFIX o $MIN_POOL\
	$DIR/testset1\
	$DIR/testset2\
	$DIR/testset3\
	$DIR/testset4

$GREP "<1>" $TEST_LOG_FILE | sed -e "s/^.*\][ ]*//g" > ./grep$UNITTEST_NUM.log

check

pass
