#!/usr/bin/env bash
#
# Copyright 2017-2019, Intel Corporation
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in
#       the documentation and/or other materials provided with the
#       distribution.
#
#     * Neither the name of the copyright holder nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

#
# src/test/util_poolset/TEST4 -- unit test for util_pool_open()
#

. ../unittest/unittest.sh

require_test_type medium
require_fs_type any

setup

RESVSIZE=$((4 * 1024 * 1024 * 1024)) # 4GiB
MIN_POOL=$((128 * 1024 * 1024)) # 128MiB
require_free_space $(( $MIN_POOL * 12 ))

export TEST_LOG_LEVEL=4
export TEST_LOG_FILE=./test$UNITTEST_NUM.log

# prepare pool sets
create_poolset $DIR/testset1\
	$RESVSIZE:$DIR/testdir11:d\
	O SINGLEHDR # pass
create_poolset $DIR/testset2\
	$RESVSIZE:$DIR/testdir21:d $RESVSIZE:$DIR/testdir22:d\
	O SINGLEHDR # pass
create_poolset $DIR/testset3\
	$RESVSIZE:$DIR/testdir31:d R $RESVSIZE:$DIR/testdir32:d\
	O SINGLEHDR # pass
create_poolset $DIR/testset4\
	$RESVSIZE:$DIR/testdir41:d $RESVSIZE:$DIR/testdir42:d\
	R $RESVSIZE:$DIR/testdir43:d $RESVSIZE:$DIR/testdir44:d\
	O SINGLEHDR # pass

# create pool sets
expect_normal_exit ./util_poolset$EXESUFFIX c $MIN_POOL\
	$DIR/testset1\
	$DIR/testset2\
	$DIR/testset3\
	$DIR/testset4

# now check if pool sets may be opened
expect_normal_exit ./util_poolset$EXESUFFIX o $MIN_POOL\
	$DIR/testset1\
	$DIR/testset2\
	$DIR/testset3\
	$DIR/testset4

expect_normal_exit ./util_poolset$EXESUFFIX f $MIN_POOL\
	$DIR/testset4

expect_normal_exit ./util_poolset$EXESUFFIX e $MIN_POOL\
	$DIR/testset1\
	$DIR/testset2\
	$DIR/testset3\
	$DIR/testset4

expect_normal_exit ./util_poolset$EXESUFFIX e $MIN_POOL\
	$DIR/testset1\
	$DIR/testset2\
	$DIR/testset3\
	$DIR/testset4

expect_normal_exit ./util_poolset$EXESUFFIX e $MIN_POOL\
	$DIR/testset1\
	$DIR/testset2\
	$DIR/testset3\
	$DIR/testset4

expect_normal_exit ./util_poolset$EXESUFFIX o $MIN_POOL\
	$DIR/testset1\
	$DIR/testset2\
	$DIR/testset3\
	$DIR/testset4

$GREP "<1>" $TEST_LOG_FILE | sed -e "s/^.*\][ ]*//g" > ./grep$UNITTEST_NUM.log

check

pass
