#!/usr/bin/env bash
#
# Copyright 2017-2019, Intel Corporation
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in
#       the documentation and/or other materials provided with the
#       distribution.
#
#     * Neither the name of the copyright holder nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

#
# src/test/util_poolset/TEST7 -- unit test for util_pool_open()
#
# case: negative test for local poolsets with the NOHDRS option
#

. ../unittest/unittest.sh

require_test_type medium
require_fs_type any

setup

RESVSIZE=$((4 * 1024 * 1024 * 1024)) # 4GiB
MIN_POOL=$((128 * 1024 * 1024)) # 128MiB
require_free_space $(( $MIN_POOL * 6 ))

export TEST_LOG_LEVEL=4
export TEST_LOG_FILE=./test$UNITTEST_NUM.log

# prepare pool sets

create_poolset $DIR/testset1 \
	$MIN_POOL:$DIR/testfile11:x \
	O NOHDRS

create_poolset $DIR/testset2 \
	$MIN_POOL:$DIR/testfile21:x \
	$MIN_POOL:$DIR/testfile22:x \
	O NOHDRS

create_poolset $DIR/testset3 \
	$MIN_POOL:$DIR/testfile31:x \
	r \
	$MIN_POOL:$DIR/testfile32:x \
	O NOHDRS

create_poolset $DIR/testset4\
	$RESVSIZE:$DIR/testdir41:d\
	O NOHDRS

create_poolset $DIR/testset5\
	$RESVSIZE:$DIR/testdir51:d $RESVSIZE:$DIR/testdir52:d\
	O NOHDRS

create_poolset $DIR/testset6\
	$RESVSIZE:$DIR/testdir61:d R $RESVSIZE:$DIR/testdir62:d\
	O NOHDRS

# attempt to create the pool sets

expect_normal_exit ./util_poolset$EXESUFFIX c $MIN_POOL\
	$DIR/testset1\
	$DIR/testset2\
	$DIR/testset3\
	$DIR/testset4\
	$DIR/testset5\
	$DIR/testset6

# Extract level 1 messages from the test log
$GREP "<1>" $TEST_LOG_FILE | sed -e "s/^.*\][ ]*//g" > ./grep$UNITTEST_NUM.log

check

pass
