#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2017-2019, Intel Corporation

#
# src/test/util_poolset/TEST6 -- unit test for util_pool_open()
#

. ../unittest/unittest.sh

require_test_type medium
require_fs_type any

setup

RESVSIZE=$((260 * 1024 * 1024)) # 264MiB (base part + 2 extends)
MIN_POOL=$((128 * 1024 * 1024)) # 128MiB
require_free_space $(( $MIN_POOL * 8 ))

export TEST_LOG_LEVEL=4
export TEST_LOG_FILE=./test$UNITTEST_NUM.log

# prepare pool sets
create_poolset $DIR/testset2\
	$RESVSIZE:$DIR/testdir21:d $RESVSIZE:$DIR/testfile22
create_poolset $DIR/testset3\
	$RESVSIZE:$DIR/testdir31:d R $RESVSIZE:$DIR/testfile32
create_poolset $DIR/testset4\
	$RESVSIZE:$DIR/testdir41:d $RESVSIZE:$DIR/testdir42:d\
	R $RESVSIZE:$DIR/testdir43:d $RESVSIZE:$DIR/testfile44

create_poolset $DIR/testset6\
	$RESVSIZE:$DIR/testdir61:d $RESVSIZE:$DIR/testfile62\
	O SINGLEHDR
create_poolset $DIR/testset7\
	$RESVSIZE:$DIR/testdir71:d R $RESVSIZE:$DIR/testfile72\
	O SINGLEHDR
create_poolset $DIR/testset8\
	$RESVSIZE:$DIR/testdir81:d $RESVSIZE:$DIR/testdir82:d\
	R $RESVSIZE:$DIR/testdir83:d $RESVSIZE:$DIR/testfile84\
	O SINGLEHDR

create_poolset $DIR/testset9\
	$RESVSIZE:$DIR/testdir91 $RESVSIZE:$DIR/testfile92:d\
	O SINGLEHDR

# create pool sets
expect_normal_exit ./util_poolset$EXESUFFIX c $MIN_POOL\
	$DIR/testset2\
	$DIR/testset3\
	$DIR/testset4\
	$DIR/testset6\
	$DIR/testset7\
	$DIR/testset8\
	$DIR/testset9

$GREP "<1>" $TEST_LOG_FILE | sed -e "s/^.*\][ ]*//g" > ./grep$UNITTEST_NUM.log

check

pass
