#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2017-2019, Intel Corporation

#
# src/test/util_poolset/TEST3 -- unit test for util_pool_open()
#

. $UNITTEST_SH

require_test_type medium
require_fs_type non-pmem

setup

export TEST_LOG_LEVEL=4
export TEST_LOG_FILE=./test$UNITTEST_NUM.log

MIN_POOL=$((4 * 1024 * 1024)) # 4MiB
MIN_PART=$((2 * 1024 * 1024)) # 2MiB

for i in `seq 1 128`; do
	FILES="$FILES $MIN_PART:$DIR/testfile$i:x "
done

# prepare pool sets
create_poolset $DIR/testset1 $FILES

# create pool sets
expect_normal_exit ./util_poolset$EXESUFFIX c $MIN_POOL $DIR/testset1

# now check if pool sets may be opened
expect_normal_exit ./util_poolset$EXESUFFIX o $MIN_POOL $DIR/testset1

$GREP "<1>" $TEST_LOG_FILE | sed -e "s/^.*\][ ]*//g" > ./grep$UNITTEST_NUM.log

check

pass
