# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2017, Intel Corporation

#
# src/test/pmem_memcpy/Makefile -- build pmem_memcpy unit test
#
TARGET = pmem_memcpy
OBJS = pmem_memcpy.o

LIBPMEM=y
LIBPMEMCOMMON=y

include ../Makefile.inc
