#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_tx_locks/TEST0 -- unit test for transaction locks
#

. ../unittest/unittest.sh

# this test verifies the correctness of the tx management functions only
configure_valgrind pmemcheck force-disable

require_test_type medium

setup

expect_normal_exit ./obj_tx_locks$EXESUFFIX $DIR/testfile1

pass
