# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018-2019, Intel Corporation

#
# src/test/obj_reorder_basic/Makefile -- build obj_reorder_basic
# unit test
#

TARGET = obj_reorder_basic
OBJS = obj_reorder_basic.o

LIBPMEMOBJ=y

# included for VALGRIND_EMIT_LOG
LIBPMEMCOMMON=y

include ../Makefile.inc
