# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_pmalloc_basic/Makefile -- build obj_pmalloc_basic unit test
#
TARGET = obj_pmalloc_basic
OBJS = obj_pmalloc_basic.o

LIBPMEMOBJ=internal-debug

include ../Makefile.inc
