#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_pmalloc_basic/TEST0 -- unit test for pmalloc interface
#

. $UNITTEST_SH

require_test_type medium

setup

expect_normal_exit ./obj_pmalloc_basic$EXESUFFIX

pass
