# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2016, Intel Corporation

#
# src/test/pmem_movnt/Makefile -- build pmem_movnt unit test
#
TARGET = pmem_movnt
OBJS = pmem_movnt.o

LIBPMEM=y

include ../Makefile.inc
