# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/obj_layout/Makefile -- build layout unit test
#
TARGET = obj_layout
OBJS = obj_layout.o

LIBPMEMOBJ=internal-debug

include ../Makefile.inc
