#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/obj_layout/TEST0 -- unit test for obj_layout interface
#

. ../unittest/unittest.sh

require_test_type short

setup

expect_normal_exit ./obj_layout$EXESUFFIX

pass
