
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2020, Intel Corporation

#
# src/libpmemset/Makefile -- Makefile for libpmemset
#

include ../common.inc
include ../core/pmemcore.inc

LIBRARY_NAME = pmemset
LIBRARY_SO_VERSION = 1
LIBRARY_VERSION = 0.0
SOURCE =\
	libpmemset.c

include ../Makefile.inc

CFLAGS += -I.
LIBS += -pthread
