# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018, Intel Corporation

#
# src/test/pmem_unmap/Makefile -- build pmem_unmap() unit test
#
TARGET = pmem_unmap
OBJS = pmem_unmap.o

LIBPMEM=y

include ../Makefile.inc
