#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018-2019, Intel Corporation

#
# src/test/pmem_unmap/TEST0 -- unit test for pmem_unmap
#

. ../unittest/unittest.sh

require_test_type medium

require_fs_type any

setup

create_holey_file 20M $DIR/testfile

expect_normal_exit ./pmem_unmap$EXESUFFIX $DIR/testfile

check_files $DIR/testfile

pass
