# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2023, Intel Corporation

# This playbook is designed to install all required packages and configure Rocky Linux 9 to execute tests.
# Playbook description and how to use it is available in README.md file

- hosts: "{{ host }}"
# - hosts: localhost
#   connection: local
  vars:
    testUser: pmdkuser

  tasks:

    - name: "Update kernel packages"
      package:
        name: "kernel.x86_64"
        state: latest
      register: isUpdated

    - name: "Update OS packages"
      package:
        name: "*"
        state: latest

    - name: "Reboot platform to apply updates"
      reboot:
      when: isUpdated.changed

    - name: "Add permanent pkg config variable to the system"
      env:
        state: present
        name: PKG_CONFIG_PATH
        value: /usr/local/lib64/pkgconfig:/usr/local/lib/pkgconfig

    - name: "Rocky - adding additional repositories"
      block:
        - name: "Rocky - adding epel repository"
          shell: yum install epel-release -y

        - name: "Rocky - enabling Power Tools"
          shell: dnf config-manager --enable crb

    - name: "Install VALGRIND deps"
      package:
        state: present
        name:
          - autoconf
          - automake
          - file
          - findutils
          - git

    - name: "Install PMDK base deps"
      package:
        state: present
        name:
          - cmake
          - git
          - daxctl-devel
          - make
          - ndctl-devel
          - passwd
          - pkgconfig

    - name: "Install benchmarks deps (optional)"
      package:
        state: present
        name:
          - glib2-devel

    - name: "Install examples deps (optional)"
      package:
        state: present
        name:
          - fuse
          - fuse-devel
          - ncurses-devel
          - libuv-devel

    - name: "Install documentation deps (optional)"
      package:
        state: present
        name:
          - pandoc

    - name: "Install tests deps"
      package:
        state: present
        name:
          - bc
          - gdb
          - libunwind-devel
          - ndctl
          - openssh-server
          - strace

    - name: "Install packaging deps"
      package:
        state: present
        name:
          - rpm-build
          - rpm-build-libs
          - rpmdevtools

    - name: "Install miscellaneous deps"
      package:
        state: present
        name:
          - clang
          - lbzip2
          - man
          - python3
          - python3-flake8
          - rsync
          - shadow-utils
          - sudo
          - tar
          - which
          - xmlto

    - name: "Run the install-valgrind script with arguments"
      script: ../docker/images/install-valgrind.sh rockylinux

    - name: "Add new user"
      shell: |
        #!/usr/bin/env bash
        export USER={{ testUser }}
        export USERPASS=pmdkpass
        useradd -m $USER
        echo $USERPASS | passwd $USER --stdin
        gpasswd wheel -a $USER
        echo "%wheel ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

    - name: "Set variable OS"
      env:
        state: present
        name: 'OS'
        value: 'rockylinux/rockylinux'

    - name: "Set variable OS_VER"
      env:
        state: present
        name: 'OS_VER'
        value: '9'

    - name: "Set variable PACKAGE_MANAGER"
      env:
        state: present
        name: 'PACKAGE_MANAGER'
        value: 'rpm'

    - name: "Set variable NOTTY"
      env:
        state: present
        name: 'NOTTY'
        value: '1'
