# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2020, Intel Corporation

#
# src/test/pmem2_badblock/Makefile --
#           -- build pmem2_badblock test
#

TOP = ../../..

TARGET = pmem2_badblock

OBJS += pmem2_badblock.o

LIBPMEM2=internal-debug

include ../Makefile.inc
