# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2019, Intel Corporation

#
# src/test/obj_obj_pool_mt/Makefile -- build obj_obj_pool_mt unit test
#
TARGET = obj_pool_open_mt
OBJS = obj_pool_open_mt.o

LIBPMEMOBJ=y

include ../Makefile.inc
