#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2019, Intel Corporation

#
# src/test/obj_pool_open_mt/TEST1 -- multithreaded test for pool_open
#

. ../unittest/unittest.sh

require_test_type medium
require_fs_type any
configure_valgrind helgrind force-enable

setup

expect_normal_exit ./obj_pool_open_mt$EXESUFFIX $DIR 2

pass
