#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2019, Intel Corporation

#
# src/test/obj_pool_open_mt/TEST0 -- unit test for concurrent pool opens/closes
#

. ../unittest/unittest.sh

require_test_type medium
require_fs_type any

setup

expect_normal_exit ./obj_pool_open_mt$EXESUFFIX $DIR 8

pass
