# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# Dockerfile - a 'recipe' for Docker to build an image of ubuntu-based
#              environment for building the PMDK project.
#

# Pull base image
FROM ubuntu:19.10
MAINTAINER marcin.slusarz@intel.com

ENV DEBIAN_FRONTEND noninteractive

# Update the Apt cache and install basic tools
RUN apt-get update && apt-get dist-upgrade -y

# libfabric (optional if libfabric-dev >= 1.4.2 is installed)
ENV FABRIC_DEPS "autoconf \
	automake \
	build-essential \
	libtool \
	unzip \
	wget"

ENV VALGRIND_DEPS "autoconf \
	automake \
	build-essential \
	git"

# pmdk base
ENV BASE_DEPS "build-essential \
	git \
	libdaxctl-dev \
	libndctl-dev \
	pkg-config"

# benchmarks (optional)
ENV BENCH_DEPS libglib2.0-dev

# examples (optional)
ENV EXAMPLES_DEPS "libfuse-dev \
	libncurses5-dev \
	libuv1-dev"

# documentation (optional)
ENV DOC_DEPS pandoc

# tests
ENV TESTS_DEPS "bc \
	gdb \
	libc6-dbg \
	libunwind-dev \
	ndctl \
	python3 \
	ssh \
	strace"

# packaging
ENV PACKAGING_DEPS "debhelper \
	devscripts \
	fakeroot"

# CodeCov
ENV CODECOV_DEPS curl

# Coverity
ENV COVERITY_DEPS ruby gcc g++ wget

# misc
ENV MISC_DEPS "clang \
	clang-format \
	flake8 \
	sudo \
	whois"

RUN apt-get install -y --no-install-recommends \
	$FABRIC_DEPS \
	$VALGRIND_DEPS \
	$BASE_DEPS \
	$BENCH_DEPS \
	$EXAMPLES_DEPS \
	$DOC_DEPS \
	$TESTS_DEPS \
	$PACKAGING_DEPS \
	$CODECOV_DEPS \
	$COVERITY_DEPS \
	$MISC_DEPS

# Install valgrind
COPY install-valgrind.sh install-valgrind.sh
RUN ./install-valgrind.sh

# Install libfabric
COPY install-libfabric.sh install-libfabric.sh
RUN ./install-libfabric.sh

# Add user
ENV USER pmdkuser
ENV USERPASS pmdkpass
RUN useradd -m $USER -g sudo -p `mkpasswd $USERPASS`

# remove stuff no longer needed
RUN apt remove -y \
	unzip \
	whois

RUN apt autoremove -y

RUN apt-get clean

RUN rm -rf /var/lib/apt/lists/*

# switch user
USER $USER

# Set required environment variables
ENV OS ubuntu
ENV OS_VER 19.10
ENV START_SSH_COMMAND service ssh start
ENV PACKAGE_MANAGER dpkg
ENV NOTTY 1
