#
# Copyright 2016-2019, Intel Corporation
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in
#       the documentation and/or other materials provided with the
#       distribution.
#
#     * Neither the name of the copyright holder nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#
# Dockerfile - a 'recipe' for Docker to build an image of ubuntu-based
#              environment for building the PMDK project.
#

# Pull base image
FROM ubuntu:18.04
MAINTAINER marcin.slusarz@intel.com

ENV DEBIAN_FRONTEND noninteractive

# Update the Apt cache and install basic tools
RUN apt-get update && apt-get dist-upgrade -y

# ndctl (optional if libndctl-dev and libdaxctl-dev >= 60.1, 64.1 preferred)
ENV NDCTL_DEPS "asciidoctor \
	automake \
	bash-completion \
	build-essential \
	git \
	libjson-c-dev \
	libkeyutils-dev \
	libkmod-dev \
	libtool \
	libudev-dev \
	pkg-config \
	systemd \
	uuid-dev"

# libfabric (optional if libfabric-dev >= 1.4.2 is installed)
ENV FABRIC_DEPS "autoconf \
	automake \
	build-essential \
	libtool \
	unzip \
	wget"

ENV VALGRIND_DEPS "autoconf \
	automake \
	build-essential \
	git"

# pmdk base
ENV BASE_DEPS "build-essential \
	git \
	pkg-config"

# jemalloc
ENV JEMALLOC_DEPS autoconf

# benchmarks (optional)
ENV BENCH_DEPS libglib2.0-dev

# examples (optional)
ENV EXAMPLES_DEPS "libfuse-dev \
	libncurses5-dev \
	libuv1-dev"

# documentation (optional)
ENV DOC_DEPS pandoc

# tests
ENV TESTS_DEPS "bc \
	libc6-dbg \
	libunwind-dev \
	python3 \
	ssh \
	strace"

# packaging
ENV PACKAGING_DEPS "debhelper \
	devscripts \
	fakeroot"

# CodeCov
ENV CODECOV_DEPS curl

# Coverity
ENV COVERITY_DEPS ruby gcc-6 g++-6 wget

# misc
ENV MISC_DEPS "clang \
	clang-format \
	flake8 \
	sudo \
	whois"

RUN apt-get install -y --no-install-recommends \
	$NDCTL_DEPS \
	$FABRIC_DEPS \
	$VALGRIND_DEPS \
	$BASE_DEPS \
	$JEMALLOC_DEPS \
	$BENCH_DEPS \
	$EXAMPLES_DEPS \
	$DOC_DEPS \
	$TESTS_DEPS \
	$PACKAGING_DEPS \
	$CODECOV_DEPS \
	$COVERITY_DEPS \
	$MISC_DEPS

# Install valgrind
COPY install-valgrind.sh install-valgrind.sh
RUN ./install-valgrind.sh

# Add user
ENV USER pmdkuser
ENV USERPASS pmdkpass
RUN useradd -m $USER -g sudo -p `mkpasswd $USERPASS`

# remove stuff no longer needed
RUN apt remove -y \
	libjson-c-dev \
	libkeyutils-dev \
	libkmod-dev \
	libudev-dev \
	uuid-dev \
	unzip \
	whois

RUN apt autoremove -y

RUN apt-get clean

RUN rm -rf /var/lib/apt/lists/*

# switch user
USER $USER

# Set required environment variables
ENV OS ubuntu
ENV OS_VER 18.04
ENV START_SSH_COMMAND service ssh start
ENV PACKAGE_MANAGER dpkg
ENV NOTTY 1
