#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/rpmemd_dbg/TEST0 -- unit test for rpmemd_log module
#
#

. $UNITTEST_SH

require_test_type medium
require_build_type debug
require_fs_type none

setup

rm -f	stderr$UNITTEST_NUM.log\
	logfile$UNITTEST_NUM.log\
	syslog$UNITTEST_NUM.log

expect_normal_exit ./rpmemd_dbg\
	log stderr stderr$UNITTEST_NUM.log

expect_normal_exit ./rpmemd_dbg\
	log file logfile$UNITTEST_NUM.log

expect_normal_exit ./rpmemd_dbg\
	log syslog syslog$UNITTEST_NUM.log

check

pass
