# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2021, Intel Corporation

#
# examples/libpmemset/log/Makefile -- build the log example
#
PROGS = log

LIBS = -lpmem2 -lpmemset

include ../../Makefile.inc

log: log.o
