#!/bin/bash -e
#
# Copyright (c) 2014, Intel Corporation
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in
#       the documentation and/or other materials provided with the
#       distribution.
#
#     * Neither the name of Intel Corporation nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

#
# src/test/util_pool_open/TEST0 -- unit test for util_pool_open()
#
export UNITTEST_NAME=util_pool_open/TEST0
export UNITTEST_NUM=0

# standard unit test setup
. ../unittest/unittest.sh

require_fs_type local

setup

MIN_POOL=0x4000

rm -f $DIR/testfile1
rm -f $DIR/testfile2
rm -f $DIR/testfile3
rm -f $DIR/testfile4
rm -f $DIR/testlink1
rm -f $DIR/testlink2
rm -f $DIR/testlink3
rm -f $DIR/testlink4
rm -f $DIR/testlink5
rm -fr $DIR/testdir1

truncate -s 32K $DIR/testfile1
chmod -rw $DIR/testfile1
truncate -s 32K $DIR/testfile2
chmod -w $DIR/testfile2
truncate -s 1K $DIR/testfile3
truncate -s 32K $DIR/testfile4
mkdir $DIR/testdir1
ln -s $DIR/testfile0 $DIR/testlink1
ln -s $DIR/testfile1 $DIR/testlink2
ln -s $DIR/testfile2 $DIR/testlink3
ln -s $DIR/testdir1 $DIR/testlink4
ln -s /dev/zero $DIR/testlink5

expect_normal_exit ./util_pool_open$EXESUFFIX $MIN_POOL \
    $DIR/testdir1\
    /dev/zero\
    $DIR/testlink1\
    $DIR/testlink2\
    $DIR/testlink3\
    $DIR/testlink4\
    $DIR/testlink5\
    $DIR/testfile0\
    $DIR/testfile1\
    $DIR/testfile2\
    $DIR/testfile3\
    $DIR/testfile4

rm -f $DIR/testfile[1234]
rm -f $DIR/testlink[12345]
rmdir $DIR/testdir1

check

pass
