#!/usr/bin/env bash
#
# Copyright 2017, Intel Corporation
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in
#       the documentation and/or other materials provided with the
#       distribution.
#
#     * Neither the name of the copyright holder nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

#
# src/test/ex_libpmemcto/TEST1 -- unit test for libpmemcto examples
#
export UNITTEST_NAME=ex_libpmemcto/TEST1
export UNITTEST_NUM=1

# standard unit test setup
. ../unittest/unittest.sh

require_test_type medium
require_build_type debug nondebug
require_fs_type any

setup

TEST_LD_LIBRARY_PATH=$TEST_LD_LIBRARY_PATH:../../examples/libpmemcto/libart
EX_PATH=../../examples/libpmemcto/libart

cat > $DIR/data << EOF
key1
Hello world!
key2
1234567890
key3
NVML
key4
PMEM
EOF

expect_normal_exit $EX_PATH/arttree -m i $DIR/testfile1 > out$UNITTEST_NUM.log << EOF
fill -n 4 $DIR/data
dump
quit
EOF

expect_normal_exit $EX_PATH/arttree -m i $DIR/testfile1 >> out$UNITTEST_NUM.log << EOF
graph
quit
EOF

check

pass
