# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/libpmempool_transform/Makefile -- build libpmempool transform test
#
TARGET = libpmempool_transform
OBJS = libpmempool_transform.o

LIBPMEMPOOL=y
USE_PMEMOBJCLI=y

include ../Makefile.inc
