# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2019, Intel Corporation

#
# src/test/obj_alloc/Makefile -- build obj_alloc unit test
#
TARGET = obj_alloc
OBJS = obj_alloc.o

LIBPMEMOBJ=internal-debug

include ../Makefile.inc
