# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/obj_tx_mt/Makefile -- build obj_tx_mt unit test
#
TARGET = obj_tx_mt
OBJS = obj_tx_mt.o

LIBPMEMOBJ=y

include ../Makefile.inc
