# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/libpmempool_api/Makefile -- build libpmempool_api unittest
#

TARGET = libpmempool_test
OBJS = libpmempool_test.o

LIBPMEMPOOL=y
USE_PMEMSPOIL=y
USE_PMEMWRITE=y
USE_BTTCREATE=y

include ../Makefile.inc
