#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2017-2018, Intel Corporation
#
#
# rpmemd_util/TEST0 -- test rpmemd_apply_pm_policy function - valid cases
#

. ../unittest/unittest.sh

require_test_type medium

require_fs_type any

setup

OUT=stdout${UNITTEST_NUM}.log

expect_normal_exit ./rpmemd_util$EXESUFFIX valid &> $OUT

check

pass
