#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2017-2018, Intel Corporation
#
#
# rpmemd_util/TEST1 -- test rpmemd_apply_pm_policy function - invalid case
#

. $UNITTEST_SH

require_test_type medium

require_fs_type any

setup

OUT=stdout${UNITTEST_NUM}.log

expect_abnormal_exit ./rpmemd_util$EXESUFFIX invalid &> $OUT

check

pass
