# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2014-2019, Intel Corporation

#
# src/test/blk_rw/Makefile -- build blk_rw unit test
#
TARGET = blk_rw
OBJS = blk_rw.o

LIBPMEMBLK=y

include ../Makefile.inc
