#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2017-2019, Intel Corporation

#
# src/test/blk_rw/TEST11 -- unit test for pmemblk_read/write/set_zero/set_error
#
# Same as TEST10, but run on a pool set that spans two Device DAX devices
# with 4K alignment.
#

. ../unittest/unittest.sh

require_test_type medium
require_fs_type any
require_dax_device_alignments 4096 4096

setup

dax_device_zero

create_poolset $DIR/testset AUTO:${DEVICE_DAX_PATH[0]} AUTO:${DEVICE_DAX_PATH[1]}

expect_normal_exit ./blk_rw$EXESUFFIX 512 $DIR/testset c\
	r:0 r:1 r:32201 r:32313 z:0 z:1 r:0

check_pool DIR/testset

pass
