#!/usr/bin/env bash
#
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation
# Copyright 2019, IBM Corporation

#
# src/test/blk_rw/TEST22 -- unit test for pmemblk_read/write/set_zero/set_error
#
# This test is equivalent of TEST8 for ppc64le platform.
#

. $UNITTEST_SH

require_test_type medium
require_ppc64

# doesn't make sense to run in local directory
require_fs_type pmem non-pmem

setup

require_free_space 2G

create_poolset $DIR/testset1 1G:$DIR/testfile1:x 1G:$DIR/testfile2:x

expect_normal_exit ./blk_rw$EXESUFFIX 512 $DIR/testset1 c\
	w:0 w:1 r:1 r:0\
	w:4161096 r:4161096

check_pool $DIR/testfile2

check

pass
