#!/usr/bin/env bash
#
# Copyright 2015-2019, Intel Corporation
# Copyright 2019, IBM Corporation
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in
#       the documentation and/or other materials provided with the
#       distribution.
#
#     * Neither the name of the copyright holder nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

#
# src/test/blk_rw/TEST21 -- unit test for pmemblk_read/write/set_zero/set_error
#
# This test is equivalent of TEST7 for ppc64le platform.
#

. ../unittest/unittest.sh

# long test, run only on pmem
require_ppc64
require_fs_type pmem
require_test_type long
configure_valgrind pmemcheck force-enable
setup

# mix writes with set_zero and set_error and check results
truncate -s 128M $DIR/testfile1

expect_normal_exit ./blk_rw$EXESUFFIX 512 $DIR/testfile1 c\
		e:1 r:1\
		e:2 w:2 r:2\
		z:3 e:3 r:3\
		e:4 z:4 r:4\
		w:5 e:5 z:5 r:5\
		w:6 z:6 e:6 r:6

check_pool $DIR/testfile1

check

pass
