#!/usr/bin/env bash
#
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2014-2019, Intel Corporation
# Copyright 2019, IBM Corporation

#
# src/test/blk_rw/TEST19 -- unit test for pmemblk_read/write/set_zero/set_error
#
# This test is equivalent of TEST5 for ppc64le platform.
#

. $UNITTEST_SH

require_test_type medium
require_ppc64

# doesn't make sense to run in local directory
require_fs_type pmem non-pmem

setup

# mix writes with set_zero and set_error and check results
truncate -s 1G $DIR/testfile1
expect_normal_exit ./blk_rw$EXESUFFIX 512 $DIR/testfile1 c\
	w:100 w:200 w:300 w:400\
	r:100 r:200 r:300 r:400\
	w:100 z:200 w:300 z:400\
	r:100 r:200 r:300 r:400\
	e:100 w:200 e:300 w:400\
	r:100 r:200 r:300 r:400

check_pool $DIR/testfile1

check

pass
