#!/usr/bin/env bash
#
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation
# Copyright 2019, IBM Corporation

#
# src/test/blk_rw/TEST21 -- unit test for pmemblk_read/write/set_zero/set_error
#
# This test is equivalent of TEST7 for ppc64le platform.
#

. ../unittest/unittest.sh

# long test, run only on pmem
require_ppc64
require_fs_type pmem
require_test_type long
configure_valgrind pmemcheck force-enable
setup

# mix writes with set_zero and set_error and check results
truncate -s 128M $DIR/testfile1

expect_normal_exit ./blk_rw$EXESUFFIX 512 $DIR/testfile1 c\
		e:1 r:1\
		e:2 w:2 r:2\
		z:3 e:3 r:3\
		e:4 z:4 r:4\
		w:5 e:5 z:5 r:5\
		w:6 z:6 e:6 r:6

check_pool $DIR/testfile1

check

pass
