#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/blk_rw/TEST10 -- unit test for pmemblk_read/write/set_zero/set_error
#
# Same as TEST0, but run on a single Device DAX device.
#

. ../unittest/unittest.sh

require_test_type medium
require_fs_type any
require_dax_devices 1

setup

dax_device_zero

expect_normal_exit ./blk_rw$EXESUFFIX 512 $DEVICE_DAX_PATH c\
	r:0 r:1 r:32201 r:32313 z:0 z:1 r:0

check_pool $DEVICE_DAX_PATH

pass
