#!/usr/bin/env bash
#
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2014-2019, Intel Corporation
# Copyright (c) 2016, Microsoft Corporation. All rights reserved.
# Copyright 2019, IBM Corporation

#
# src/test/blk_rw/TEST14 -- unit test for pmemblk_read/write/set_zero/set_error
#
# This test is equivalent of TEST0 for ppc64le platform.
#

. ../unittest/unittest.sh

require_test_type medium
require_ppc64

# doesn't make sense to run in local directory
require_fs_type pmem non-pmem

setup

# single arena and minimum pmemblk pool file case
MIN_POOL_SIZE=$((16*1024*1024 + 128*1024))
truncate -s $MIN_POOL_SIZE $DIR/testfile1
#
# All reads to an unwritten block pool should return zeros.
# Block 32313 is out of range and should return EINVAL.
# Attempts to zero uninitialized blocks are nops (should succeed).
#
expect_normal_exit ./blk_rw$EXESUFFIX 512 $DIR/testfile1 c\
	r:0 r:1 r:32201 r:32313 z:0 z:1 r:0

check_pool $DIR/testfile1

check

pass
