#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2014-2019, Intel Corporation

#
# src/test/blk_rw/TEST6 -- unit test for pmemblk_read/write/set_zero/set_error
#

. ../unittest/unittest.sh

require_test_type medium
exclude_ppc64

# doesn't make sense to run in local directory
require_fs_type pmem non-pmem

setup

# mix writes with set_zero and set_error and check results
truncate -s 1G $DIR/testfile1
expect_normal_exit ./blk_rw$EXESUFFIX 512 $DIR/testfile1 c\
		e:1 r:1\
		e:2 w:2 r:2\
		z:3 e:3 r:3\
		e:4 z:4 r:4\
		w:5 e:5 z:5 r:5\
		w:6 z:6 e:6 r:6

check_pool $DIR/testfile1

check

pass
