# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_tx_free/Makefile -- build obj_tx_free unit test
#
TARGET = obj_tx_free
OBJS = obj_tx_free.o

LIBPMEMCOMMON=y
LIBPMEMOBJ=y

include ../Makefile.inc
