#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_tx_free/TEST0 -- unit test for pmemobj_tx_free
#

. $UNITTEST_SH

require_test_type medium

setup

expect_normal_exit ./obj_tx_free$EXESUFFIX $DIR/testfile1

check

pass
