# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/util_is_poolset/Makefile -- build util_is_poolset unit test
#
#
TARGET = util_is_poolset
OBJS = util_is_poolset.o

LIBPMEMCOMMON=y

include ../Makefile.inc
