# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2024, Intel Corporation

#
# src/test/log_errno/Makefile -- build unit test for log_errno
#
TARGET = log_errno
OBJS = log_errno.o

BUILD_STATIC_DEBUG=n
BUILD_STATIC_NONDEBUG=n

include ../Makefile.inc
