# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2023, Intel Corporation

#
# src/test/set_funcs/Makefile -- build set_funcs unit test
#
TARGET = set_funcs
OBJS = set_funcs.o

LIBPMEM=y
LIBPMEMOBJ=y

include ../Makefile.inc
