# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/util_poolset_foreach/Makefile -- build util_poolset_foreach test
#
#
TARGET = util_poolset_foreach
OBJS = util_poolset_foreach.o

LIBPMEMCOMMON=y

include ../Makefile.inc
