#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/util_poolset_foreach/TEST1 -- unit test for util_poolset_foreach
#

. ../unittest/unittest.sh

require_test_type medium

require_fs_type any

setup

create_poolset $DIR/pool.set1 32K:$DIR/testfile:x\
	M remote_node1:remote_pool.set1
create_poolset $DIR/pool.set2 32K:$DIR/testfile1:x 32M:$DIR/testfile2:x\
	M remote_node2:remote_pool.set2
create_poolset $DIR/pool.set3\
	32M:$DIR/testfile11:x 32M:$DIR/testfile12:x\
	R 64M:$DIR/testfile21:x 32M:$DIR/testfile22:x\
	M remote_node3:remote_pool.set3
create_poolset $DIR/pool.set4\
	32M:$DIR/testfile11:x 32M:$DIR/testfile12:x\
	R 64M:$DIR/testfile21:x 32M:$DIR/testfile22:x\
	R 64M:$DIR/testfile31:x 64M:$DIR/testfile32:x\
	M remote_node4:remote_pool.set4

expect_normal_exit ./util_poolset_foreach$EXESUFFIX\
	$DIR/pool.set1\
	$DIR/pool.set2\
	$DIR/pool.set3\
	$DIR/pool.set4

check

pass
