# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2019, Intel Corporation
#

#
# src/test/obj_defrag/Makefile -- build obj_defrag unit test
#
TARGET = obj_defrag
OBJS = obj_defrag.o

LIBPMEMOBJ=internal-debug

include ../Makefile.inc
