# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018-2019, Intel Corporation

#
# src/test/obj_ctl_alignment/Makefile -- build obj_ctl_alignment test
#
TARGET = obj_ctl_alignment
OBJS = obj_ctl_alignment.o

LIBPMEMOBJ=y

include ../Makefile.inc
