#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018-2019, Intel Corporation

. $UNITTEST_SH

require_test_type short
require_fs_type any

setup

expect_normal_exit ./obj_ctl_alignment$EXESUFFIX $DIR/testfile

pass
