# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2014-2019, Intel Corporation

#
# src/test/blk_rw_mt/Makefile -- build blk_rw_mt unit test
#
TARGET = blk_rw_mt
OBJS = blk_rw_mt.o

LIBPMEMBLK=y

include ../Makefile.inc
