#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2014-2019, Intel Corporation

#
# src/test/blk_rw_mt/TEST1 -- unit test for MT I/O on blk pool
#

. $UNITTEST_SH

require_test_type medium

# doesn't make sense to run in local directory
require_fs_type pmem non-pmem

# libpmemblk does not support race detection tools
configure_valgrind helgrind force-disable
configure_valgrind drd force-disable

setup

truncate -s 1G $DIR/testfile1
# 100 threads, each doing 100 random I/Os
expect_normal_exit ./blk_rw_mt$EXESUFFIX 4096 $DIR/testfile1 456 100 100

check_pool $DIR/testfile1

check

pass
