# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2020, Intel Corporation

#
# src/test/pmemset_include/Makefile -- compilation test for libpmemset
#
TARGET = pmemset_include
OBJS = pmemset_include.o

LIBPMEMSET=y

include ../Makefile.inc
