# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2023, Intel Corporation

#
# src/test/obj_reserve_mt/Makefile -- build obj_reserve_mt unit test
#
TARGET = obj_reserve_mt
OBJS = obj_reserve_mt.o

LIBPMEMOBJ=internal-debug

include ../Makefile.inc
