# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/util_ctl/Makefile -- build util_ctl test
#
TARGET = util_ctl
OBJS = util_ctl.o

LIBPMEMCOMMON=y

include ../Makefile.inc
