#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

. $UNITTEST_SH

require_test_type medium

configure_valgrind memcheck force-enable

setup

expect_normal_exit\
	./util_ctl$EXESUFFIX $DIR/testconfig

pass
