#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

. ../unittest/unittest.sh

require_test_type short

setup

expect_normal_exit\
	./util_ctl$EXESUFFIX $DIR/testconfig

pass
