name: PMEM host update
description: PMDK update host kernel and OS packages

runs:
  using: composite
  steps:
    # Note: Core libraries or services such as kernel and several OS packages
    # requires a reboot in order to be fully-utilized.
    # for RHEL see: https://access.redhat.com/solutions/27943
    # for SUSE see: https://www.suse.com/support/kb/doc/?id=000020544
    #
    # Update-os playbook checks needs-restarting -r command status after packages update
    # to determine if platform reboot is required and triggers it immediately. This will fail
    # currently running workflow job due to runner service restart.
    - name: Run ansible update-os playbook (platform reboot may be performed)
      working-directory: utils/ansible
      run: |
        ansible-playbook ./update-os.yml
      shell: bash
