# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2017, Intel Corporation

#
# src/test/pmem_memset/Makefile -- build pmem_memset unit test
#
TARGET = pmem_memset
OBJS = pmem_memset.o

LIBPMEM=y
LIBPMEMCOMMON=y

include ../Makefile.inc
