# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018-2019, Intel Corporation

#
# src/test/obj_memops/Makefile -- build obj_memops test
#
TARGET = obj_memops
OBJS = obj_memops.o

LIBPMEMOBJ=internal-debug

include ../Makefile.inc
