#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/rpmem_addr/TEST0 -- unit test for rpmem_addr  module
#
#

. $UNITTEST_SH

require_test_type medium

require_fs_type none
require_build_type debug

setup

expect_normal_exit ./rpmem_addr\
	host\
	user@host\
	user@host:1234\
	127.0.0.1\
	user@127.0.0.1\
	user@127.0.0.1:1234\
	::1\
	user@::1\
	"user@\[::1\]:1234"

check

pass
