# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2020, Intel Corporation

#
# examples/libpmem2/map_multiple_files/Makefile -- build virtual address
#                                                  allocation example
#
PROGS = map_multiple_files

LIBS = -lpmem2

include ../../Makefile.inc

map_multiple_files: map_multiple_files.o
