# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_pool_lock/Makefile -- build obj_pool_lock unit test
#
TARGET = obj_pool_lock
OBJS = obj_pool_lock.o

LIBPMEMOBJ=y

include ../Makefile.inc
