#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_pool_lock/TEST0 -- unit test for pmemobj_open
#

. $UNITTEST_SH

require_test_type medium
require_no_superuser

setup

expect_normal_exit ./obj_pool_lock$EXESUFFIX $DIR/testfile

pass
