# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018-2019, Intel Corporation

#
# src/test/obj_memcheck_register/Makefile -- build obj_memcheck_register test
#
TARGET = obj_memcheck_register
OBJS = obj_memcheck_register.o

LIBPMEMOBJ=y

include ../Makefile.inc

