# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2019, Intel Corporation

#
# src/test/pmem_map_file_trunc/Makefile -- build pmem_map_file() truncation test
#
TARGET = pmem_map_file_trunc
OBJS = pmem_map_file_trunc.o

LIBPMEM=y

include ../Makefile.inc
