# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018-2019, Intel Corporation

#
# src/test/libpmempool_feature/Makefile -- build libpmempool_feature unittest
#

TARGET = libpmempool_feature
OBJS = libpmempool_feature.o

LIBPMEMPOOL=y
LIBPMEMCOMMON=y

include ../Makefile.inc
