# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2014-2016, Intel Corporation

#
# examples/libpmemlog/Makefile -- build the libpmemlog examples
#
PROGS = manpage
DIRS = logfile

LIBS = -lpmemlog -lpmem -pthread

include ../Makefile.inc

manpage: manpage.o
