# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_out_of_memory/Makefile -- build obj_out_of_memory test
#
TARGET = obj_out_of_memory
OBJS = obj_out_of_memory.o

LIBPMEMOBJ=y

include ../Makefile.inc
