# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2017, Intel Corporation

#
# src/test/arch_flags/Makefile -- build arch_flags unit test
#
TARGET = arch_flags
OBJS = arch_flags.o

LIBPMEMCOMMON=y
include ../Makefile.inc
