#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/getopt/TEST1 -- unit test for windows getopt implementation
#

. $UNITTEST_SH

require_test_type medium
require_fs_type none

ERR=stderr${UNITTEST_NUM}.log

setup

expect_normal_exit ./getopt$EXESUFFIX -Z --arg_Z -A 2>$ERR

check

pass
