# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2020, Intel Corporation

#
# examples/libpmem2/basic/Makefile -- build the unsafe_shutdowns example
#
PROGS = unsafe_shutdowns

LIBS = -lpmem2

include ../../Makefile.inc

unsafe_shutdowns: unsafe_shutdowns.o
