#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_persist_count/TEST1 -- unit test for persist count
#

. $UNITTEST_SH

require_test_type medium

require_fs_type pmem
require_build_type debug nondebug
exclude_ppc64

# Pmemcheck would complain about making a store without adding to transaction
# in this test. As the test counts the exact number of pmem_persist calls for
# sheer transactions, pmemcheck is disabled.
configure_valgrind pmemcheck force-disable

setup

expect_normal_exit ./obj_persist_count$EXESUFFIX $DIR/testfile

check

pass
