# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_tx_strdup/Makefile -- build obj_tx_strdup unit test
#
TARGET = obj_tx_strdup
OBJS = obj_tx_strdup.o

LIBPMEMOBJ=y

include ../Makefile.inc
