#!/usr/bin/env bash
#
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2017-2019, Intel Corporation
# Copyright 2019, IBM Corporation

#
# src/test/blk_pool/TEST39 -- unit test for pmemblk_create with unicode
#
# This test is equivalent of TEST17 for ppc64le platform
#

. $UNITTEST_SH

require_test_type medium
require_ppc64

setup
umask 0

#
# TEST39 non-existing file, poolsize > 0
#

expect_normal_exit ./blk_pool$EXESUFFIX c $DIR/ㅹestㆅile 4096 20 0600

check_files $DIR/ㅹestㆅile

check

pass
