#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/blk_pool/TEST29 -- unit test for pmemblk_open
#

. $UNITTEST_SH

require_test_type medium

setup
umask 0

#
# TEST29 existing file, file size >= min required size, bsize == 300
#        (pool set)
#
create_poolset $DIR/testset 20M:$DIR/testfile1 20M:$DIR/testfile2

expect_normal_exit ./blk_pool$EXESUFFIX c $DIR/testset 300 0 0640

expect_normal_exit ./blk_pool$EXESUFFIX o $DIR/testset 300

check

pass
