#!/usr/bin/env bash
#
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation
# Copyright (c) 2016, Microsoft Corporation. All rights reserved.
# Copyright 2019, IBM Corporation

#
# src/test/blk_pool/TEST36 -- unit test for pmemblk_create
#
# This test is equivalent of TEST8 for ppc64le platform
#

. ../unittest/unittest.sh

require_test_type medium
require_ppc64

setup
umask 0

create_nonzeroed_file 17M 8K $DIR/testfile
chmod 0600 $DIR/testfile

#
# TEST36 existing file, file length >= min required size, poolsize == 0
#       (file contains garbage, except for header)
#
expect_normal_exit ./blk_pool$EXESUFFIX c $DIR/testfile 4096 0 0600

check_files $DIR/testfile

check

pass
