#!/usr/bin/env bash
#
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation
# Copyright (c) 2016, Microsoft Corporation. All rights reserved.
# Copyright 2019, IBM Corporation

#
# src/test/blk_pool/TEST35 -- unit test for pmemblk_create
#
# This test is equivalent of TEST1 for ppc64le platform
#

. ../unittest/unittest.sh

require_test_type medium
require_ppc64

setup
umask 0

create_holey_file 40M $DIR/testfile
chmod 0600 $DIR/testfile

#
# TEST35 existing file, file length >= min required size, poolsize == 0
#
expect_normal_exit ./blk_pool$EXESUFFIX c $DIR/testfile 4096 0 0600

check_files $DIR/testfile

check

pass
