#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2017-2019, Intel Corporation

#
# src/test/blk_pool/TEST31 -- unit test for pmemblk_open with unicode
#

. ../unittest/unittest.sh

require_test_type medium

setup
umask 0

#
# TEST31 existing file, file size >= min required size, layout matches
#
expect_normal_exit ./blk_pool$EXESUFFIX c $DIR/ㅹestㆅile 4096 20 0640

expect_normal_exit ./blk_pool$EXESUFFIX o $DIR/ㅹestㆅile 4096

check

pass
