#!/usr/bin/env bash
#
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation
# Copyright 2019, IBM Corporation

#
# src/test/blk_pool/TEST37 -- unit test for pmemblk_create
#
# This test is equivalent of TEST13 for ppc64le platform
#

. $UNITTEST_SH

require_test_type medium
require_ppc64

setup
umask 0

#
# TEST37 non-existing file, poolsize >= min required size, bsize < min bsize
#
expect_normal_exit ./blk_pool$EXESUFFIX c $DIR/testfile 10 20 0600

check_files $DIR/testfile

check

pass
