#!/usr/bin/env bash
#
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation
# Copyright 2019, IBM Corporation

#
# src/test/blk_pool/TEST34 -- unit test for pmemblk_create
#
# This test is equivalent of TEST0 for ppc64le platform.
#

. ../unittest/unittest.sh

require_test_type medium
require_ppc64

setup
umask 0

#
# TEST34 non-existing file, poolsize > 0
#
expect_normal_exit ./blk_pool$EXESUFFIX f $DIR/testfile 4096 20 0600

expect_normal_exit ./blk_pool$EXESUFFIX c $DIR/testfile 4096 20 0600

check_files $DIR/testfile

check

pass
