#!/usr/bin/env bash
#
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation
# Copyright 2019, IBM Corporation

#
# src/test/blk_pool/TEST38 -- unit test for pmemblk_create
#
# This test is equivalent of TEST15 for ppc64le platform.
#

. ../unittest/unittest.sh

require_test_type medium
require_ppc64

setup
umask 0

#
# TEST38 non-existing file, poolsize >= min required size, bsize > min bsize
#        (pool set)
#
create_poolset $DIR/testset 20M:$DIR/testfile1:x 20M:$DIR/testfile2:x

expect_normal_exit ./blk_pool$EXESUFFIX c $DIR/testset 100 0 0640

check_files $DIR/testset $DIR/testfile1 $DIR/testfile2

check

pass
