#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/blk_pool/TEST6 -- unit test for pmemblk_create
#

. ../unittest/unittest.sh

require_test_type medium

setup
umask 0

touch $DIR/testfile
chmod 0640 $DIR/testfile

#
# TEST6 existing file, file length < min required size, poolsize == 0,
#       bsize == 0
#
expect_normal_exit ./blk_pool$EXESUFFIX c $DIR/testfile 0 0 0640

check_files $DIR/testfile

check

pass
