#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2017-2019, Intel Corporation

#
# src/test/blk_pool/TEST32 -- unit test for blk poolsets with unicode
#

. $UNITTEST_SH

require_test_type medium
require_fs_type non-pmem

setup
umask 0

expect_normal_exit ./blk_pool$EXESUFFIX c $DIR/testfile⮸ 300 20 0640

cp $DIR/testfile⮸ $DIR/testfileⰊ

create_poolset $DIR/testsetㅓㅹ 20M:$DIR/testfile⮸ R 20M:$DIR/testfileⰊ

expect_normal_exit ./blk_pool$EXESUFFIX o $DIR/testsetㅓㅹ 300

check

pass
