#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2017-2019, Intel Corporation

#
# src/test/blk_pool/TEST17 -- unit test for pmemblk_create with unicode
#

. ../unittest/unittest.sh

require_test_type medium
exclude_ppc64

setup
umask 0

#
# TEST0 non-existing file, poolsize > 0
#

expect_normal_exit ./blk_pool$EXESUFFIX c $DIR/ㅹestㆅile 4096 20 0600

check_files $DIR/ㅹestㆅile

check

pass
