#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/blk_pool/TEST15 -- unit test for pmemblk_create
#

. $UNITTEST_SH

require_test_type medium
exclude_ppc64

setup
umask 0

#
# TEST15 non-existing file, poolsize >= min required size, bsize > min bsize
#        (pool set)
#
create_poolset $DIR/testset 20M:$DIR/testfile1:x 20M:$DIR/testfile2:x

expect_normal_exit ./blk_pool$EXESUFFIX c $DIR/testset 100 0 0640

check_files $DIR/testset $DIR/testfile1 $DIR/testfile2

check

pass
