#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/blk_pool/TEST13 -- unit test for pmemblk_create
#

. ../unittest/unittest.sh

require_test_type medium
exclude_ppc64

setup
umask 0

#
# TEST13 non-existing file, poolsize >= min required size, bsize < min bsize
#
expect_normal_exit ./blk_pool$EXESUFFIX c $DIR/testfile 10 20 0600

check_files $DIR/testfile

check

pass
