#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/blk_pool/TEST16 -- unit test for pmemblk_create
#

. ../unittest/unittest.sh

require_test_type medium

setup
umask 0

#
# TEST16 non-existing file, poolsize >= min required size, bsize > min bsize
#        (pool set with replica section)
#
create_poolset $DIR/testset 20M:$DIR/testfile1:x R 20M:$DIR/testfile2:x

expect_normal_exit ./blk_pool$EXESUFFIX c $DIR/testset 100 0 0600

check_files $DIR/testset
check_no_files $DIR/testfile1 $DIR/testfile2

check

pass
