#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/blk_pool/TEST28 -- unit test for pmemblk_open
#

. $UNITTEST_SH

require_test_type medium

setup
umask 0

#
# TEST28 existing file, file size >= min required size, bsize == 300
#
expect_normal_exit ./blk_pool$EXESUFFIX c $DIR/testfile 300 20 0640

expect_normal_exit ./blk_pool$EXESUFFIX o $DIR/testfile 300

check

pass
