#!/usr/bin/env bash
#
# Copyright 2017-2019, Intel Corporation
# Copyright 2019, IBM Corporation
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in
#       the documentation and/or other materials provided with the
#       distribution.
#
#     * Neither the name of the copyright holder nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

#
# src/test/blk_pool/TEST40 -- create a pool with the smallest parts
# possible
#
# This test is equivalent of TEST33 for ppc64le platform.
#

. ../unittest/unittest.sh

require_test_type medium
require_ppc64

setup
umask 0

#
# TEST40 non-existing file, poolsize >= min required size, bsize > min bsize
#        part size == min part size (pool set)
#
CMD="$DIR/testset"
MIN_PART=$((2 * 1024 * 1024)) # 2MiB
for i in {1..9}; do
	CMD="$CMD $MIN_PART:$DIR/testfile$i:x"
done
create_poolset $CMD

expect_normal_exit ./blk_pool$EXESUFFIX c $DIR/testset 100 0 0640

check_files $DIR/testset $DIR/testfile1 $DIR/testfile2 $DIR/testfile3 \
    $DIR/testfile4 $DIR/testfile5 $DIR/testfile6 $DIR/testfile7 $DIR/testfile8 \
    $DIR/testfile9

check

pass
