#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/blk_pool/TEST20 -- unit test for pmemblk_open
#

. ../unittest/unittest.sh

require_test_type medium

setup
umask 0

#
# TEST20 non-existing file, bsize == 0
#
expect_normal_exit ./blk_pool$EXESUFFIX o $DIR/testfile 0

check

pass
