#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2014-2018, Intel Corporation
#
#
# pmempool_help/TEST0 -- test for pmempool help
#

. $UNITTEST_SH

require_test_type medium

require_fs_type pmem non-pmem

setup

LOG=out${UNITTEST_NUM}.log
rm -f $LOG && touch $LOG

expect_normal_exit $PMEMPOOL$EXESUFFIX >> $LOG
expect_normal_exit $PMEMPOOL$EXESUFFIX --version >> $LOG
expect_normal_exit $PMEMPOOL$EXESUFFIX --help >> $LOG

check

pass
