# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2017-2019, Intel Corporation

#
# src/test/obj_ctl_stats/Makefile -- build obj_ctl_stats test
#
TARGET = obj_ctl_stats
OBJS = obj_ctl_stats.o

LIBPMEMOBJ=y

include ../Makefile.inc
