#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2019, Intel Corporation

. $UNITTEST_SH

require_test_type short
require_fs_type any
configure_valgrind pmemcheck force-enable

setup

expect_normal_exit ./obj_ctl_stats$EXESUFFIX $DIR/testfile1

pass
