# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018-2019, Intel Corporation

#
# src/test/ctl_prefault/Makefile -- build ctl_prefault test
#
TARGET = ctl_prefault
OBJS = ctl_prefault.o

LIBPMEMBLK=y
LIBPMEMLOG=y
LIBPMEMOBJ=y

include ../Makefile.inc
