#!/usr/bin/env bash
#
# Copyright 2018-2019, Intel Corporation
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in
#       the documentation and/or other materials provided with the
#       distribution.
#
#     * Neither the name of the copyright holder nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#


. ../unittest/unittest.sh

require_test_type short

setup

# without fallocate, creating pool causes writes to each block and
# number of page faults is the same no matter if prefaulting is enabled
require_native_fallocate $DIR/testfile1

# create, don't prefault
expect_normal_exit ./ctl_prefault$EXESUFFIX obj $DIR/testfile1 0 0
pagefault_create_baseline=`cat out$UNITTEST_NUM.log | sed -n '3p'`

# open, don't prefault
expect_normal_exit ./ctl_prefault$EXESUFFIX obj $DIR/testfile1 0 1
pagefault_open_baseline=`cat out$UNITTEST_NUM.log | sed -n '3p'`

rm -f $DIR/testfile1

# create, prefault
expect_normal_exit ./ctl_prefault$EXESUFFIX obj $DIR/testfile1 2 0
pagefault_create_prefault=`cat out$UNITTEST_NUM.log | sed -n '3p'`

# open, prefault
expect_normal_exit ./ctl_prefault$EXESUFFIX obj $DIR/testfile1 1 1
pagefault_open_prefault=`cat out$UNITTEST_NUM.log | sed -n '3p'`

rm -f $DIR/testfile1

if [ ${pagefault_create_baseline} -ge ${pagefault_create_prefault} ]; then
	fatal "create: ${pagefault_create_baseline} >= ${pagefault_create_prefault} "
fi

if [ ${pagefault_open_baseline} -ge ${pagefault_open_prefault} ]; then
	fatal "open: ${pagefault_open_baseline} >= ${pagefault_open_prefault}"
fi

pass
