# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018-2019, Intel Corporation

#
# src/test/pmreorder_simple/Makefile -- build pmreorder_simple
# unit test
#

TARGET = pmreorder_simple
OBJS = pmreorder_simple.o

LIBPMEM=y

# included for VALGRIND_EMIT_LOG
LIBPMEMCOMMON=y

include ../Makefile.inc
