#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018-2019, Intel Corporation
#
#
# pmempool_rm/TEST10 -- test for pmempool rm in interactive mode
#

. $UNITTEST_SH

require_test_type medium
require_fs_type any
require_no_superuser

setup
LOG=out$UNITTEST_NUM.log

# Create pmemlog, pmemblk and pmemobj pools
expect_normal_exit $PMEMPOOL$EXESUFFIX create log $DIR/pool.log
expect_normal_exit $PMEMPOOL$EXESUFFIX create blk 512 $DIR/pool.blk
expect_normal_exit $PMEMPOOL$EXESUFFIX create obj $DIR/pool.obj

# Create poolset
create_poolset $DIR/pool.set 32M:$DIR/pool.part1:z 32M:$DIR/pool.part2:z

# Create pmemobj pool from the poolset
expect_normal_exit $PMEMPOOL$EXESUFFIX create obj $DIR/pool.set

check_files\
	$DIR/pool.log\
	$DIR/pool.blk\
	$DIR/pool.obj\
	$DIR/pool.set\
	$DIR/pool.part1\
	$DIR/pool.part2

chmod 400\
	$DIR/pool.log\
	$DIR/pool.blk\
	$DIR/pool.obj\
	$DIR/pool.set\
	$DIR/pool.part1\
	$DIR/pool.part2

echo Y | expect_normal_exit $PMEMPOOL$EXESUFFIX rm $DIR/pool.log > $LOG
echo n | expect_normal_exit $PMEMPOOL$EXESUFFIX rm $DIR/pool.blk >> $LOG
echo y | expect_normal_exit $PMEMPOOL$EXESUFFIX rm $DIR/pool.obj >> $LOG
echo N | expect_normal_exit $PMEMPOOL$EXESUFFIX rm $DIR/pool.part1 >> $LOG
echo n | expect_normal_exit $PMEMPOOL$EXESUFFIX rm $DIR/pool.part2 >> $LOG

check_files\
	$DIR/pool.blk\
	$DIR/pool.set\
	$DIR/pool.part1\
	$DIR/pool.part2

check_no_files\
	$DIR/pool.log\
	$DIR/pool.obj

expect_normal_exit $PMEMPOOL$EXESUFFIX rm $DIR/pool.set >> $LOG <<EOF
y
n
EOF

check_no_files $DIR/pool.part1

check_files\
	$DIR/pool.set\
	$DIR/pool.part2

pass
