#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2014-2018, Intel Corporation
#
#
# pmempool_rm/TEST1 -- test for pmempool rm
#

. ../unittest/unittest.sh

require_test_type medium

require_no_superuser

setup

LOG=out${UNITTEST_NUM}.log
rm -f $LOG && touch $LOG

# Create pmemlog, pmemblk and pmemobj pools
expect_normal_exit $PMEMPOOL$EXESUFFIX create -m400 log $DIR/pool.log
expect_normal_exit $PMEMPOOL$EXESUFFIX create -m440 blk 512 $DIR/pool.blk
expect_normal_exit $PMEMPOOL$EXESUFFIX create -m444 obj $DIR/pool.obj

# Create poolset with replica
create_poolset $DIR/pool.set 32M:$DIR/pool.part1:z 32M:$DIR/pool.part2:z\
	R 32M:$DIR/rep.part1:z 32M:$DIR/rep.part2:z

# Create pmemobj pools from the poolset
expect_normal_exit $PMEMPOOL$EXESUFFIX create -m444 obj $DIR/pool.set

chmod 444 $DIR/pool.set $DIR/pool.part1 $DIR/pool.part2 $DIR/rep.part1 $DIR/rep.part2

# Check if all pools and poolset exist
check_files\
	$DIR/pool.log\
	$DIR/pool.blk\
	$DIR/pool.obj\
	$DIR/pool.set\
	$DIR/pool.part1\
	$DIR/pool.part2\
	$DIR/rep.part1\
	$DIR/rep.part2

expect_normal_exit $PMEMPOOL$EXESUFFIX rm -sv\
	$DIR/pool.log\
	$DIR/pool.blk\
	$DIR/pool.obj\
	$DIR/pool.set >> $LOG 2>&1 << EOF
n
n
n
y
y
y
y
n
EOF

check_files\
	$DIR/pool.log\
	$DIR/pool.blk\
	$DIR/pool.obj\
	$DIR/pool.set\

check_no_files\
	$DIR/pool.part1\
	$DIR/pool.part2\
	$DIR/rep.part1\
	$DIR/rep.part2

expect_normal_exit $PMEMPOOL$EXESUFFIX create -m444 obj $DIR/pool.set

check_files\
	$DIR/pool.log\
	$DIR/pool.blk\
	$DIR/pool.obj\
	$DIR/pool.set\
	$DIR/pool.part1\
	$DIR/pool.part2\
	$DIR/rep.part1\
	$DIR/rep.part2

expect_normal_exit $PMEMPOOL$EXESUFFIX rm -fvl\
	$DIR/pool.log\
	$DIR/pool.blk\
	$DIR/pool.obj\
	$DIR/pool.set >> $LOG

check_no_files\
	$DIR/pool.log\
	$DIR/pool.blk\
	$DIR/pool.obj\
	$DIR/pool.set\
	$DIR/pool.part1\
	$DIR/pool.part2\
	$DIR/rep.part1\
	$DIR/rep.part2
check

pass
