#!/usr/bin/env bash
#
# Copyright 2018, Intel Corporation
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in
#       the documentation and/or other materials provided with the
#       distribution.
#
#     * Neither the name of the copyright holder nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
#
# pmempool_rm/TEST11 -- test for pmempool rm using 'yes','no' responses
#

. ../unittest/unittest.sh

require_test_type medium
require_fs_type any

setup

LOG=out${UNITTEST_NUM}.log
rm -f $LOG && touch $LOG

# Create pmemlog, pmemblk and pmemobj pools
expect_normal_exit $PMEMPOOL$EXESUFFIX create -m400 log $DIR/pool.log
expect_normal_exit $PMEMPOOL$EXESUFFIX create -m440 blk 512 $DIR/pool.blk
expect_normal_exit $PMEMPOOL$EXESUFFIX create -m444 obj $DIR/pool.obj

# Create poolset with replica
create_poolset $DIR/pool.set 32M:$DIR/pool.part1:z 32M:$DIR/pool.part2:z\
        R 32M:$DIR/rep.part1:z 32M:$DIR/rep.part2:z

# Check if pools exists
check_files\
	$DIR/pool.log\
	$DIR/pool.blk\
	$DIR/pool.obj\
	$DIR/pool.set\
	$DIR/pool.part1\
	$DIR/pool.part2\
	$DIR/rep.part1\
	$DIR/rep.part2

# Try to remove all files in interactive mode
expect_normal_exit $PMEMPOOL$EXESUFFIX rm -il\
	$DIR/pool.log\
	$DIR/pool.blk\
	$DIR/pool.obj\
	$DIR/pool.set >> $LOG 2>&1 <<EOF
No
no
N
n
Yes
yes
Y
y
EOF

check_files\
	$DIR/pool.log\
	$DIR/pool.blk\
	$DIR/pool.obj\
	$DIR/pool.part1\

check_no_files\
	$DIR/pool.part2\
	$DIR/rep.part1\
	$DIR/rep.part2\
	$DIR/pool.set

# Test if behavior is proper when we type improper input
expect_normal_exit $PMEMPOOL$EXESUFFIX rm -il\
	$DIR/pool.log\
	$DIR/pool.blk\
	$DIR/pool.obj\
	$DIR/pool.part1 >> $LOG 2>&1 <<EOF
fsdfdsf
nope
yes
bla
Yes
xd

N
EOF

check_no_files\
	$DIR/pool.log\
	$DIR/pool.blk\
	$DIR/pool.obj

check_files\
	$DIR/pool.part1

pass

