#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2018, Intel Corporation
#
#
# pmempool_rm/TEST8 -- test for pmempool rm
#
# Same as TEST4, but run on a pool set that spans two Device DAX devices
# with 2M alignment.
#

. $UNITTEST_SH

require_test_type medium
require_fs_type any
require_dax_device_alignments 2097152 2097152 # 2MiB

setup

create_poolset $DIR/testset1 AUTO:${DEVICE_DAX_PATH[0]} AUTO:${DEVICE_DAX_PATH[1]} \
	O SINGLEHDR

expect_normal_exit $PMEMPOOL$EXESUFFIX rm -af $DIR/testset1

check_no_files $DIR/testset1

pass
