#!/usr/bin/env bash
#
# Copyright 2015-2019, Intel Corporation
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in
#       the documentation and/or other materials provided with the
#       distribution.
#
#     * Neither the name of the copyright holder nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
#
# pmempool_rm/TEST5 -- test for pmempool rm
#

. ../unittest/unittest.sh

require_test_type medium

setup

create_poolset $DIR/pool.set\
	8M:$DIR/pool1:x\
	8M:$DIR/pool2:x\
	8M:$DIR/pool3:x\
	8M:$DIR/pool4:x

expect_normal_exit $PMEMPOOL$EXESUFFIX create obj $DIR/pool.set
expect_normal_exit $PMEMPOOL$EXESUFFIX create obj $DIR/pool.1
expect_normal_exit $PMEMPOOL$EXESUFFIX create obj $DIR/pool.2
check_files $DIR/pool.set $DIR/pool1 $DIR/pool2 $DIR/pool3 $DIR/pool4\
	$DIR/pool.1 $DIR/pool.2
expect_normal_exit $PMEMPOOL$EXESUFFIX rm $DIR/pool2 $DIR/pool3
check_no_file $DIR/pool2 $DIR/pool3

expect_abnormal_exit $PMEMPOOL$EXESUFFIX rm -a\
	$DIR/pool.1 $DIR/pool.set $DIR/pool.2 2>log$UNITTEST_NUM.log

check_no_files $DIR/pool2 $DIR/pool3 \
	$DIR/pool.1 $DIR/pool.2
check_file $DIR/pool.set $DIR/pool1 $DIR/pool4

check

pass
