#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2018, Intel Corporation
#
#
# pmempool_rm/TEST2 -- test for pmempool rm
#

. $UNITTEST_SH

require_test_type medium

setup

LOG=out${UNITTEST_NUM}.log
rm -f $LOG && touch $LOG

# Create poolset with replica
create_poolset $DIR/pool.set 32M:$DIR/pool.part1:x 32M:$DIR/pool.part2:x\
	R 32M:$DIR/rep.part1 32M:$DIR/rep.part2

# Check if pool set file exists
check_files\
	$DIR/pool.set

# Check if all pools don't exist
check_no_files\
	$DIR/pool.obj\
	$DIR/pool.part1\
	$DIR/pool.part2\
	$DIR/rep.part1\
	$DIR/rep.part2

# Try to remove files without force flag
expect_abnormal_exit $PMEMPOOL$EXESUFFIX rm -v $DIR/pool.obj >> $LOG 2>&1
expect_abnormal_exit $PMEMPOOL$EXESUFFIX rm -sv $DIR/pool.set >> $LOG 2>&1

# Try to remove files with force flag
expect_normal_exit $PMEMPOOL$EXESUFFIX rm -lfv\
	$DIR/pool.obj\
	$DIR/pool.set >> $LOG 2>&1

check_no_files\
	$DIR/pool.set\
	$DIR/pool.obj\
	$DIR/pool.part1\
	$DIR/pool.part2\
	$DIR/rep.part1\
	$DIR/rep.part2

check

pass
