#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2018, Intel Corporation
#
#
# pmempool_rm/TEST3 -- test for pmempool rm
#

. $UNITTEST_SH

require_test_type medium
require_dax_devices 1

setup

expect_normal_exit $PMEMPOOL$EXESUFFIX rm -f $DEVICE_DAX_PATH

pass
