#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2017-2018, Intel Corporation
#
#
# pmempool_rm/TEST7 -- test for pmempool rm in interactive mode
#

. ../unittest/unittest.sh

require_test_type medium
require_fs_type any

setup

LOG=out${UNITTEST_NUM}.log
rm -f $LOG && touch $LOG

# Create poolset with replica
create_poolset $DIR/pool.set 32M:$DIR/pool.part1:z 32M:$DIR/pool.part2:z\
	R 32M:$DIR/rep.part1:z 32M:$DIR/rep.part2:z

# Check if pool set file exists
check_files\
	$DIR/pool.set\
	$DIR/pool.part1\
	$DIR/pool.part2\
	$DIR/rep.part1\
	$DIR/rep.part2

# Try to remove all files in interactive mode
expect_normal_exit $PMEMPOOL$EXESUFFIX rm -il $DIR/pool.set >> $LOG 2>&1 <<EOF
Y
n
n
y
n
EOF

check_no_files\
	$DIR/pool.part1\
	$DIR/rep.part2

check_files\
	$DIR/pool.set\
	$DIR/pool.part2\
	$DIR/rep.part1

pass
