# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/pmempool_transform/Makefile -- build pmempool transform test
#

USE_PMEMOBJCLI=y
USE_DDMAP=y

include ../Makefile.inc
