#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation
#
#
# pmempool_transform/TEST14 -- test for transform with SINGLEHDR option
#
# adding the SINGLEHDR option
# case: two replicas:
# 1. two 4KB-aligned device daxes
# 2. three file-based parts
#

. $UNITTEST_SH

require_test_type medium
require_fs_type any

require_dax_device_alignments $SIZE_4KB $SIZE_4KB
require_max_devdax_size 0 $PMEMOBJ_MAX_ALLOC_SIZE

# the test takes too long under pmemcheck
configure_valgrind pmemcheck force-disable

setup

# test requires at least (size of device DAX #0 + 1G) of free space in $DIR
DAX_SIZE[0]=$(get_devdax_size 0)
SIZE_1G=$(convert_to_bytes 1G)
require_free_space $(( DAX_SIZE[0] + SIZE_1G ))

dax_device_zero

LOG=out${UNITTEST_NUM}.log
LOG_TEMP=out${UNITTEST_NUM}_part.log
rm -f $LOG && touch $LOG
rm -f $LOG_TEMP && touch $LOG_TEMP

LAYOUT=OBJ_LAYOUT$SUFFIX
POOLSET_IN=$DIR/poolset.in
POOLSET_OUT=$DIR/poolset.out

# Create poolset files
create_poolset $POOLSET_IN \
	AUTO:${DEVICE_DAX_PATH[0]}:x \
	AUTO:${DEVICE_DAX_PATH[1]}:x \
	R \
	${DAX_SIZE[0]}:$DIR/part00:x \
	1G:$DIR/part01:x

create_poolset $POOLSET_OUT \
	O SINGLEHDR \
	AUTO:${DEVICE_DAX_PATH[0]}:x \
	AUTO:${DEVICE_DAX_PATH[1]}:x \
	R \
	${DAX_SIZE[0]}:$DIR/part00:x \
	1G:$DIR/part01:x

OFFSET=${DAX_SIZE[0]}
ROOT_SIZE=$[OFFSET + 1024]

# CLI script for writing some data hitting all the parts
WRITE_SCRIPT=$DIR/write_data
cat << EOF > $WRITE_SCRIPT
pr $ROOT_SIZE
srcp 0 TestOK111
srcp $OFFSET TestOK222
EOF

# CLI script for reading 9 characters from all the parts
READ_SCRIPT=$DIR/read_data
cat << EOF > $READ_SCRIPT
srpr 0 9
srpr $OFFSET 9
EOF

# Log poolset structures
echo poolset_in >> $LOG_TEMP
cat $POOLSET_IN >> $LOG_TEMP
echo >> $LOG_TEMP
echo poolset_out >> $LOG_TEMP
cat $POOLSET_OUT >> $LOG_TEMP
echo >> $LOG_TEMP

# Create a pool
expect_normal_exit $PMEMPOOL$EXESUFFIX create --layout=$LAYOUT\
	obj $POOLSET_IN >> $LOG_TEMP

# Write some data into the pool, hitting two part files
expect_normal_exit $PMEMOBJCLI$EXESUFFIX -s $WRITE_SCRIPT $POOLSET_IN >> \
	$LOG_TEMP

# Check if correctly written
expect_normal_exit $PMEMOBJCLI$EXESUFFIX -s $READ_SCRIPT $POOLSET_IN >> \
	$LOG_TEMP

# Transform poolset
expect_normal_exit $PMEMPOOL$EXESUFFIX transform \
	$POOLSET_IN $POOLSET_OUT >> $LOG_TEMP

# Check if correctly transformed
expect_normal_exit $PMEMOBJCLI$EXESUFFIX -s $READ_SCRIPT $POOLSET_OUT >> \
	$LOG_TEMP

# Check metadata by pmempool info
dump_pool_info $POOLSET_OUT >> $LOG_TEMP
dump_pool_info ${DEVICE_DAX_PATH[0]} >> $LOG_TEMP
dump_pool_info $DIR/part00 >> $LOG_TEMP

mv $LOG_TEMP $LOG
check

pass
