# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018, Intel Corporation

#
# src/test/obj_root/Makefile -- build obj_root test
#
TARGET = obj_root
OBJS = obj_root.o

LIBPMEMOBJ=y

include ../Makefile.inc
