#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/obj_list_move/TEST2 -- unit test for list_move
#

. ../unittest/unittest.sh

require_test_type medium
require_build_type debug

setup

create_holey_file 1M $DIR/testfile

expect_normal_exit ../obj_list/obj_list$EXESUFFIX $DIR/testfile\
	i:0:-1 i:0:-1 i:0:-1 i:0:-1 i:0:-1 i:0:-1 P:2 R:2\
	M:0:0:0 P:2 R:2\
	M:0:1:0 P:2 R:2\
	M:0:1:1 P:2 R:2\
	M:1:0:0 P:2 R:2\
	M:-1:1:0 P:2 R:2\
	M:0:0:-1 P:2 R:2\
	M:0:0:3 P:2 R:2\
	M:3:1:0 P:2 R:2\

check

pass
