# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018, Intel Corporation

#
# examples/libpmemobj/queue/Makefile -- build the queue example
#
PROGS = queue

LIBS = -lpmemobj

include ../../Makefile.inc

queue: queue.o
