#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/log_pool/TEST8 -- unit test for pmemlog_create
#

. ../unittest/unittest.sh

require_test_type medium

setup
umask 0

#
# TEST8 non-existing file, poolsize < min required size
#
expect_normal_exit ./log_pool$EXESUFFIX c $DIR/testfile 1 0600

check_no_files $DIR/testfile

check

pass
