#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/log_pool/TEST20 -- unit test for pmemlog_open
#

. $UNITTEST_SH

require_test_type medium

setup
umask 0

#
# TEST20 non-existing file
#
expect_normal_exit ./log_pool$EXESUFFIX o $DIR/testfile

check

pass
