#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/log_pool/TEST27 -- unit test for pmemlog_open
#

. $UNITTEST_SH

require_test_type medium

setup
umask 0

#
# TEST27 existing file, file size >= min required size
#
create_poolset $DIR/testset 20M:$DIR/testfile1:x 20M:$DIR/testfile2:x

expect_normal_exit ./log_pool$EXESUFFIX c $DIR/testset 0 0640

expect_normal_exit ./log_pool$EXESUFFIX o $DIR/testset

check

pass
