#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/log_pool/TEST25 -- unit test for pmemlog_open
#

. ../unittest/unittest.sh

require_test_type medium

require_no_superuser

setup
umask 0

#
# TEST25 existing file, file size >= min required size
#        (no write permissions)
#
expect_normal_exit ./log_pool$EXESUFFIX c $DIR/testfile 20 0640
chmod -w $DIR/testfile

expect_normal_exit ./log_pool$EXESUFFIX o $DIR/testfile

check

pass
