#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/log_pool/TEST0 -- unit test for pmemlog_create
#

. ../unittest/unittest.sh

require_test_type medium

setup
umask 0

#
# TEST0 non-existing file, poolsize > 0
#
expect_normal_exit ./log_pool$EXESUFFIX c $DIR/testfile 20 0600

check_files $DIR/testfile

check

pass
