#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/log_pool/TEST22 -- unit test for pmemlog_open
#

. ../unittest/unittest.sh

require_test_type medium

setup
umask 0

#
# TEST22 existing file, file size < min required size
#        (valid pool header)
#
expect_normal_exit ./log_pool$EXESUFFIX c $DIR/testfile 20 0640
truncate -s 1M $DIR/testfile

expect_normal_exit ./log_pool$EXESUFFIX o $DIR/testfile

check

pass
