#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/log_pool/TEST12 -- unit test for pmemlog_create
#

. $UNITTEST_SH

require_test_type medium

setup
umask 0

#
# TEST12 non-existing file, poolsize > 0
#        (pool set with replica section)
#
create_poolset $DIR/testset 20M:$DIR/testfile1:x R 20M:$DIR/testfile2:x

expect_normal_exit ./log_pool$EXESUFFIX c $DIR/testset 0 0600

check_files $DIR/testset
check_no_files $DIR/testfile1 $DIR/testfile2

check

pass
