# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2024, Intel Corporation

vpath %.c ../core_log

TARGET = core_log_no_func
OBJS = core_log_no_func.o core_log_common.o

include ../core_log/Makefile.inc
INCS += -I../core_log
