#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2017-2023, Intel Corporation
#
#
# compat_incompat_features/TEST4 -- test for compat/incompat feature flags
#
# check if pool fails to open when incompat flags do not match poolset options
#

. ../unittest/unittest.sh

require_test_type	medium
require_fs_type		any

setup

. ./common.sh

# Create poolset file
create_poolset $POOLSET \
	o SINGLEHDR \
	20M:$DIR/part0:x \
	20M:$DIR/part1:x

# Create poolset
expect_normal_exit $PMEMPOOL$EXESUFFIX rm -f $POOLSET >> $LOG_TEMP
expect_normal_exit $PMEMPOOL$EXESUFFIX create ${create_args[obj]} \
	>> $LOG_TEMP

# Clear POOL_FEAT_SINGLEHDR incompat flag in header
set_incompat $DIR/part0 0 >> $LOG_TEMP

# Check if pool fails to open
expect_abnormal_exit ./pool_open$EXESUFFIX $POOLSET 2>&1
cat $LOG >> $LOG_TEMP
cat $ERR >> $ERR_TEMP

for flag in ${UNKNOWN_INCOMPAT[@]}; do
	# Set compat/incompat flags in headers
	set_incompat $DIR/part0 $flag >> $LOG_TEMP

	# Check if pool fails to open
	expect_abnormal_exit ./pool_open$EXESUFFIX $POOLSET 2>&1
	cat $LOG >> $LOG_TEMP
	cat $ERR >> $ERR_TEMP
done

mv $LOG_TEMP $LOG
mv $ERR_TEMP $ERR

check
pass
