#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2017-2023, Intel Corporation
#
#
# compat_incompat_features/TEST0 -- test for compat/incompat feature flags
#
# check if pool opens when compat flags are equal and nonzero
#

. ../unittest/unittest.sh

require_test_type	medium
require_fs_type		any

setup

. ./common.sh

# Create poolset file
create_poolset $POOLSET \
	20M:$DIR/part0:x \
	20M:$DIR/part1:x

expect_normal_exit $PMEMPOOL$EXESUFFIX rm -f $POOLSET >> $LOG_TEMP
expect_normal_exit $PMEMPOOL$EXESUFFIX create ${create_args[obj]} \
	>> $LOG_TEMP

for flag in ${UNKNOWN_COMPAT[@]}; do
	# Set compat/incompat flags in headers
	set_compat $DIR/part0 $flag >> $LOG_TEMP
	set_compat $DIR/part1 $flag >> $LOG_TEMP

	# Check if pool opens
	expect_normal_exit ./pool_open$EXESUFFIX $POOLSET 2>&1
	cat $LOG >> $LOG_TEMP
	cat $ERR >> $ERR_TEMP
done

mv $LOG_TEMP $LOG
mv $ERR_TEMP $ERR

check
pass
