#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2017-2018, Intel Corporation
#
#
# compat_incompat_features/TEST3 -- test for compat/incompat feature flags
#
# check if pool fails to open when incompat flags differ between parts
#

. ../unittest/unittest.sh

require_test_type	medium
require_fs_type		any

setup

. ./common.sh

# Create poolset file
create_poolset $POOLSET \
	20M:$DIR/part0:x \
	20M:$DIR/part1:x

for type in ${POOL_TYPES[@]}; do
	# Create poolset
	expect_normal_exit $PMEMPOOL$EXESUFFIX rm -f $POOLSET >> $LOG_TEMP
	expect_normal_exit $PMEMPOOL$EXESUFFIX create ${create_args[$type]} \
		>> $LOG_TEMP

	# Set compat/incompat flags in headers
	set_incompat $DIR/part0 $POOL_FEAT_SINGLEHDR >> $LOG_TEMP

	# Check if pool fails to open
	expect_abnormal_exit ./pool_open$EXESUFFIX $type $POOLSET 2>&1
	cat $LOG >> $LOG_TEMP
	cat $ERR >> $ERR_TEMP

	# Set compat/incompat flags in headers
	set_incompat $DIR/part0 0 >> $LOG_TEMP
	set_incompat $DIR/part1 $POOL_FEAT_SINGLEHDR >> $LOG_TEMP

	# Check if pool fails to open
	expect_abnormal_exit ./pool_open$EXESUFFIX $type $POOLSET 2>&1
	cat $LOG >> $LOG_TEMP
	cat $ERR >> $ERR_TEMP

	# Set compat/incompat flags in headers
	set_incompat $DIR/part0 ${UNKNOWN_INCOMPAT[0]} >> $LOG_TEMP

	# Check if pool fails to open
	expect_abnormal_exit ./pool_open$EXESUFFIX $type $POOLSET 2>&1
	cat $LOG >> $LOG_TEMP
	cat $ERR >> $ERR_TEMP

	# Set compat/incompat flags in headers
	set_incompat $DIR/part1 ${UNKNOWN_INCOMPAT[1]} >> $LOG_TEMP

	# Check if pool fails to open
	expect_abnormal_exit ./pool_open$EXESUFFIX $type $POOLSET 2>&1
	cat $LOG >> $LOG_TEMP
	cat $ERR >> $ERR_TEMP
done

mv $LOG_TEMP $LOG
mv $ERR_TEMP $ERR

check
pass
