#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2017-2018, Intel Corporation
#
#
# compat_incompat_features/TEST1 -- test for compat/incompat feature flags
#
# check if pool fails to open when compat flags differ between parts
#

. $UNITTEST_SH

require_test_type	medium
require_fs_type		any

setup

. ./common.sh

# Create poolset file
create_poolset $POOLSET \
	20M:$DIR/part0:x \
	20M:$DIR/part1:x

for type in ${POOL_TYPES[@]}; do
	# Create poolset
	expect_normal_exit $PMEMPOOL$EXESUFFIX rm -f $POOLSET >> $LOG_TEMP
	expect_normal_exit $PMEMPOOL$EXESUFFIX create ${create_args[$type]} \
		>> $LOG_TEMP

	# Set compat flag in part 0 header
	set_compat $DIR/part0 ${UNKNOWN_COMPAT[0]} >> $LOG_TEMP

	# Check if pool opens
	expect_abnormal_exit ./pool_open$EXESUFFIX $type $POOLSET 2>&1
	cat $LOG >> $LOG_TEMP
	cat $ERR >> $ERR_TEMP

	# Set compat flag in part 1 headers
	set_compat $DIR/part1 ${UNKNOWN_COMPAT[1]} >> $LOG_TEMP

	# Check if pool opens
	expect_abnormal_exit ./pool_open$EXESUFFIX $type $POOLSET 2>&1
	cat $LOG >> $LOG_TEMP
	cat $ERR >> $ERR_TEMP
done

mv $LOG_TEMP $LOG
mv $ERR_TEMP $ERR

check
pass
