#!/usr/bin/env bash
#
# Copyright 2014-2019, Intel Corporation
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in
#       the documentation and/or other materials provided with the
#       distribution.
#
#     * Neither the name of the copyright holder nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
#
# magic/TEST0 -- test for magic file script
#

. ../unittest/unittest.sh

require_test_type medium

require_build_type release

# There is no point in testing the file command using memcheck
# because even if it does report any problems we can't fix it
configure_valgrind force-disable

require_command file

setup

POOL=$DIR/file.pool
LOG=out${UNITTEST_NUM}.log
MAGIC=../../../utils/pmdk.magic
rm -f $LOG && touch $LOG

rm -f $POOL
expect_normal_exit $PMEMPOOL create blk 512 $POOL
expect_normal_exit file -m $MAGIC $POOL >> $LOG

rm -f $POOL
expect_normal_exit $PMEMPOOL create log $POOL
expect_normal_exit file -m $MAGIC $POOL >> $LOG

rm -f $POOL
expect_normal_exit $PMEMPOOL create obj $POOL
expect_normal_exit file -m $MAGIC $POOL >> $LOG

rm -f $POOL
create_poolset $POOL 32M:file.part1:x 32M:file.part2:x
expect_normal_exit file -m $MAGIC $POOL >> $LOG

rm -f $POOL
create_poolset $POOL 32M:file.part1:x 32M:file.part2:x R 32M:file.rep1:x 32M:file.rep2:x
expect_normal_exit file -m $MAGIC $POOL >> $LOG

check

pass
