# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2014-2018, Intel Corporation

#
# src/test/pmem_map_file/Makefile -- build pmem_map_file() unit test
#
TARGET = pmem_map_file
OBJS = pmem_map_file.o mocks_posix.o

LIBPMEM=y

include ../Makefile.inc

LIBS += $(LIBDL)
