#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2014-2019, Intel Corporation

#
# src/test/log_recovery/TEST0 -- unit test for pmemlog recovery
#                                pmemlog_appendv() is used to append data
#

. $UNITTEST_SH

require_test_type medium

require_build_type nondebug static-nondebug

# exits with locked mutexes
configure_valgrind helgrind force-disable
configure_valgrind drd force-disable
configure_valgrind pmemcheck force-disable

setup

# this test invokes sigsegvs by design
export ASAN_OPTIONS=handle_segv=0

touch $DIR/testfile1

expect_normal_exit ./log_recovery$EXESUFFIX $DIR/testfile1 v

check_pool $DIR/testfile1

check

pass
