#!/usr/bin/env bash
#
# Copyright 2015-2019, Intel Corporation
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in
#       the documentation and/or other materials provided with the
#       distribution.
#
#     * Neither the name of the copyright holder nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

#
# src/test/obj_list_recovery/TEST0 -- unit test for list recovery process
#

. ../unittest/unittest.sh

require_test_type medium
require_build_type debug

# exits with locked mutexes
configure_valgrind helgrind force-disable
configure_valgrind drd force-disable

# the test delibretly fails at various stages of redo logging
configure_valgrind pmemcheck force-disable ../obj_list/obj_list$EXESUFFIX

setup

create_holey_file 1M $DIR/testfile

rm -f log${UNITTEST_NUM}.log

function concat_log()
{
	cat out${UNITTEST_NUM}.log >> log${UNITTEST_NUM}.log
	rm out${UNITTEST_NUM}.log
}

# fail after finish flag is set in redo log
expect_normal_exit\
	../obj_list/obj_list$EXESUFFIX $DIR/testfile\
		i:1:0 i:1:0\
		F:after_finish\
		i:1:0

concat_log

# check
expect_normal_exit\
	../obj_list/obj_list$EXESUFFIX $DIR/testfile\
		P:2 R:2\
		V\
		P:2 R:2

concat_log

# fail before finish flag is set in redo log
expect_normal_exit\
	../obj_list/obj_list$EXESUFFIX $DIR/testfile\
		F:before_finish\
		i:1:0

concat_log

# check
expect_normal_exit\
	../obj_list/obj_list$EXESUFFIX $DIR/testfile\
		P:2 R:2\
		V\
		P:2 R:2

concat_log

check

pass
