#!/bin/bash -e
#
# Copyright 2016, Intel Corporation
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in
#       the documentation and/or other materials provided with the
#       distribution.
#
#     * Neither the name of the copyright holder nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

#
# src/test/rpmem_obc_int/TEST1 -- integration test for rpmem_obc and
# rpmemd_obc modules
#

export UNITTEST_NAME=rpmem_obc_int/TEST1
export UNITTEST_NUM=1

# standard unit test setup
. ../unittest/unittest.sh

require_fs_type none
require_build_type nondebug debug

setup

require_nodes 2
require_node_log_files 0 $RPMEM_LOG_FILE $RPMEMD_LOG_FILE
require_node_log_files 1 $RPMEM_LOG_FILE $RPMEMD_LOG_FILE

SRV=srv${UNITTEST_NUM}.pid
CNT_CREATE=cnt_create${UNITTEST_NUM}.pid
CNT_OPEN=cnt_open${UNITTEST_NUM}.pid
CNT_REMOVE=cnt_remove${UNITTEST_NUM}.pid

clean_remote_node 0 $SRV $CNT_OPEN $CNT_CREATE $CNT_REMOVE

expect_normal_exit run_on_node_background 0 $SRV\
	./rpmem_obc_int$EXESUFFIX server_sim\
	${NODE_ADDR[0]} $RPMEM_PORT

expect_normal_exit wait_on_node_port 0 $SRV $RPMEM_PORT

expect_normal_exit run_on_node_background 1 $CNT_CREATE\
	./rpmem_obc_int$EXESUFFIX client_create\
	${NODE_ADDR[0]}:${RPMEM_PORT}

expect_normal_exit run_on_node_background 1 $CNT_OPEN\
	./rpmem_obc_int$EXESUFFIX client_open\
	${NODE_ADDR[0]}:${RPMEM_PORT}

expect_normal_exit run_on_node_background 1 $CNT_REMOVE\
	./rpmem_obc_int$EXESUFFIX client_remove\
	${NODE_ADDR[0]}:${RPMEM_PORT}


expect_normal_exit wait_on_node 1 $CNT_OPEN
expect_normal_exit wait_on_node 1 $CNT_CREATE
expect_normal_exit wait_on_node 1 $CNT_REMOVE
expect_normal_exit wait_on_node 0 $SRV

pass
