#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_sync/TEST0 -- unit test for PMEM-resident locks
#

. $UNITTEST_SH

require_test_type medium

require_fs_type none
require_build_type debug nondebug

setup

expect_normal_exit ./obj_sync$EXESUFFIX m 50 5

check

pass
