#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2023, Intel Corporation

#
# src/test/obj_sync/TEST7 -- unit test for PMEM-resident locks
#

. ../unittest/unittest.sh

# XXX disable the test until https://github.com/pmem/pmdk/issues/5727 is fixed.
DISABLED

require_test_type medium

require_fs_type none
require_build_type debug nondebug

setup

expect_normal_exit ./obj_sync$EXESUFFIX t 50 5

check

pass
