#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2023, Intel Corporation

#
# src/test/obj_sync/TEST0 -- unit test for PMEM-resident locks
#

. ../unittest/unittest.sh

require_test_type medium

require_fs_type none
require_build_type debug nondebug
# XXX disable the test for 'pmemcheck'
# until https://github.com/pmem/pmdk/issues/5643 is fixed.
configure_valgrind pmemcheck force-disable

setup

expect_normal_exit ./obj_sync$EXESUFFIX m 50 5

check

pass
