#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2017-2019, Intel Corporation

#
# src/test/obj_sync/TEST9 -- unit test for PMEM-resident locks
#

. $UNITTEST_SH

require_test_type medium

require_fs_type none
require_build_type debug nondebug
require_valgrind 3.10
configure_valgrind helgrind force-enable

setup

expect_normal_exit ./obj_sync$EXESUFFIX t 10 5

pass
