# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2018, Intel Corporation

#
# src/test/remote_basic/Makefile -- build remote_basic unit test
#
SCP_TO_REMOTE_NODES = y

TARGET = remote_basic
OBJS = remote_basic.o

LIBPMEMCOMMON=y

include ../Makefile.inc
