#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/remote_basic/TEST1 -- unit test for remote tests support
#

. ../unittest/unittest.sh

require_test_type medium

setup

# how much remote nodes are required
require_nodes 1

# create a local test file for this unit test
TEST_FILE_REMOTE="test-file"
TEST_FILE_LOCAL="$DIR/$TEST_FILE_REMOTE"
touch $TEST_FILE_LOCAL

# list of required files that should be copied to the remote nodes
copy_files_to_node 0 ${NODE_DIR[0]} $TEST_FILE_LOCAL

# remove the local test file
rm -f $TEST_FILE_LOCAL

# PID file name for remote test run in background
PID_FILE="pid-file-$$.txt"

# register the list of PID files to be cleaned in case of an error
clean_remote_node 0 $PID_FILE

#
# Run commands on remote nodes
# (run_on_node or run_on_node_background can be used here).
#
# LD_LIBRARY_PATH for the n-th remote node can be provided
# in the array NODE_LD_LIBRARY_PATH[n].
#
expect_normal_exit run_on_node_background 0 $PID_FILE ./remote_basic$EXESUFFIX ${NODE_DIR[0]}$TEST_FILE_REMOTE
expect_normal_exit wait_on_node 0 $PID_FILE

check

pass
