#!/usr/bin/env bash
#
# Copyright 2017, Intel Corporation
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in
#       the documentation and/or other materials provided with the
#       distribution.
#
#     * Neither the name of the copyright holder nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

#
# src/test/rpmem_basic/TEST12 -- unit test for minimal part size
#
export UNITTEST_NAME=rpmem_basic/TEST12
export UNITTEST_NUM=12

# standard unit test setup
. ../unittest/unittest.sh

require_test_type medium

setup

. setup.sh

create_poolset $DIR/pool0.set  8M:$PART_DIR/pool0.part0 8M:$PART_DIR/pool0.part1

run_on_node 0 "rm -rf $POOLS_DIR $POOLS_PART && mkdir -p $POOLS_DIR && mkdir -p $POOLS_PART"

copy_files_to_node 0 $POOLS_DIR $DIR/pool0.set

# Minimal part size bigger than pool parts - create fail
ARGS="$ARGS test_create 0 pool0.set ${NODE_ADDR[0]} pool 8M 10M"
# Minimal part size equal to pool parts - create succeed
ARGS="$ARGS test_create 0 pool0.set ${NODE_ADDR[0]} pool 8M 8M test_close 0"
# Remove create pool parts before creating them one more time
ARGS="$ARGS test_remove ${NODE_ADDR[0]} pool0.set 0 0"
# Minimal part size smaller than pool parts - create succeed
ARGS="$ARGS test_create 0 pool0.set ${NODE_ADDR[0]} pool 8M 4M test_close 0"
# Minimal part size bigger than pool parts - open fail
ARGS="$ARGS test_open 0 pool0.set ${NODE_ADDR[0]} pool 8M 10M init"
# Minimal part size equal to pool parts - open succeed
ARGS="$ARGS test_open 0 pool0.set ${NODE_ADDR[0]} pool 8M 8M init test_close 0"
# Minimal part size smaller than pool parts - open succeed
ARGS="$ARGS test_open 0 pool0.set ${NODE_ADDR[0]} pool 8M 4M init test_close 0"

expect_normal_exit run_on_node 1 ./rpmem_basic$EXESUFFIX $ARGS

check

pass
