#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2017-2019, Intel Corporation

#
# src/test/rpmem_basic/TEST11 -- test rpmemd persistency policy for GPSPM
#

. $UNITTEST_SH

require_test_type medium

. setup.sh

setup

. common_pm_policy.sh

for PMEM_IS_PMEM_FORCE in {0..1}; do
	test_pm_policy $PMEM_IS_PMEM_FORCE
done

check_local

pass
