#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018-2019, Intel Corporation

#
# src/test/rpmem_basic/TEST19 -- unit test for rpmem create with failing rpmemd
#

. ../unittest/unittest.sh

require_test_type medium

SETUP_MANUAL_INIT_RPMEM=1
. setup.sh

PID_FILE=SKIP
CONF_FILE=in19.conf
init_rpmem_on_node 1 0:$PID_FILE:${NODE_DIR[0]}/$CONF_FILE

setup

create_poolset $DIR/pool0.set 16M:$PART_DIR/pool0.part0

run_on_node 0 "rm -rf ${NODE_DIR[0]}$POOLS_DIR ${NODE_DIR[0]}$POOLS_PART && mkdir -p ${NODE_DIR[0]}$POOLS_PART"
copy_files_to_node 0 ${NODE_DIR[0]}$POOLS_DIR $DIR/pool0.set
copy_files_to_node 0 ${NODE_DIR[0]} $CONF_FILE

# Create valid pool but because of malformed config file rpmemd should return
# EINVAL status during initialization
ARGS="$ARGS test_create 0 pool0.set ${NODE_ADDR[0]} mem 8M none"
expect_normal_exit run_on_node 1 ./rpmem_basic$EXESUFFIX $ARGS

check

pass
