#!/bin/bash -e
#
# Copyright 2016, Intel Corporation
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in
#       the documentation and/or other materials provided with the
#       distribution.
#
#     * Neither the name of the copyright holder nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

#
# src/test/rpmem_basic/TEST12 -- unit test for rpmem_persist
#                                in 2-to-1 configuration
#
export UNITTEST_NAME=rpmem_basic/TEST12
export UNITTEST_NUM=12

# standard unit test setup
. ../unittest/unittest.sh

require_test_type medium

setup

. setup2to1.sh

for node in 1 2; do

	cat > $DIR/pool0.set << EOF
PMEMPOOLSET
8M ${PART_DIR[${node}]}/pool0.part0
8M ${PART_DIR[${node}]}/pool0.part1
EOF

	run_on_node ${REPLICA[${node}]} "rm -rf $POOLS_DIR $POOLS_PART && mkdir -p $POOLS_DIR && mkdir -p $POOLS_PART"

	copy_files_to_node ${REPLICA[${node}]} $POOLS_DIR $DIR/pool0.set

	expect_normal_exit run_on_node ${node} ./rpmem_basic$EXESUFFIX\
		test_create 0 pool0.set ${REP_ADDR[${node}]} mem 8M test_close 0

	expect_normal_exit run_on_node ${REPLICA[${node}]} ./rpmem_basic$EXESUFFIX\
		fill_pool $POOLS_DIR/pool0.set 1234
done

expect_normal_exit run_on_node_background 1 ${PID_FILE[1]} ./rpmem_basic$EXESUFFIX\
	test_open 0 pool0.set ${REP_ADDR[1]} pool 8M\
	test_persist 0 4321 8 8\
	test_close 0

expect_normal_exit run_on_node_background 2 ${PID_FILE[2]} ./rpmem_basic$EXESUFFIX\
	test_open 0 pool0.set ${REP_ADDR[2]} pool 8M\
	test_persist 0 4321 8 8\
	test_close 0

for node in 1 2; do
	expect_normal_exit wait_on_node ${node} ${PID_FILE[${node}]}

	expect_normal_exit run_on_node ${REPLICA[${node}]} ./rpmem_basic$EXESUFFIX\
		check_pool $POOLS_DIR/pool0.set 4321 8M
done

pass
