#!/usr/bin/env bash
#
# Copyright 2017-2019, Intel Corporation
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in
#       the documentation and/or other materials provided with the
#       distribution.
#
#     * Neither the name of the copyright holder nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

#
# src/test/rpmem_basic/TEST12 -- unit test for handling rpmemd termination
#

. ../unittest/unittest.sh

require_test_type medium

SETUP_MANUAL_INIT_RPMEM=1
. setup.sh

PID_FILE=rpmemd.pid
init_rpmem_on_node 1 0:$PID_FILE

setup

create_poolset $DIR/pool0.set  8M:$PART_DIR/pool0.part0 8M:$PART_DIR/pool0.part1

run_on_node 0 "rm -rf ${RPMEM_POOLSET_DIR[0]} $PART_DIR && mkdir -p ${RPMEM_POOLSET_DIR[0]} && mkdir -p $PART_DIR"

copy_files_to_node 0 ${RPMEM_POOLSET_DIR[0]} $DIR/pool0.set

SEED=4321
CREATE="test_create 0 pool0.set ${NODE_ADDR[0]} pool 8M none"
OPEN="test_open 0 pool0.set ${NODE_ADDR[0]} pool 8M init none"
PERSIST="test_persist 0 $SEED 1 1 0"
READ="test_read 0 $SEED"
TERMINATE="rpmemd_terminate 0 ${NODE_TEST_DIR[0]}/$PID_FILE"
CLOSE="test_close 0"

ARGS="$ARGS $CREATE $PERSIST $CLOSE"
ARGS="$ARGS $OPEN $TERMINATE wait $CLOSE"
ARGS="$ARGS $OPEN $TERMINATE nowait $CLOSE"
ARGS="$ARGS $OPEN $TERMINATE wait $PERSIST $CLOSE"
ARGS="$ARGS $OPEN $TERMINATE nowait $PERSIST $CLOSE"
ARGS="$ARGS $OPEN $TERMINATE wait $READ $CLOSE"
ARGS="$ARGS $OPEN $TERMINATE nowait $READ $CLOSE"

expect_normal_exit run_on_node 1 ./rpmem_basic$EXESUFFIX $ARGS

expect_normal_exit run_on_node 0 ./rpmem_basic$EXESUFFIX\
	check_pool ${RPMEM_POOLSET_DIR[0]}/pool0.set $SEED 8M

pass
