# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2019, Intel Corporation

#
# src/test/libpmempool_check_version/Makefile -- build libpmempool_check_version unittest
#

TARGET = libpmempool_check_version
OBJS = libpmempool_check_version.o

LIBPMEMPOOL=y

include ../Makefile.inc
