# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2017-2019, Intel Corporation

#
# src/test/obj_zones/Makefile -- build obj_zones test
#
TARGET = obj_zones
OBJS = obj_zones.o

LIBPMEMOBJ=y

include ../Makefile.inc
