#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2017-2019, Intel Corporation

. ../unittest/unittest.sh

# too large
configure_valgrind force-disable

require_test_type medium

setup

create_holey_file 64G $DIR/testfile1

expect_normal_exit ./obj_zones$EXESUFFIX $DIR/testfile1 c

check

expect_normal_exit ./obj_zones$EXESUFFIX $DIR/testfile1 o

pass
