# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_tx_realloc/Makefile -- build obj_tx_realloc unit test
#
TARGET = obj_tx_realloc
OBJS = obj_tx_realloc.o

LIBPMEMCOMMON=y
LIBPMEMOBJ=y

include ../Makefile.inc
