#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018-2019, Intel Corporation

#
# src/test/ex_pmreorder/TEST0 -- test for pmreorder list example
#

. $UNITTEST_SH

LIBPMEM_SO=${PMDK_LIB_PATH}/libpmem.so.1

require_test_type medium
require_build_type debug nondebug
require_fs_type any
require_pmemcheck_version_ge 1 0 $LIBPMEM_SO
require_pmemcheck_version_lt 2 0 $LIBPMEM_SO
require_pmreorder $LIBPMEM_SO

setup

export PMREORDER_EMIT_LOG=1
truncate -s 2M $DIR/testfile

EX_PATH=../../examples/pmreorder
BIN="$EX_PATH/pmreorder_list$EXESUFFIX"
PMEMCHECK_CMD="$BIN g $DIR/testfile"
PMREORDER_CMD="$BIN c"

pmreorder_create_store_log $DIR/testfile "$PMEMCHECK_CMD"
pmreorder_expect_success ReorderReverseAccumulative \
	"pmem_memset_persist=NoReorderNoCheck" \
	"$PMREORDER_CMD"

check

pass
