#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_list_insert/TEST0 -- unit test for list_insert
#
# Adding item to list after the first element
#

. ../unittest/unittest.sh

require_test_type medium
require_build_type debug

setup

create_holey_file 1M $DIR/testfile

expect_normal_exit ../obj_list/obj_list$EXESUFFIX $DIR/testfile\
	i:0:0 P:2 R:2\
	i:0:0 P:2 R:2\
	i:0:0 P:2 R:2\
	i:0:0 P:2 R:2

check

pass
