# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016, Intel Corporation

#
# src/test/obj_rpmem_heap_interrupt/Makefile -- build obj_rpmem_heap_interrupt
#    test
#
SCP_TO_REMOTE_NODES = y
SCP_TARGET = obj_heap_interrupt
SCP_SRC_DIR = ../obj_heap_interrupt

include ../obj_heap_interrupt/Makefile.inc
