# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2014-2016, Intel Corporation
#
# Makefile -- Makefile for ddmap tool
#

TOP = ../../../..

TARGET = ddmap

OBJS = ddmap.o

LIBPMEM=y
TOOLS_COMMON=y
LIBPMEMBLK_PRIV=btt_info_convert2h

include $(TOP)/src/tools/Makefile.inc
