# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2014-2023, Intel Corporation
#
# Makefile -- Makefile for ddmap tool
#

TOP = ../../../..

TARGET = ddmap

OBJS = ddmap.o

LIBPMEM=y
TOOLS_COMMON=y
TOOLS_PMEMPOOL_COMMON=y

include $(TOP)/src/tools/Makefile.inc
