# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_pool/Makefile -- build obj_pool unit test
#
TARGET = obj_pool
OBJS = obj_pool.o

LIBPMEMOBJ=y

include ../Makefile.inc
