#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_pool/TEST28 -- unit test for pmemobj_open
#

. ../unittest/unittest.sh

require_test_type medium

setup
umask 0

#
# TEST28 existing file, file size >= min required size
#        layout matches the value from pool header
#
expect_normal_exit ./obj_pool$EXESUFFIX c $DIR/testfile "test" 20 0640

expect_normal_exit ./obj_pool$EXESUFFIX o $DIR/testfile "test"

check

pass
