#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018-2019, Intel Corporation

#
# src/test/obj_pool/TEST31 -- unit test for pmemobj_open
#

. $UNITTEST_SH

require_fs_type any
require_test_type medium

setup
umask 0

#
# TEST31 existing file, file size > min required size, layout is NULL
#        (valid pool header), reopen after failure
#
expect_normal_exit ./obj_pool$EXESUFFIX c $DIR/testfile NULL 20 0640

expect_normal_exit ./obj_pool$EXESUFFIX f $DIR/testfile NULL

check

pass
