#!/bin/bash -e
#
# Copyright 2017, Intel Corporation
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in
#       the documentation and/or other materials provided with the
#       distribution.
#
#     * Neither the name of the copyright holder nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

#
# src/test/obj_pool/TEST31 -- unit test for obj poolsets with unicode
#
export UNITTEST_NAME=obj_pool/TEST31
export UNITTEST_NUM=31

# standard unit test setup
. ../unittest/unittest.sh

require_test_type medium

require_fs_type non-pmem

POOLSET=testsetㅓㅹ
LAYOUT=⮓ⱙ

setup

create_poolset $DIR/$POOLSET 8M:$DIR/tesⰄfile:z 8M:$DIR/testfile⮸:z \
	r 24M:$DIR/testfileⰊ:z r 8M:$DIR/testfile⮌:z 8M:$DIR/testfile⭙:z

expect_normal_exit $PMEMPOOL$EXESUFFIX create --layout=$LAYOUT obj $DIR/$POOLSET

expect_normal_exit ./obj_pool$EXESUFFIX o $DIR/$POOLSET $LAYOUT

check

pass
