#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_pool/TEST13 -- unit test for pmemobj_create
#

. ../unittest/unittest.sh

require_test_type medium

setup
umask 0

#
# TEST13 non-existing file, poolsize >= min required size
#        layout is empty string
#
expect_normal_exit ./obj_pool$EXESUFFIX c $DIR/testfile EMPTY 20 0600

check_files $DIR/testfile

check

pass
