#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2023, Intel Corporation

#
# src/test/obj_pool/TEST20 -- unit test for pmemobj_open
#

. ../unittest/unittest.sh

require_test_type medium
set_test_labels fault_injection

setup
umask 0

#
# TEST20 non-existing file, layout is NULL
#
expect_normal_exit ./obj_pool$EXESUFFIX o $DIR/testfile NULL

check

pass
