#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_pool/TEST9 -- unit test for pmemobj_create
#

. ../unittest/unittest.sh

require_test_type medium

setup
umask 0

#
# TEST9 non-existing file, poolsize < min required size
#
expect_normal_exit ./obj_pool$EXESUFFIX c $DIR/testfile "test" 1 0640

check_no_files $DIR/testfile

check

pass
