#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018-2019, Intel Corporation

#
# src/test/obj_pool/TEST16 -- unit test for pmemobj_create
#

. ../unittest/unittest.sh

require_test_type medium

setup

# non-existing file, layout length == PMEMOBJ_MAX_LAYOUT, poolsize > 0
LAYOUT=$(printf 'x%.0s' {1..1023})

expect_normal_exit ./obj_pool$EXESUFFIX c $DIR/testfile $LAYOUT 20 0600

check_files $DIR/testfile

check

pass
