#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_pool/TEST4 -- unit test for pmemobj_create
#

. $UNITTEST_SH

require_test_type medium

setup
umask 0

touch $DIR/testfile
chmod 0640 $DIR/testfile

#
# TEST4 existing file, file length < min required size, poolsize == 0
#
expect_normal_exit ./obj_pool$EXESUFFIX c $DIR/testfile "test" 0 0640

check_files $DIR/testfile

check

pass
