#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_pool/TEST22 -- unit test for pmemobj_open
#

. $UNITTEST_SH

require_test_type medium

setup
umask 0

#
# TEST22 existing file, file size < min required size, layout is NULL
#        (valid pool header)
#
expect_normal_exit ./obj_pool$EXESUFFIX c $DIR/testfile NULL 20 0640
truncate -s 1M $DIR/testfile

expect_normal_exit ./obj_pool$EXESUFFIX o $DIR/testfile NULL

check

pass
