# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2020, Intel Corporation
#

#
# src/test/obj_defrag_advanced/Makefile -- build obj_defrag_advanced test
#
TARGET = obj_defrag_advanced
OBJS = vgraph.o pgraph.o obj_defrag_advanced.o

LIBPMEMOBJ=y

include ../Makefile.inc

CFLAGS += -DDEBUG
