# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2018, Intel Corporation

#
# src/test/pmem_valgr_simple/Makefile -- build pmem_valgr_simple unit test
#

TARGET = pmem_valgr_simple
OBJS = pmem_valgr_simple.o

LIBPMEM=y

include ../Makefile.inc
