#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/pmem_valgr_simple/TEST0 -- unit test for pmem_valgr_simple
#

. $UNITTEST_SH

require_test_type medium

require_fs_type pmem non-pmem
configure_valgrind pmemcheck force-enable
export VALGRIND_OPTS="--mult-stores=yes --indiff=20"
setup

truncate -s 4M $DIR/testfile1

expect_normal_exit ./pmem_valgr_simple$EXESUFFIX\
  $DIR/testfile1 60 8

check

pass
