# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/libpmempool_include/Makefile -- compilation test for libpmempool
#
TARGET = libpmempool_include
OBJS = libpmempool_include.o

LIBPMEMPOOL=y

include ../Makefile.inc
