# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_pool_lookup/Makefile -- build obj_pool_lookup unit test
#

TARGET = obj_pool_lookup
OBJS = obj_pool_lookup.o

LIBPMEMOBJ=y

include ../Makefile.inc
