#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_pool_lookup/TEST0 -- unit test for pmemobj_pool
#

. $UNITTEST_SH

require_test_type medium

require_fs_type any

setup

expect_normal_exit ./obj_pool_lookup$EXESUFFIX $DIR 9

pass
