# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_first_next/Makefile -- build obj_first_next unit test
#

TARGET = obj_first_next
OBJS = obj_first_next.o

LIBPMEMOBJ=y

include ../Makefile.inc
