# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016, Intel Corporation

#
# src/test/pmempool_sync_remote/Makefile -- build unittest for pmempool
# sync with remote replication
#
SCP_TO_REMOTE_NODES=y

include ../Makefile.inc
