#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2017-2019, Intel Corporation
#
#
# pmempool_sync_remote/TEST8 -- a test for pmempool sync with the SINGLEHDR option
#                               and a remote replica
#
# case: damaged local master replica
#

. ../unittest/unittest.sh

require_test_type	medium
require_fs_type		any

. common.sh

# Create poolset files
create_poolset $DIR/pool.set \
	O SINGLEHDR \
	10M:${NODE_DIR[1]}part00:x \
	10M:${NODE_DIR[1]}part01:x \
        m \
	${NODE_ADDR[0]}:remote.set

create_poolset $DIR/remote.set \
	O SINGLEHDR \
	21M:${NODE_DIR[0]}partr00:x

# CLI script for writing some data hitting all the parts
WRITE_SCRIPT=write_data
cat << EOF > $DIR/$WRITE_SCRIPT
pmemobj_root 15M
str_root_copy 0 TestOK111
str_root_copy 10M TestOK222
EOF

# CLI script for reading 9 characters from all the parts
READ_SCRIPT=read_data
cat << EOF > $DIR/$READ_SCRIPT
str_root_print 0 9
str_root_print 10M 9
EOF

copy_files_to_node 1 ${NODE_DIR[1]} $DIR/pool.set
copy_files_to_node 0 ${NODE_DIR[0]} $DIR/remote.set
copy_files_to_node 1 ${NODE_DIR[1]} $DIR/$WRITE_SCRIPT
copy_files_to_node 1 ${NODE_DIR[1]} $DIR/$READ_SCRIPT

expect_normal_exit run_on_node 1 ../pmempool rm -sf ${NODE_DIR[1]}pool.set
expect_normal_exit run_on_node 1 ../pmempool create obj ${NODE_DIR[1]}pool.set
check_files_on_node 1 pool.set part00 $WRITE_SCRIPT $READ_SCRIPT
check_files_on_node 0 remote.set partr00
exec_pmemobjcli_script 1 ${NODE_DIR[1]}$WRITE_SCRIPT ${NODE_DIR[1]}pool.set /dev/null
exec_pmemobjcli_script 1 ${NODE_DIR[1]}$READ_SCRIPT ${NODE_DIR[1]}pool.set before.data.log
dump_info_log 1 0 ${NODE_DIR[1]}pool.set before.0.log
dump_info_log_remote 0 ${NODE_DIR[0]}remote.set before.r.log

expect_normal_exit run_on_node 1 rm -f ${NODE_DIR[1]}part00
expect_normal_exit run_on_node 1 rm -f ${NODE_DIR[1]}part01
expect_normal_exit run_on_node 1 ../pmempool sync ${NODE_DIR[1]}pool.set

exec_pmemobjcli_script 1 ${NODE_DIR[1]}$READ_SCRIPT ${NODE_DIR[1]}pool.set after.data.log
dump_info_log 1 0 ${NODE_DIR[1]}pool.set after.0.log
dump_info_log_remote 0 ${NODE_DIR[0]}remote.set after.r.log

diff_log 1 before.0.log after.0.log
diff_log 0 before.r.log after.r.log
diff_log 1 before.data.log after.data.log

pass
