#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation
#
#
# pmempool_sync_remote/TEST1 -- pmempool sync with remote replication
#

. $UNITTEST_SH

require_test_type medium
require_fs_type any

. common.sh

configure_poolsets 1 1

dump_info_log 1 1 ${NODE_DIR[1]}$POOLSET_LOCAL before.1.log

expect_normal_exit run_on_node 1 rm ${NODE_DIR[1]}pool.part.1
expect_normal_exit run_on_node 1 ../pmemspoil ${NODE_DIR[1]}pool.0.part.1 pool_hdr.checksum=0
expect_normal_exit run_on_node 1 ../pmempool sync ${NODE_DIR[1]}$POOLSET_LOCAL
dump_info_log 1 1 ${NODE_DIR[1]}$POOLSET_LOCAL after.1.1.log

diff_log 1 before.1.log after.1.1.log

expect_normal_exit run_on_node 1 ../pmempool sync ${NODE_DIR[1]}$POOLSET_LOCAL

pass
