# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2017, Intel Corporation

#
# examples/libpmemobj/list_map/Makefile -- build the list map example
#
LIBRARIES = skiplist_map

LIBS = -lpmemobj

include ../../Makefile.inc

libskiplist_map.o: skiplist_map.o
