.TH "pmempool\-convert" "1" "" "" ""
.SS NAME
\f[B]pmempool\-convert\f[] \- Convert pool files from old layout
versions to the newest one.
.SS SYNOPSIS
.IP
.nf
\f[C]
pmempool\ convert\ <file>
\f[]
.fi
.SS DESCRIPTION
.PP
The \f[B]pmempool\f[] invoked with the \f[C]convert\f[] command performs
a conversion of the specified pool to the newest layout supported by
this tool.
Currently only \f[B]libpmemobj\f[](3) pools are supported.
It is advised to have a backup of the pool before conversion.
The conversion process is not fail\-safe \- power interruption may
damage the pool.
.SS EXAMPLES
.PP
\f[C]pmempool\ convert\ pool.obj\f[]
.PP
Updates pool.obj to the latest layout version.
.SS SEE ALSO
.PP
\f[B]pmempool\f[](1), \f[B]pmempool\-info\f[](1), \f[B]libpmemobj\f[](3)
.SS PMEMPOOL
.PP
Part of the \f[B]pmempool\f[](1) suite.
