#!/usr/bin/env bash
#
# Copyright 2016-2018, Intel Corporation
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in
#       the documentation and/or other materials provided with the
#       distribution.
#
#     * Neither the name of the copyright holder nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
#
# rpmemd_config/TEST2 -- test for rpmemd invalid config file
#

. ../unittest/unittest.sh

require_test_type medium

require_fs_type any

setup

RPMEMD=./rpmemd_config$EXESUFFIX

OUT=stdout${UNITTEST_NUM}.log
OUT_TEMP=stdout${UNITTEST_NUM}_temp.log
rm -rf $OUT $OUT_TEMP

CONFIG=$DIR/in${UNITTEST_NUM}.conf

INVALID_PATH="  \t\t  \t\t"
INVALID_FLAG=invalid
INVALID_ENUM=Invalid

function check_config {
	echo -e $1 > $CONFIG
	expect_normal_exit $RPMEMD -c $CONFIG 1>> $OUT_TEMP 2>&1
	expect_normal_exit $RPMEMD --config $CONFIG 1>> $OUT_TEMP 2>&1
}

check_config "; invalid comment format"
check_config "dir=$INVALID_PATH# invalid dir path"
check_config "log-file=$INVALID_PATH # invalid log-file path"
check_config "log-level=$INVALID_ENUM # invalid log-level"
check_config "persist-apm=$INVALID_FLAG # invalid persist-apm value"
check_config "persist-general=$INVALID_FLAG # invalid persist-general value"
check_config "use-syslog=$INVALID_FLAG # invalid use-syslog value"

$GREP -v START $OUT_TEMP > $OUT

check

pass
