#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation
#
#
# rpmemd_config/TEST2 -- test for rpmemd invalid config file
#

. ../unittest/unittest.sh

require_test_type medium
require_build_type debug
require_fs_type any

setup

RPMEMD=./rpmemd_config$EXESUFFIX

OUT=stdout${UNITTEST_NUM}.log
OUT_TEMP=stdout${UNITTEST_NUM}_temp.log
rm -f $OUT $OUT_TEMP

CONFIG=$DIR/in${UNITTEST_NUM}.conf

INVALID_PATH="  \t\t  \t\t"
INVALID_FLAG=invalid
INVALID_ENUM=Invalid

function check_config {
	echo -e "$1" > $CONFIG
	expect_normal_exit $RPMEMD -c $CONFIG 1>> $OUT_TEMP 2>&1
	expect_normal_exit $RPMEMD --config $CONFIG 1>> $OUT_TEMP 2>&1
}

check_config "; invalid comment format"
check_config "dir=$INVALID_PATH# invalid dir path"
check_config "log-file=$INVALID_PATH # invalid log-file path"
check_config "log-level=$INVALID_ENUM # invalid log-level"
check_config "persist-apm=$INVALID_FLAG # invalid persist-apm value"
check_config "persist-general=$INVALID_FLAG # invalid persist-general value"
check_config "use-syslog=$INVALID_FLAG # invalid use-syslog value"

$GREP -v START $OUT_TEMP > $OUT

check

pass
