#!/usr/bin/env bash
#
# Copyright 2016-2018, Intel Corporation
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in
#       the documentation and/or other materials provided with the
#       distribution.
#
#     * Neither the name of the copyright holder nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
#
# rpmemd_config/TEST0 -- test for rpmemd default config and cl arguments
#

. ../unittest/unittest.sh

require_test_type medium

require_fs_type any

setup

RPMEMD=./rpmemd_config$EXESUFFIX

OUT=stdout${UNITTEST_NUM}.log
LOG=out${UNITTEST_NUM}.log
LOG_TEMP=out${UNITTEST_NUM}_temp.log
rm -rf $OUT $LOG $LOG_TEMP

EMPTY_CONFIG=in${UNITTEST_NUM}.conf
INVALID_CONFIG=$DIR/invalid.conf

# use empty config to prevent loading config file from default location
# which may have nondefault configuration
expect_normal_exit $RPMEMD -c $EMPTY_CONFIG 1>> $OUT 2>&1
cat $LOG >> $LOG_TEMP

expect_normal_exit $RPMEMD -V 1>> $OUT 2>&1
cat $LOG >> $LOG_TEMP

expect_normal_exit $RPMEMD --version 1>> $OUT 2>&1
cat $LOG >> $LOG_TEMP

expect_normal_exit $RPMEMD -h 1>> $OUT 2>&1
cat $LOG >> $LOG_TEMP

expect_normal_exit $RPMEMD --help 1>> $OUT 2>&1
cat $LOG >> $LOG_TEMP

expect_normal_exit $RPMEMD -c $EMPTY_CONFIG 1>> $OUT 2>&1
cat $LOG >> $LOG_TEMP

expect_normal_exit $RPMEMD --config $EMPTY_CONFIG 1>> $OUT 2>&1
cat $LOG >> $LOG_TEMP

expect_normal_exit $RPMEMD -c $INVALID_CONFIG 1>> $OUT 2>&1
cat $LOG >> $LOG_TEMP

expect_normal_exit $RPMEMD --config $INVALID_CONFIG 1>> $OUT 2>&1
cat $LOG >> $LOG_TEMP

$GREP -v rpmemd_config $LOG_TEMP > $LOG

check

pass
