#!/bin/bash -e
#
# Copyright 2016, Intel Corporation
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in
#       the documentation and/or other materials provided with the
#       distribution.
#
#     * Neither the name of the copyright holder nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
#
# rpmemd_config/TEST3 -- test for rpmemd config overwrite
#
export UNITTEST_NAME=rpmemd_config/TEST3
export UNITTEST_NUM=3

. ../unittest/unittest.sh

require_fs_type any

setup

RPMEMD=./rpmemd_config

STDOUT=stdout${UNITTEST_NUM}.log
rm -rf $STDOUT && touch $STDOUT

CONFIG=$DIR/in${UNITTEST_NUM}.conf
touch $CONFIG

FILE_MAGIC=67
FILE_LOG_LEVEL=warn
CL_MAGIC=76
CL_LOG_LEVEL=notice

cat << EOF >> $CONFIG
pid-file=/nondefault/pid/file/path # nondefault pid-file path
log-file=/nondefault/log/file/path # nondefault log-file path
poolset-dir=/nondefault/dir/path # nondefault dir path
enable-create=no # nondefault enable-create value
enable-remove=no # nondefault enable-remove value
persist-apm=no # nondefault persist-apm value
persist-general=no # nondefault persist-general value
provider-sockets=no # nondefault provider-sockets value
provider-verbs=no # nondefault provider-verbs value
use-syslog=no # nondefault use-syslog value
verify-pool-sets=no # nondefault verify-pool-sets value
port=$FILE_MAGIC # nondefault port value
max-lanes=$FILE_MAGIC # nondefault max-lanes
log-level=$FILE_LOG_LEVEL # nondefault log-level
EOF

expect_normal_exit $RPMEMD$EXESUFFIX -c $CONFIG 1>> $STDOUT
expect_normal_exit $RPMEMD$EXESUFFIX -c $CONFIG\
	--pid-file=/cl/pid/file/path\
	--log-file=/cl/log/file/path\
	--poolset-dir=/cl/dir/path\
	--enable-create\
	--enable-remove\
	--foreground\
	--persist-apm\
	--persist-general\
	--provider-sockets\
	--provider-verbs\
	--use-syslog\
	--verify-pool-sets\
	--port=$CL_MAGIC\
	--max-lanes=$CL_MAGIC\
	--log-level=$CL_LOG_LEVEL\
	1>> $STDOUT

check

pass
