# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2017-2019, Intel Corporation

#
# src/test/obj_action/Makefile -- build obj_action test
#
TARGET = obj_action
OBJS = obj_action.o

LIBPMEMOBJ=y

include ../Makefile.inc
