#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2017-2019, Intel Corporation

#
# src/test/obj_action/TEST0 -- unit test (short) for obj_action
#

. $UNITTEST_SH

require_test_type short
require_fs_type any

# TEST1 runs valgrind memcheck
configure_valgrind memcheck force-disable

# TEST2 runs valgrind pmemcheck
configure_valgrind pmemcheck force-disable

setup

export PMEM_IS_PMEM_FORCE=1
export PMEMOBJ_LOG_LEVEL=1

expect_normal_exit ./obj_action$EXESUFFIX $DIR/testfile

pass
