#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2017-2019, Intel Corporation

#
# src/test/obj_action/TEST1 -- unit test (memcheck) for obj_action
#

. ../unittest/unittest.sh

require_test_type medium
require_build_type debug
configure_valgrind memcheck force-enable

setup

export PMEM_IS_PMEM_FORCE=1
export PMEMOBJ_LOG_LEVEL=1

expect_normal_exit ./obj_action$EXESUFFIX $DIR/testfile

check

pass
