#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018-2019, Intel Corporation

#
# src/test/obj_action/TEST2 -- unit test (pmemcheck) for obj_action
#

. ../unittest/unittest.sh

require_test_type medium
require_fs_type any
require_build_type debug

require_valgrind 3.12
configure_valgrind pmemcheck force-enable

setup

export PMEM_IS_PMEM_FORCE=1
export PMEMOBJ_LOG_LEVEL=1

expect_normal_exit ./obj_action$EXESUFFIX $DIR/testfile

check

pass
