# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/util_poolset_parse/Makefile -- build util_poolset_parse unit test
#
TARGET = util_poolset_parse
OBJS = util_poolset_parse.o

LIBPMEMCOMMON=y

include ../Makefile.inc
