#!/usr/bin/env bash
#
# Copyright 2018-2019, Intel Corporation
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in
#       the documentation and/or other materials provided with the
#       distribution.
#
#     * Neither the name of the copyright holder nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

#
# src/test/util_poolset_parse/TEST4 -- unit test for parsing a pool set file
#
# Duplicate directories
#

# standard unit test setup
. ../unittest/unittest.sh

require_test_type medium
require_build_type debug
require_fs_type any

setup

export PARSER_LOG_LEVEL=4
export PARSER_LOG_FILE=./parser$UNITTEST_NUM.log

RESVSIZE=$((260 * 1024 * 1024)) # 264MiB (base part + 2 extends)
MIN_POOL=$((128 * 1024 * 1024)) # 128MiB
export TEST_LOG_LEVEL=4
export TEST_LOG_FILE=./test$UNITTEST_NUM.log

# prepare pool sets
create_poolset $DIR/testset1\
	$RESVSIZE:$DIR/testset11:d $RESVSIZE:$DIR/testset11:d\
	O SINGLEHDR # fail
create_poolset $DIR/testset2\
	$RESVSIZE:$DIR/testset21:d R $RESVSIZE:$DIR/testset21:d\
	O SINGLEHDR # fail

POOLSETS="$DIR/testset1 $DIR/testset2"

expect_normal_exit ./util_poolset_parse$EXESUFFIX t $POOLSETS

$GREP -e "<[14]>.*\[.*util_parse_add_directory\]" ./parser$UNITTEST_NUM.log | \
	sed -e "s/^.*util_parse_add_directory][ ]*//g" > grep$UNITTEST_NUM.log

check

pass
