# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_oid_thread/Makefile -- build obj_oid_thread unit test
#
TARGET = obj_oid_thread
OBJS = obj_oid_thread.o

LIBPMEMOBJ=y

include ../Makefile.inc

INCS += -I../../libpmemobj/
