#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_oid_thread/TEST0 -- unit test for pmemobj_oid
#

. $UNITTEST_SH

require_fs_type any
require_test_type medium

setup

expect_normal_exit ./obj_oid_thread$EXESUFFIX $DIR 9

pass
