# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2021, Intel Corporation

#
# src/test/ex_libpmemset/Makefile -- build ex_libpmemset unittest
#

all: $(EXAMPLES)
	$(MAKE) -C $(EX_LIBPMEMSET)

include ../Makefile.inc

EXAMPLES=$(EX_LIBPMEMSET)/basic
