# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2014-2019, Intel Corporation

#
# src/test/log_basic/Makefile -- build log_basic unit test
#
TARGET = log_basic
OBJS = log_basic.o

LIBPMEMLOG=y

include ../Makefile.inc
