#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/log_basic/TEST6 -- unit test for:
# - pmemlog_nbyte
# - pmemlog_check
# - pmemlog_open
# - pmemlog_close
#

. $UNITTEST_SH

require_test_type medium

setup

create_poolset $DIR/testset1 2M:$DIR/testfile1:x 2M:$DIR/testfile2:x

expect_normal_exit ./log_basic$EXESUFFIX $DIR/testset1 c n l h

check_pool $DIR/testset1

check

pass
