#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2017-2019, Intel Corporation

#
# src/test/log_basic/TEST8 -- unit test for:
# - pmemlog_append
# and:
# - pmemlog_nbyte
# - pmemlog_tell
# - pmemlog_walk
# - pmemlog_rewind
# in case of non-empty pool and
# - pmemlog_check
# - pmemlog_open
# - pmemlog_close
#
# Same as TEST1, but run on a pool set that spans two Device DAX devices
# with 4K alignment.
#

. $UNITTEST_SH

require_test_type medium
require_fs_type any
require_dax_device_alignments 4096 4096

setup

dax_device_zero

create_poolset $DIR/testset AUTO:${DEVICE_DAX_PATH[0]} AUTO:${DEVICE_DAX_PATH[1]}

expect_normal_exit ./log_basic$EXESUFFIX $DIR/testset c a n t w r t w l h

check_pool $DIR/testset

pass
