#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/log_basic/TEST5 -- unit test for:
# - pmemlog_nbyte
# - pmemlog_check
# - pmemlog_open
# - pmemlog_close
#

. ../unittest/unittest.sh

require_test_type medium

setup

export PMEMLOG_LOG_LEVEL=10

create_poolset $DIR/testset1 2M:$DIR/testfile1:x

expect_normal_exit ./log_basic$EXESUFFIX $DIR/testset1 c n l h

check_pool $DIR/testset1

check

pass
