#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2017-2019, Intel Corporation

#
# src/test/log_basic/TEST9 -- unit test for:
# - pmemlog_append
# and:
# - pmemlog_nbyte
# - pmemlog_tell
# - pmemlog_walk
# - pmemlog_rewind
# in case of non-empty pool and
# - pmemlog_check
# - pmemlog_open
# - pmemlog_close
#
# Same as TEST1, but run on a pool set that spans two Device DAX devices
# with 2M alignment. Expected failure, as 2M alignment is not supported
# if SINGLEHDR option is not specified.
#

. ../unittest/unittest.sh

require_test_type medium
require_fs_type any
require_dax_device_alignments 2097152 2097152 # 2MiB

setup

dax_device_zero

create_poolset $DIR/testset AUTO:${DEVICE_DAX_PATH[0]} AUTO:${DEVICE_DAX_PATH[1]}

expect_abnormal_exit ./log_basic$EXESUFFIX $DIR/testset c a n t w r t w l h

pass
