#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/log_basic/TEST7 -- unit test for:
# - pmemlog_append
# and:
# - pmemlog_nbyte
# - pmemlog_tell
# - pmemlog_walk
# - pmemlog_rewind
# in case of non-empty pool and
# - pmemlog_check
# - pmemlog_open
# - pmemlog_close
#
# Same as TEST1, but run on a single Device DAX device.
#

. ../unittest/unittest.sh

require_test_type medium
require_dax_devices 1
require_fs_type any

setup

dax_device_zero

expect_normal_exit ./log_basic$EXESUFFIX $DEVICE_DAX_PATH c a n t w r t w l h

check_pool $DEVICE_DAX_PATH

pass
