# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016, Intel Corporation

#
# src/test/util_parse_size/Makefile -- check parsing results
#
TARGET = util_parse_size
OBJS = util_parse_size.o

LIBPMEMCOMMON=y
include ../Makefile.inc
