#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2014-2023, Intel Corporation
#
#
# pmempool_create/TEST2 -- test for creating pools of specified size
#

. ../unittest/unittest.sh

require_test_type medium

require_fs_type pmem non-pmem

setup

POOL=$DIR/file.pool
SIZE=$(((1024 + 512) * 1024 * 1024))

require_free_space $SIZE

# PMEMLOG
rm -f $POOL
expect_normal_exit $PMEMPOOL$EXESUFFIX create -s $SIZE log $POOL
check_file $POOL
check_signature PMEMLOG $POOL
check_size $SIZE $POOL

#PMEMOBJ
rm -f $POOL
expect_normal_exit $PMEMPOOL$EXESUFFIX create -s $SIZE obj $POOL
check_file $POOL
check_signature PMEMOBJ $POOL
check_layout "" $POOL
check_size $SIZE $POOL

pass
