#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2014-2019, Intel Corporation
#
#
# pmempool_create/TEST7 -- test for pmempool create command with default pool size
#

. $UNITTEST_SH

require_test_type medium

require_fs_type pmem non-pmem
require_build_type nondebug debug

configure_valgrind memcheck force-enable $PMDK_LIB_PATH/libpmemobj.so
export PMEMOBJ_VG_CHECK_UNDEF=1

setup

POOL=$DIR/file.pool

expect_normal_exit $PMEMPOOL create --layout=LAYOUT_NAME$SUFFIX obj $POOL
check_file $POOL
check_signature PMEMOBJ $POOL
check_layout LAYOUT_NAME$SUFFIX $POOL

pass
