#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2014-2018, Intel Corporation
#
#
# pmempool_create/TEST5 -- test for pmempool create for checking bsize argument
#

. ../unittest/unittest.sh

require_test_type medium

require_fs_type pmem non-pmem

setup

POOL=$DIR/file.pool
POOL2=$DIR/file.pool2

# PMEMBLK
expect_abnormal_exit $PMEMPOOL$EXESUFFIX create blk $POOL 2> err5.log

expect_abnormal_exit $PMEMPOOL$EXESUFFIX create blk 4294967296 $POOL2 2>> err5.log

check

pass
