# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2016, Intel Corporation

#
# examples/libpmemobj/string_store_tx/Makefile -- build the intro 2 example
#
PROGS = writer reader

LIBS = -lpmemobj -lpmem -pthread

include ../../Makefile.inc

writer: writer.o
reader: reader.o
