#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_direct/TEST0 -- unit test for direct
#

. ../unittest/unittest.sh

require_test_type medium

require_fs_type any

setup

expect_normal_exit ./obj_direct$EXESUFFIX $DIR 9

pass
