# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016, Intel Corporation

#
# src/test/obj_rpmem_heap_state/Makefile -- build obj_rpmem_heap_state test
#
SCP_TO_REMOTE_NODES = y
SCP_TARGET = obj_heap_state
SCP_SRC_DIR = ../obj_heap_state

include ../obj_heap_state/Makefile.inc
