#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

. ../unittest/unittest.sh

require_test_type medium

exclude_ppc64

setup

require_nodes 2

require_node_libfabric 0 $RPMEM_PROVIDER
require_node_libfabric 1 $RPMEM_PROVIDER

init_rpmem_on_node 1 0

# binary for this test
EXE=obj_heap_state

# define files and directories
TEST_SET_LOCAL="testset_local"
TEST_SET_REMOTE="testset_remote"

TEST_FILE_LOCAL="testfile_local"
TEST_FILE_REMOTE="testfile_remote"

rm_files_from_node 0 ${NODE_DIR[0]}$TEST_FILE_REMOTE
rm_files_from_node 1 "${NODE_DIR[1]}$TEST_FILE_LOCAL ${NODE_DIR[1]}${TEST_FILE_LOCAL}_replica"

# XXX: Make sum of all parts and replicas sizes equal
# create and upload poolset files
create_poolset $DIR/$TEST_SET_LOCAL 8M:${NODE_DIR[1]}/$TEST_FILE_LOCAL:x \
	r 9M:${NODE_DIR[1]}/${TEST_FILE_LOCAL}_replica \
	m ${NODE_ADDR[0]}:$TEST_SET_REMOTE
create_poolset $DIR/$TEST_SET_REMOTE 9M:${NODE_DIR[0]}/$TEST_FILE_REMOTE:x

copy_files_to_node 0 ${NODE_DIR[0]} $DIR/$TEST_SET_REMOTE
copy_files_to_node 1 ${NODE_DIR[1]} $DIR/$TEST_SET_LOCAL

PMEM_IS_PMEM_FORCE=1
export_vars_node 1 PMEM_IS_PMEM_FORCE

# execute test
expect_normal_exit run_on_node 1 ./$EXE$EXESUFFIX ${NODE_DIR[1]}$TEST_SET_LOCAL

check

# download pools and compare them
copy_files_from_node 0 $DIR ${NODE_DIR[0]}$TEST_FILE_REMOTE
copy_files_from_node 1 $DIR ${NODE_DIR[1]}$TEST_FILE_LOCAL ${NODE_DIR[1]}${TEST_FILE_LOCAL}_replica

compare_replicas "-soOaAb -l -Z -H -C" \
	$DIR/$TEST_FILE_LOCAL $DIR/$TEST_FILE_REMOTE > diff$UNITTEST_NUM.log

compare_replicas "-soOaAb -l -Z -H -C" \
	$DIR/${TEST_FILE_LOCAL}_replica $DIR/$TEST_FILE_REMOTE >> diff$UNITTEST_NUM.log

check_local

pass
