# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2017, Intel Corporation

#
# src/test/libpmempool_rm_remote/Makefile -- unit test for pmempool_rm
# with remote replica
#
SCP_TO_REMOTE_NODES = y
SCP_TARGET = libpmempool_rm
SCP_SRC_DIR = ../libpmempool_rm

include ../libpmempool_rm/Makefile.inc
