# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2017-2019, Intel Corporation

#
# src/test/obj_ctl_config/Makefile -- build obj_ctl_config test
#
TARGET = obj_ctl_config
OBJS = obj_ctl_config.o

LIBPMEMOBJ=y

include ../Makefile.inc
