#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2017-2019, Intel Corporation

export UNITTEST_NAME=obj_ctl_config/TEST1
export UNITTEST_NUM=100 # TEST0 poses as different test numbers

. ../unittest/unittest.sh

require_test_type short

setup

expect_normal_exit $PMEMPOOL$EXESUFFIX\
	create --layout obj_ctl_config obj $DIR/testfile

PMEMOBJ_CONF_FILE=""\
	expect_normal_exit ./obj_ctl_config$EXESUFFIX $DIR/testfile

pass
