# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_basic_integration/Makefile -- build obj_basic_integration test
#
TARGET = obj_basic_integration
OBJS = obj_basic_integration.o

LIBPMEMOBJ=y

include ../Makefile.inc
INCS += -I../../libpmemobj
