#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

. ../unittest/unittest.sh

require_test_type medium
require_dax_devices 1

# covered by TEST5
configure_valgrind memcheck force-disable

setup

dax_device_zero

expect_normal_exit ./obj_basic_integration$EXESUFFIX $DEVICE_DAX_PATH

pass
