#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

. $UNITTEST_SH

require_test_type medium
require_dax_devices 1

setup

dax_device_zero

create_poolset $DIR/testset1 AUTO:$DEVICE_DAX_PATH

expect_normal_exit ./obj_basic_integration$EXESUFFIX $DIR/testset1

pass
