#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

. ../unittest/unittest.sh

require_test_type medium
require_command $STRACE
require_dax_devices 1
require_no_asan

# covered by TEST5
configure_valgrind memcheck force-disable

setup

dax_device_zero

expect_normal_exit $STRACE -emsync -ostrace$UNITTEST_NUM.log \
	./obj_basic_integration$EXESUFFIX $DEVICE_DAX_PATH

check

pass
