#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

. $UNITTEST_SH

require_test_type medium
require_dax_devices 2

setup

dax_device_zero

create_poolset $DIR/testset1 \
	AUTO:${DEVICE_DAX_PATH[0]}:x \
	r \
	AUTO:${DEVICE_DAX_PATH[1]}:x

expect_normal_exit ./obj_basic_integration$EXESUFFIX $DIR/testset1

pass
