#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2017-2019, Intel Corporation

#
# src/test/obj_basic_integration/TEST13 -- basic integration tests for libpmemobj
#
# Same as TEST0, but run on a pool set that spans two Device DAX devices
# with 2M alignment. Expected success, as pool is created with SINGLEHDR option.
# if SINGLEHDR option is not specified.
#

. ../unittest/unittest.sh

require_test_type medium
require_dax_device_alignments 2097152 2097152 # 2MiB

setup

dax_device_zero

create_poolset $DIR/testset1 AUTO:${DEVICE_DAX_PATH[0]} AUTO:${DEVICE_DAX_PATH[1]} \
	O SINGLEHDR

expect_normal_exit ./obj_basic_integration$EXESUFFIX $DIR/testset1

pass
