#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

. $UNITTEST_SH

require_test_type medium

setup

create_poolset $DIR/testset1 8M:$DIR/testfile1:x 8M:$DIR/testfile2:x \
	r 16M:$DIR/testfile3:x

expect_normal_exit\
    ./obj_basic_integration$EXESUFFIX $DIR/testset1

check

pass
