# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_toid/Makefile -- build obj_toid unit test
#
TARGET = obj_toid
OBJS = obj_toid.o

LIBPMEMOBJ=y

include ../Makefile.inc
