# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2019, Intel Corporation

#
# src/test/obj_ctl_arenas/Makefile -- build obj_ctl_arenas test
#
TARGET = obj_ctl_arenas
OBJS = obj_ctl_arenas.o

LIBPMEMOBJ=y

include ../Makefile.inc
