#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2019, Intel Corporation

#
# src/test/obj_ctl_arenas/TEST6 --  mt test for arena allocation using ctl
#

. $UNITTEST_SH

require_test_type short
require_fs_type any
configure_valgrind drd force-enable

setup

expect_normal_exit ./obj_ctl_arenas$EXESUFFIX $DIR/testset1 a

pass
