#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2019, Intel Corporation

#
# src/test/obj_ctl_arenas/TEST3 -- unit test for POBJ_ARENA_ID flag
#

. ../unittest/unittest.sh

require_test_type medium
require_fs_type any
configure_valgrind drd force-enable

setup

expect_normal_exit ./obj_ctl_arenas$EXESUFFIX $DIR/testset1 f

pass
