#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2019, Intel Corporation

#
# src/test/obj_ctl_arenas/TEST2 -- unit test for create arenas using ctl
#

. ../unittest/unittest.sh

require_test_type short
require_fs_type any

setup

expect_normal_exit ./obj_ctl_arenas$EXESUFFIX $DIR/testset1 c

pass
