# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018, Intel Corporation

#
# src/test/pmempool_info_remote/Makefile -- build unittest for pmempool
# info with remote replicas
#
SCP_TO_REMOTE_NODES = y

include ../Makefile.inc
