#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018, Intel Corporation
#
#
# pmempool_feature/TEST1 -- unit test for CKSUM_2K
#

. ../unittest/unittest.sh

require_test_type medium
require_fs_type any

configure_valgrind force-disable

setup
. ../pmempool_feature/common.sh

pmempool_feature_remote_init
pmempool_feature_create_poolset "remote"
pmempool_feature_test_remote "CKSUM_2K"

check

pass
