# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018, Intel Corporation

#
# examples/pmreorder/Makefile -- build the pmreorder example
#

PROGS = pmreorder_list

LIBS = -lpmem -pthread

include ../Makefile.inc

pmreorder_list: pmreorder_list.o
