# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_check/Makefile -- build obj_check test
#
TARGET = obj_check
OBJS = obj_check.o

LIBPMEMOBJ=y
USE_PMEMSPOIL=y
USE_PMEMWRITE=y
USE_PMEMALLOC=y

include ../Makefile.inc

