#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_check/TEST2 -- unit test for pmemobj_check
#

. ../unittest/unittest.sh

require_test_type medium

setup

expect_normal_exit $PMEMPOOL$EXESUFFIX create obj $DIR/testfile
$PMEMSPOIL $DIR/testfile "pmemobj.layout=ERROR"
expect_normal_exit ./obj_check$EXESUFFIX $DIR/testfile

check

pass
