# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2019, Intel Corporation

#
# src/test/pmem2_compat/Makefile -- build pmem2_compat test
#
TARGET = pmem2_compat
OBJS = pmem2_compat.o

LIBPMEM=y
LIBPMEM2=y

include ../Makefile.inc
