# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_many_size_allocs/Makefile -- build obj_many_size_allocs test
#
TARGET = obj_many_size_allocs
OBJS = obj_many_size_allocs.o

LIBPMEMOBJ=internal-debug

include ../Makefile.inc
