#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

. ../unittest/unittest.sh

require_test_type long

setup

# limit number of emitted logs due to excessive log size
export PMEMOBJ_LOG_LEVEL=2

create_poolset $DIR/testset1 16M:$DIR/testfile1 16M:$DIR/testfile2

expect_normal_exit\
	./obj_many_size_allocs$EXESUFFIX $DIR/testset1

check

pass
