# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2014-2022, Intel Corporation
#
# Makefile -- Makefile for pmemspoil tool
#

TOP=../../../..

TARGET = pmemspoil

OBJS = spoil.o

LIBPMEM=y
TOOLS_COMMON=y
LIBPMEMBLK_PRIV=btt_info_convert2h

include $(TOP)/src/tools/Makefile.inc
