# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2017, Intel Corporation

#
# src/test/pmempool_transform_remote/Makefile -- build unit test for pmempool
# transform with remote replication
#
SCP_TO_REMOTE_NODES=y

include ../Makefile.inc
