#
# Copyright 2016, FUJITSU TECHNOLOGY SOLUTIONS GMBH
# Copyright 2016, Intel Corporation
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in
#       the documentation and/or other materials provided with the
#       distribution.
#
#     * Neither the name of the copyright holder nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

#
# ===========================================================================
#
#      Filename:  Makefile
#
#   Description:  build libart port to libpmemobj
#
#        Author:  Andreas Bluemle, Dieter Kasper
#                 Andreas.Bluemle.external@ts.fujitsu.com
#                 dieter.kasper@ts.fujitsu.com
#
#  Organization:  FUJITSU TECHNOLOGY SOLUTIONS GMBH
#
# ===========================================================================
#

PROGS = arttree
LIBRARIES = art

include ../../Makefile.inc

# LIBDIR = $(TOP_SRC)/debug
# CFLAGS += -O0 -finstrument-functions -finstrument-functions-exclude-function-list=_mm_set1_epi8,_mm_set_epi8,_mm_cmplt_epi8,_mm_loadu_si128,_mm_movemask_epi8,_mm_cmpeq_epi8

# EXTRA_CFLAGS += "-DUSE_VALGRIND -I/root/valgrind/include"

LIBDIR = $(TOP_SRC)/nondebug
CFLAGS += -O2

INCDIR += -I$(TOP_SRC)/common -I$(TOP_SRC)/libpmemobj
LIBS = -lpmemobj -pthread -lart 

$(PROGS): | $(DYNAMIC_LIBRARIES)
$(PROGS): LDFLAGS += -Wl,-rpath=. -L.
static: LDFLAGS += -Wl,-rpath=. -L. -pg
static: CFLAGS += -pg

libart.o: art.o

arttree: arttree.o

static: arttree.o libart.a ../../../nondebug/libpmemobj.a ../../../nondebug/libpmem.a
	$(LINKER) -o arttree-static $(LDFLAGS) $^  -pthread

pmemobj_debugger: pmemobj_debugger.o

clean:
	rm -f *.o arttree pmemobj_debugger libart.so libart.a
