# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2014-2023, Intel Corporation
#
# Makefile -- Makefile for pmemalloc tool
#

TOP=../../../..

TARGET = pmemobjcli

OBJS = pmemobjcli.o

LIBPMEM=y
LIBPMEMOBJ=y
TOOLS_COMMON=y
TOOLS_PMEMPOOL_COMMON=y
LIBPMEMBLK_PRIV=btt_info_convert2h

include $(TOP)/src/tools/Makefile.inc
