# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_memcheck/Makefile -- build obj_memcheck unit test
#
TARGET = obj_memcheck
OBJS = obj_memcheck.o

LIBPMEMOBJ=y

include ../Makefile.inc
