# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2021, Intel Corporation

#
# examples/libpmem2/ringbuf/Makefile -- build the ring buffer example
#
PROGS = ringbuf

LIBS = -lpmem2 -lpthread

include ../../Makefile.inc

ringbuf: ringbuf.o
