# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016, Intel Corporation

#
# src/test/libpmempool_map_flog/Makefile -- build libpmempool_map_flog unittest
#

include ../libpmempool_api/Makefile.inc
