#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2018, Intel Corporation
#
#
# libpmempool_map_flog/TEST0 -- test for checking map and flog
#

. ../unittest/unittest.sh

require_test_type medium

require_fs_type any

setup

POOL=$DIR/file.pool
LOG=out${UNITTEST_NUM}.log
LOG_TEMP=out${UNITTEST_NUM}_part.log
rm -f $LOG && touch $LOG
rm -f $LOG_TEMP && touch $LOG_TEMP
EXE=../libpmempool_api/libpmempool_test

declare -A map_err=(["Initial"]="0" ["Error"]="4"
	["Zeroed"]="8" ["Normal"]="C")

ent_val=2

for field in Zeroed Error Initial Normal;
do
	for((i=0;i<ent_val;i++));
	do
		spcmd="bttdevice.arena.btt_map(0)=0x${map_err["$field"]}000000${i}"

		expect_normal_exit $BTTCREATE $POOL
		echo ${field}: $spcmd >> $LOG_TEMP
		$PMEMSPOIL $POOL $spcmd

		expect_normal_exit $EXE$EXESUFFIX -r 1 -t btt -a 1 $POOL
		cat $LOG >> $LOG_TEMP
	done
done

mv $LOG_TEMP $LOG
check_file $POOL

check
pass
