#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2018, Intel Corporation
#
#
# libpmempool_map_flog/TEST3 -- test for checking map and flog
#

. $UNITTEST_SH

require_test_type medium

require_fs_type any

setup

POOL=$DIR/file.pool
LOG=out${UNITTEST_NUM}.log
LOG_TEMP=out${UNITTEST_NUM}_part.log
rm -f $LOG && touch $LOG
rm -f $LOG_TEMP && touch $LOG_TEMP
EXE=../libpmempool_api/libpmempool_test

ent_val=10

expect_normal_exit $BTTCREATE $POOL

for((i=0;i<ent_val;i++));
do
	spcmd="bttdevice.arena.btt_map(${i})=0xC000000${i}"
	echo $spcmd >> $LOG_TEMP
	$PMEMSPOIL $POOL $spcmd
done

spcmd="bttdevice.arena.btt_map(5)=0xC0000002"
echo $spcmd >> $LOG_TEMP
$PMEMSPOIL $POOL $spcmd

spcmd="bttdevice.arena.btt_map(6)=0xC0000002"
echo $spcmd >> $LOG_TEMP
$PMEMSPOIL $POOL $spcmd

spcmd="bttdevice.arena.btt_map(7)=0xC0000002"
echo $spcmd >> $LOG_TEMP
$PMEMSPOIL $POOL $spcmd

spcmd="bttdevice.arena.btt_map(10)=0xC0000002"
echo $spcmd >> $LOG_TEMP
$PMEMSPOIL $POOL $spcmd

spcmd="bttdevice.arena.btt_map(11)=0xC0000002"
echo $spcmd >> $LOG_TEMP
$PMEMSPOIL $POOL $spcmd

spcmd="bttdevice.arena.btt_map(12)=0xC0000003"
echo $spcmd >> $LOG_TEMP
$PMEMSPOIL $POOL $spcmd

expect_normal_exit $EXE$EXESUFFIX -r 1 -t btt -a 1 $POOL
cat $LOG >> $LOG_TEMP

expect_normal_exit $PMEMPOOL$EXESUFFIX info $POOL -f btt -m\
	| $GREP "error" >> $LOG_TEMP

mv $LOG_TEMP $LOG
check_file $POOL

check
pass
