# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/obj_locks/Makefile -- build obj_locks unit test
#
TARGET = obj_locks
OBJS = obj_locks.o

LIBPMEMOBJ=y

include ../Makefile.inc
