#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_locks/TEST1 -- unit test for pmemobj_mutex and pmemobj_rwlock
#

. $UNITTEST_SH

require_test_type medium

require_build_type debug
require_valgrind 3.10
configure_valgrind drd force-enable

setup

expect_normal_exit ./obj_locks$EXESUFFIX $DIR/testfile1

check

pass
