# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2014-2016, Intel Corporation

#
# src/test/pmem_is_pmem/Makefile -- build pmem_is_pmem unit test
#
TARGET = pmem_is_pmem
OBJS = pmem_is_pmem.o

LIBPMEM=y

include ../Makefile.inc
