# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018-2019, Intel Corporation

#
# src/test/obj_ctl_debug/Makefile -- build obj_ctl_debug test
#
TARGET = obj_ctl_debug
OBJS = obj_ctl_debug.o

LIBPMEMOBJ=y

include ../Makefile.inc
