#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018-2019, Intel Corporation

#
# src/test/obj_ctl_debug/TEST0 -- unit test (short) without memcheck and
#       and pmemcheck for ctl_debug
#

. ../unittest/unittest.sh

require_test_type short
require_fs_type any

# TEST1 runs valgrind memcheck
configure_valgrind memcheck force-disable

# TEST2 runs valgrind pmemcheck
configure_valgrind pmemcheck force-disable

setup

expect_normal_exit ./obj_ctl_debug$EXESUFFIX $DIR/testfile

pass
