# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/util_poolset_size/Makefile -- build util_poolset_size
#
#
TARGET = util_poolset_size
OBJS = util_poolset_size.o

LIBPMEMCOMMON=y

include ../Makefile.inc
