# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_tx_flow/Makefile -- build obj_tx_flow unit test
#
TARGET = obj_tx_flow
OBJS = obj_tx_flow.o

LIBPMEMOBJ=internal-debug

include ../Makefile.inc
