#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_tx_flow/TEST0 -- unit test for transaction flow
#

. $UNITTEST_SH

# this test verifies the correctness of the tx management functions only
configure_valgrind pmemcheck force-disable

require_test_type medium

setup

expect_normal_exit ./obj_tx_flow$EXESUFFIX f $DIR/testfile1

expect_normal_exit ./obj_tx_flow$EXESUFFIX t $DIR/testfile2

pass
