# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2016, Intel Corporation

#
# src/test/pmempool_info/Makefile -- build pmempool info unittest
#
USE_PMEMWRITE=y
USE_PMEMALLOC=y

include ../Makefile.inc
