#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018-2019, Intel Corporation
#
#
# pmempool_info/TEST26 -- test for info command
#

. ../unittest/unittest.sh

require_test_type medium

require_fs_type pmem non-pmem

setup

POOL=$DIR/file.pool
LOG=out${UNITTEST_NUM}.log

expect_normal_exit $PMEMPOOL$EXESUFFIX create --layout "pmempool$SUFFIX" obj\
  $POOL
expect_normal_exit $PMEMSPOIL $POOL \
				   "pool_hdr.shutdown_state.dirty=1 \
				   pool_hdr.shutdown_state.f:checksum_gen"
expect_normal_exit $PMEMPOOL$EXESUFFIX info $POOL >> $LOG

check

pass
