#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2018, Intel Corporation
#
#
# pmempool_info/TEST18 -- test for info command with device dax
#

. ../unittest/unittest.sh

require_test_type medium

require_dax_devices 1
require_fs_type any

setup

LOG=out${UNITTEST_NUM}.log

rm -f $LOG && touch $LOG

POOLSET=$DIR/testset1
create_poolset $POOLSET AUTO:$DEVICE_DAX_PATH

expect_normal_exit $PMEMPOOL$EXESUFFIX rm $DEVICE_DAX_PATH
expect_normal_exit $PMEMPOOL$EXESUFFIX create obj --layout pmempool$SUFFIX $POOLSET
expect_normal_exit $PMEMPOOL$EXESUFFIX info $POOLSET >> $LOG
expect_normal_exit $PMEMPOOL$EXESUFFIX info $DEVICE_DAX_PATH >> $LOG

check

pass
