#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2014-2018, Intel Corporation
#
#
# pmempool_info/TEST12 -- test for info command
#

. $UNITTEST_SH

require_test_type medium

setup

POOL=$DIR/file.pool
LOG=out${UNITTEST_NUM}.log
rm -f $LOG && touch $LOG

expect_normal_exit $PMEMPOOL$EXESUFFIX create --layout "pmempool$SUFFIX" obj $POOL
expect_normal_exit $PMEMALLOC$EXESUFFIX -o $((3*1024*1024)) -t 1 $POOL
expect_normal_exit $PMEMALLOC$EXESUFFIX -o 16 -t 2 $POOL
expect_normal_exit $PMEMALLOC$EXESUFFIX -c 777 -t 3 $POOL
expect_normal_exit $PMEMPOOL$EXESUFFIX info -O -E -a -A -H -Z -C -s $POOL >> $LOG

check

pass
