#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2014-2018, Intel Corporation
#
#
# pmempool_info/TEST15 -- test for info command
#

. ../unittest/unittest.sh

require_test_type medium

require_fs_type pmem non-pmem

setup

POOL=$DIR/file.pool
LOG=out${UNITTEST_NUM}.log
rm -f $LOG && touch $LOG

expect_normal_exit $PMEMPOOL$EXESUFFIX create --layout "pmempool$SUFFIX" obj $POOL
expect_normal_exit $PMEMPOOL$EXESUFFIX info -o -A -a $POOL >> $LOG
expect_normal_exit $PMEMALLOC$EXESUFFIX -r 1 $POOL
echo >> $LOG
expect_normal_exit $PMEMPOOL$EXESUFFIX info -o -A -a $POOL >> $LOG

check

pass
