#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2014-2018, Intel Corporation
#
#
# pmempool_info/TEST4 -- test for info command with statistics
#

. $UNITTEST_SH

require_test_type medium

require_fs_type pmem non-pmem

setup

POOL=$DIR/file.pool
LOG=out${UNITTEST_NUM}.log
rm -f $LOG && touch $LOG

expect_normal_exit $PMEMPOOL$EXESUFFIX create -w blk 512 $POOL
expect_normal_exit $PMEMPOOL$EXESUFFIX info -s $POOL >> $LOG

echo >> $LOG

rm -f $POOL
expect_normal_exit $PMEMPOOL$EXESUFFIX create log $POOL
expect_normal_exit $PMEMPOOL$EXESUFFIX info -s $POOL >> $LOG

check

pass
