# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016, Intel Corporation

#
# src/test/rpmem_proto/Makefile -- build rpmem_proto test
#

TARGET = rpmem_proto
OBJS = rpmem_proto.o

BUILD_STATIC_DEBUG=n
BUILD_STATIC_NONDEBUG=n

include ../Makefile.inc

INCS += -I../../rpmem_common
