#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/rpmem_obc/TEST0 -- unit test for rpmem_proto.h
#

. ../unittest/unittest.sh

require_test_type medium
require_build_type debug
require_fs_type none

setup

expect_normal_exit ./rpmem_proto$EXESUFFIX

pass
