# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/obj_ctl_alloc_class/Makefile -- build obj_ctl_alloc_class test
#
TARGET = obj_ctl_alloc_class
OBJS = obj_ctl_alloc_class.o

LIBPMEMOBJ=y

include ../Makefile.inc
