#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

. ../unittest/unittest.sh

require_test_type short
require_fs_type any
require_build_type debug

setup

expect_normal_exit ./obj_ctl_alloc_class$EXESUFFIX $DIR/testfile b

pass
