# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016, Intel Corporation

#
# examples/libpmempool/Makefile -- build the libpmempool examples
#

PROGS = manpage

LIBS = -lpmempool -pthread

include ../Makefile.inc

manpage: manpage.o
