#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_bucket/TEST0 -- unit test for obj_bucket interface
#

. ../unittest/unittest.sh

require_test_type medium

# this is a volatile state test
configure_valgrind pmemcheck force-disable

setup

expect_normal_exit ./obj_bucket$EXESUFFIX

pass
