# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2019, Intel Corporation

#
# src/test/obj_check_remote/Makefile -- build obj_check_remote test
#
TARGET = obj_check_remote
OBJS = obj_check_remote.o

LIBPMEMOBJ=y
SCP_TO_REMOTE_NODES = y

include ../Makefile.inc
