# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_tx_locks_abort/Makefile -- build obj_tx_locks_abort unit test
#
TARGET = obj_tx_locks_abort
OBJS = obj_tx_locks_abort.o

LIBPMEMOBJ=y

include ../Makefile.inc
