#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_tx_locks_abort/TEST0 -- unit test for transaction locks
#

. ../unittest/unittest.sh

require_test_type medium

setup

expect_normal_exit ./obj_tx_locks_abort$EXESUFFIX $DIR/testfile1

check

pass
