#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_tx_locks_abort/TEST1 -- unit test for transaction locks
#

. $UNITTEST_SH

require_test_type medium

unset PMEM_LOG_LEVEL
unset PMEM_LOG_FILE
unset PMEMOBJ_LOG_LEVEL
unset PMEMOBJ_LOG_FILE

require_fs_type any
require_build_type debug nondebug
require_valgrind 3.10
configure_valgrind drd force-enable
setup

expect_normal_exit ./obj_tx_locks_abort$EXESUFFIX $DIR/testfile1

check

pass
