#!/bin/sh
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2019, Intel Corporation

# check-manpages -- a tool to test against some manpage errors

MANS="$*"
[ -n "$MANS" ] || MANS="$(find doc -name '*.1' -o -name '*.3' -o -name '*.5' -o -name '*.7')"
[ -n "$MANS" ] || echo >&2 "No man pages given, and none found in doc/"

for m in $MANS; do
	if grep -q '^\.SH NAME' "$m"; then
		if ! lexgrog "$m" >/dev/null; then
			echo 2>&1 "lexgrog failed on $m"
		fi
	fi

	MANWIDTH=80 man --warnings -E UTF-8 -l -Tutf8 -Z "$m" >/dev/null
done
