#!/bin/bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2019-2023, Intel Corporation

# check-manpages -- a tool to test against some manpage errors

MANS="$*"
[ -n "$MANS" ] || MANS="$(find doc -name '*.1' -o -name '*.3' -o -name '*.5' -o -name '*.7')"
[ -n "$MANS" ] || { echo >&2 "No man pages given, and none found in doc/"; exit 1;}

for page in $MANS;do
	echo $page
done | xargs -P `nproc` -n1 -- utils/check-manpage
