#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/rpmemd_obc/TEST0 -- unit test for rpmemd_obc_process
#

. $UNITTEST_SH

require_test_type medium

require_fs_type none
require_build_type nondebug debug

setup

. setup.sh

expect_normal_exit run_on_node 1 ./rpmemd_obc$EXESUFFIX\
	client_bad_msg_hdr ${NODE_ADDR[0]}

pass
