#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_list_valgrind/TEST3 -- unit test for list module with valgrind
# pmemcheck tool
#

. ../unittest/unittest.sh

require_test_type medium

require_fs_type pmem non-pmem
require_build_type debug

configure_valgrind pmemcheck force-enable ../obj_list/obj_list
export VALGRIND_OPTS="--mult-stores=yes"
setup

create_holey_file 1M $DIR/testfile

expect_normal_exit ../obj_list/obj_list$EXESUFFIX $DIR/testfile\
		i:1:0\
		i:0:0\
		i:1:-1\
		i:0:-1\
		i:1:2\
		P:2 R:2\
		r:3\
		r:2\
		r:1\
		r:-1\
		r:0\
		P:2 R:2

pass
