# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2016, Intel Corporation

#
# src/test/pmem_movnt_align/Makefile -- build pmem_movnt_align unittest
#
TARGET = pmem_movnt_align
OBJS = pmem_movnt_align.o

LIBPMEM=y

include ../Makefile.inc
