# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016, Intel Corporation
#
# Makefile -- Makefile for pmemdetect tool
#

TOP = ../../../..

TARGET = pmemdetect

OBJS = pmemdetect.o

LIBPMEM=y
TOOLS_COMMON=y
LIBPMEMBLK_PRIV=btt_info_convert2h

SCP_TO_REMOTE_NODES = y

include $(TOP)/src/tools/Makefile.inc
