# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2023, Intel Corporation
#
# Makefile -- Makefile for pmemdetect tool
#

TOP = ../../../..

TARGET = pmemdetect

OBJS = pmemdetect.o

LIBPMEM=y
TOOLS_COMMON=y

include $(TOP)/src/tools/Makefile.inc
