# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2020, Intel Corporation

#
# examples/libpmem2/basic/Makefile -- build the basic example
#
PROGS = basic

LIBS = -lpmem2

include ../../Makefile.inc

basic: basic.o
