# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/mmap_fixed/Makefile -- build mmap_fixed unit test
#

TARGET = mmap_fixed
OBJS = mmap_fixed.o

include ../Makefile.inc
