/* SPDX-License-Identifier: BSD-3-Clause */
/* Copyright 2024, Intel Corporation */

/*
 * This file is automatically generated by utils/call_stack_analysis/log_generate_all_calls.py.
 * Please do not modify manually.
 */

/*
 * all_calls.h -- internal logging interfaces
 */

#ifndef ALL_CALLS_H
#define ALL_CALLS_H

void call_all_CORE_LOG_ERROR_LAST(void);
void call_all_ERR_WO_ERRNO(void);
void call_all_CORE_LOG_ERROR_W_ERRNO_LAST(int errnum);
void call_all_ERR_W_ERRNO(int errnum);

#endif /* ALL_CALLS_H */
