# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018-2022, Intel Corporation

#
# src/test/tools/obj_verify -- build obj_verify tool
#

TOP = ../../../..

TARGET = obj_verify
OBJS = obj_verify.o

LIBPMEM=y
LIBPMEMOBJ=y
LIBPMEMCOMMON=y

include $(TOP)/src/tools/Makefile.inc
