# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2014-2016, Intel Corporation

#
# examples/libpmem/Makefile -- build the libpmem examples
#

PROGS = manpage simple_copy full_copy

LIBS = -lpmem -pthread

include ../Makefile.inc

manpage: manpage.o

simple_copy: simple_copy.o

full_copy: full_copy.o
