#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2024, Intel Corporation

#
# src/test/ex_libpmemobj/TEST9 -- unit test for libpmemobj examples
#

. ../unittest/unittest.sh

require_test_type medium

require_build_type debug nondebug

setup

. ./common.sh
EX_PATH=../../examples/libpmemobj/string_store_tx_type

expect_normal_exit $EX_PATH/writer $DIR/testfile1 > $LOG_TEMP 2>&1 << EOF
Hello!
EOF

expect_normal_exit $EX_PATH/reader $DIR/testfile1 >> $LOG_TEMP 2>&1

mv $LOG_TEMP $LOG

check

pass
