#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2024, Intel Corporation

#
# src/test/ex_libpmemobj/TEST7 -- unit test for libpmemobj examples
#

. ../unittest/unittest.sh

require_test_type medium

require_build_type debug nondebug

setup

. ./common.sh

EX_PATH=../../examples/libpmemobj/string_store

expect_normal_exit $EX_PATH/writer $DIR/testfile1 > $LOG_TEMP 2>&1 << EOF
Hello!
EOF

expect_normal_exit $EX_PATH/reader $DIR/testfile1 >> $LOG_TEMP 2>&1

# Exclude error messages printed out on the stderr by PMDK in debug
fgrep -v "*ERROR*" $LOG_TEMP > $LOG
rm $LOG_TEMP

check

pass
