#!/usr/bin/env bash
#
# Copyright 2019, Intel Corporation
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in
#       the documentation and/or other materials provided with the
#       distribution.
#
#     * Neither the name of the copyright holder nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

#
# src/test/ex_libpmemobj/TEST25 -- unit test for libpmemobj examples
#

# standard unit test setup
. ../unittest/unittest.sh

cp ../../examples/libpmemobj/colony/ints.txt int.txt
cp ../../examples/libpmemobj/colony/pmemoids.txt pmemoid.txt

require_test_type medium

require_build_type debug nondebug

setup

EX_PATH=../../examples/libpmemobj/colony

expect_normal_exit $EX_PATH/colony $DIR/testfile > out$UNITTEST_NUM.log

expect_normal_exit $EX_PATH/colony $DIR/testfile create-colony >> out$UNITTEST_NUM.log
expect_normal_exit $EX_PATH/colony $DIR/testfile insert-int >> out$UNITTEST_NUM.log
expect_normal_exit $EX_PATH/colony $DIR/testfile insert-pmemoid >> out$UNITTEST_NUM.log
expect_normal_exit $EX_PATH/colony $DIR/testfile insert-int-from-file >> out$UNITTEST_NUM.log
expect_normal_exit $EX_PATH/colony $DIR/testfile insert-pmemoid-from-file >> out$UNITTEST_NUM.log
expect_normal_exit $EX_PATH/colony $DIR/testfile remove-item >> out$UNITTEST_NUM.log
expect_normal_exit $EX_PATH/colony $DIR/testfile remove-range >> out$UNITTEST_NUM.log
expect_normal_exit $EX_PATH/colony $DIR/testfile print-content >> out$UNITTEST_NUM.log
expect_normal_exit $EX_PATH/colony $DIR/testfile print-colony >> out$UNITTEST_NUM.log
expect_normal_exit $EX_PATH/colony $DIR/testfile delete-free-blocks >> out$UNITTEST_NUM.log
expect_normal_exit $EX_PATH/colony $DIR/testfile delete-colony >> out$UNITTEST_NUM.log

expect_normal_exit $EX_PATH/colony $DIR/testfile create-colony coli int 5 >> out$UNITTEST_NUM.log
expect_normal_exit $EX_PATH/colony $DIR/testfile print-content coli >> out$UNITTEST_NUM.log

expect_normal_exit $EX_PATH/colony $DIR/testfile insert-int-from-file coli int.txt >> out$UNITTEST_NUM.log
expect_normal_exit $EX_PATH/colony $DIR/testfile print-content coli >> out$UNITTEST_NUM.log
expect_normal_exit $EX_PATH/colony $DIR/testfile print-colony coli >> out$UNITTEST_NUM.log

expect_normal_exit $EX_PATH/colony $DIR/testfile remove-item coli 15 >> out$UNITTEST_NUM.log
expect_normal_exit $EX_PATH/colony $DIR/testfile print-content coli >> out$UNITTEST_NUM.log
expect_normal_exit $EX_PATH/colony $DIR/testfile print-colony coli >> out$UNITTEST_NUM.log

expect_normal_exit $EX_PATH/colony $DIR/testfile remove-range coli 14 20 >> out$UNITTEST_NUM.log
expect_normal_exit $EX_PATH/colony $DIR/testfile remove-range coli 5 10 >> out$UNITTEST_NUM.log
expect_normal_exit $EX_PATH/colony $DIR/testfile print-content coli >> out$UNITTEST_NUM.log
expect_normal_exit $EX_PATH/colony $DIR/testfile print-colony coli >> out$UNITTEST_NUM.log

expect_normal_exit $EX_PATH/colony $DIR/testfile insert-int coli 183 >> out$UNITTEST_NUM.log
expect_normal_exit $EX_PATH/colony $DIR/testfile print-content coli >> out$UNITTEST_NUM.log
expect_normal_exit $EX_PATH/colony $DIR/testfile print-colony coli >> out$UNITTEST_NUM.log

expect_normal_exit $EX_PATH/colony $DIR/testfile delete-free-blocks coli >> out$UNITTEST_NUM.log
expect_normal_exit $EX_PATH/colony $DIR/testfile print-content coli >> out$UNITTEST_NUM.log
expect_normal_exit $EX_PATH/colony $DIR/testfile print-colony coli >> out$UNITTEST_NUM.log

expect_normal_exit $EX_PATH/colony $DIR/testfile insert-int-from-file coli int.txt >> out$UNITTEST_NUM.log
expect_normal_exit $EX_PATH/colony $DIR/testfile print-content coli >> out$UNITTEST_NUM.log
expect_normal_exit $EX_PATH/colony $DIR/testfile print-colony coli >> out$UNITTEST_NUM.log

expect_normal_exit $EX_PATH/colony $DIR/testfile delete-colony coli >> out$UNITTEST_NUM.log
expect_normal_exit $EX_PATH/colony $DIR/testfile print-content coli >> out$UNITTEST_NUM.log


expect_normal_exit $EX_PATH/colony $DIR/testfile create-colony colp pmemoid 7 >> out$UNITTEST_NUM.log
expect_normal_exit $EX_PATH/colony $DIR/testfile print-content colp >> out$UNITTEST_NUM.log

expect_normal_exit $EX_PATH/colony $DIR/testfile insert-pmemoid-from-file colp pmemoid.txt >> out$UNITTEST_NUM.log
expect_normal_exit $EX_PATH/colony $DIR/testfile print-content colp >> out$UNITTEST_NUM.log
expect_normal_exit $EX_PATH/colony $DIR/testfile print-colony colp >> out$UNITTEST_NUM.log

expect_normal_exit $EX_PATH/colony $DIR/testfile remove-range colp 6 15 >> out$UNITTEST_NUM.log
expect_normal_exit $EX_PATH/colony $DIR/testfile print-content colp >> out$UNITTEST_NUM.log
expect_normal_exit $EX_PATH/colony $DIR/testfile print-colony colp >> out$UNITTEST_NUM.log

expect_normal_exit $EX_PATH/colony $DIR/testfile remove-range colp 0 5 >> out$UNITTEST_NUM.log
expect_normal_exit $EX_PATH/colony $DIR/testfile print-content colp >> out$UNITTEST_NUM.log
expect_normal_exit $EX_PATH/colony $DIR/testfile print-colony colp >> out$UNITTEST_NUM.log

expect_normal_exit $EX_PATH/colony $DIR/testfile delete-free-blocks colp
expect_normal_exit $EX_PATH/colony $DIR/testfile print-content colp >> out$UNITTEST_NUM.log
expect_normal_exit $EX_PATH/colony $DIR/testfile print-colony colp >> out$UNITTEST_NUM.log

expect_normal_exit $EX_PATH/colony $DIR/testfile insert-pmemoid-from-file colp pmemoid.txt >> out$UNITTEST_NUM.log
expect_normal_exit $EX_PATH/colony $DIR/testfile insert-pmemoid colp 40731435551616 985633251211 >> out$UNITTEST_NUM.log
expect_normal_exit $EX_PATH/colony $DIR/testfile insert-pmemoid colp 35551698674407316 14073705021046740 >> out$UNITTEST_NUM.log
expect_normal_exit $EX_PATH/colony $DIR/testfile insert-pmemoid colp 98674447107335551 777441113705002 >> out$UNITTEST_NUM.log
expect_normal_exit $EX_PATH/colony $DIR/testfile insert-pmemoid colp 5858755551616 425370962235 >> out$UNITTEST_NUM.log
expect_normal_exit $EX_PATH/colony $DIR/testfile print-content colp >> out$UNITTEST_NUM.log
expect_normal_exit $EX_PATH/colony $DIR/testfile print-colony colp >> out$UNITTEST_NUM.log

expect_normal_exit $EX_PATH/colony $DIR/testfile remove-range colp 13 27 >> out$UNITTEST_NUM.log
expect_normal_exit $EX_PATH/colony $DIR/testfile print-content colp >> out$UNITTEST_NUM.log
expect_normal_exit $EX_PATH/colony $DIR/testfile print-colony colp >> out$UNITTEST_NUM.log

expect_normal_exit $EX_PATH/colony $DIR/testfile delete-free-blocks colp
expect_normal_exit $EX_PATH/colony $DIR/testfile print-content colp >> out$UNITTEST_NUM.log
expect_normal_exit $EX_PATH/colony $DIR/testfile print-colony colp >> out$UNITTEST_NUM.log

expect_normal_exit $EX_PATH/colony $DIR/testfile delete-colony colp
expect_normal_exit $EX_PATH/colony $DIR/testfile print-content colp >> out$UNITTEST_NUM.log


check

rm -f /repos/pmdk/src/test/ex_libpmemobj/int.txt
rm -f /repos/pmdk/src/test/ex_libpmemobj/pmemoid.txt

pass