#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/ex_libpmemobj/TEST19 -- unit test for libpmemobj examples
#

. $UNITTEST_SH

require_test_type medium

require_build_type debug nondebug

setup

EX_PATH=../../examples/libpmemobj/map

expect_normal_exit $EX_PATH/mapcli skiplist $DIR/testfile1 555 > out$UNITTEST_NUM.log 2>&1 << EOF
i 1234
i 4321
c 1234
r 1234
c 4321
r 4321
c 4321
q
EOF

check

pass
