#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/ex_libpmemobj/TEST1 -- unit test for libpmemobj examples
#

. ../unittest/unittest.sh

require_test_type medium

require_build_type debug nondebug

setup

EX_PATH=../../examples/libpmemobj

expect_normal_exit $EX_PATH/btree $DIR/testfile1 i 1234 foo > out$UNITTEST_NUM.log 2>&1
expect_normal_exit $EX_PATH/btree $DIR/testfile1 i 4321 bar >> out$UNITTEST_NUM.log 2>&1
expect_normal_exit $EX_PATH/btree $DIR/testfile1 i 1 Hello >> out$UNITTEST_NUM.log 2>&1
expect_normal_exit $EX_PATH/btree $DIR/testfile1 i 2 World! >> out$UNITTEST_NUM.log 2>&1
expect_normal_exit $EX_PATH/btree $DIR/testfile1 p >> out$UNITTEST_NUM.log 2>&1
expect_normal_exit $EX_PATH/btree $DIR/testfile1 f 4321 >> out$UNITTEST_NUM.log 2>&1

check

pass
