#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/ex_libpmemobj/TEST0 -- unit test for libpmemobj examples
#

. ../unittest/unittest.sh

require_test_type medium
require_build_type debug nondebug
# Valgrind interprets msync as a read and hence reports a race
require_fs_type pmem

setup

EX_PATH=../../examples/libpmemobj

expect_normal_exit $EX_PATH/pi $DIR/testfile1 c 2 20 > out$UNITTEST_NUM.log 2>&1
expect_normal_exit $EX_PATH/pi $DIR/testfile1 p >> out$UNITTEST_NUM.log 2>&1

check

pass
