#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/ex_linkedlist/TEST0 -- unit test for linkedlist example
#

. $UNITTEST_SH

require_test_type medium

require_build_type debug nondebug
setup

expect_normal_exit ./ex_linkedlist$EXESUFFIX $DIR/testfile

check

pass
