# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016, Intel Corporation

#
# src/test/bttdevice/Makefile -- build unittest for testing tools operating
# on btt device
#
USE_PMEMSPOIL=y
USE_BTTCREATE=y

include ../Makefile.inc
