#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2018, Intel Corporation
#
#
# bttdevice/TEST1 -- test for checking pmempool info for spoiled btt device
#

. $UNITTEST_SH

require_test_type medium

require_fs_type any

setup

POOL=$DIR/file.pool
LOG=out${UNITTEST_NUM}.log
rm -f $LOG && touch $LOG

expect_normal_exit $BTTCREATE -v $POOL >> $LOG

$PMEMSPOIL -v $POOL "bttdevice.arena(0).btt_info.sig=BADSIGNATURE"\
		"bttdevice.arena(0).btt_info.external_lbasize=10"\
		"bttdevice.arena(0).btt_info.major=0x0" >> $LOG

expect_normal_exit $PMEMPOOL$EXESUFFIX info $POOL -f btt >> $LOG
check_file $POOL

check

pass
