# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/obj_tx_callbacks/Makefile -- build obj_tx_callbacks unit test
#
TARGET = obj_tx_callbacks
OBJS = obj_tx_callbacks.o

LIBPMEMOBJ=y

include ../Makefile.inc
