#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/obj_tx_callbacks/TEST0 -- unit test for transaction stage callbacks
#

. ../unittest/unittest.sh

require_test_type medium

setup

expect_normal_exit ./obj_tx_callbacks$EXESUFFIX $DIR/testfile1

check

pass
