# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_recovery/Makefile -- build obj_recovery unit test
#

TARGET = obj_recovery
OBJS = obj_recovery.o

LIBPMEMOBJ=y
LIBPMEMCOMMON=y

include ../Makefile.inc
