# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2023, Intel Corporation

#
# src/test/obj_tx_alloc_mt/Makefile -- build obj_tx_alloc_mt unit test
#
TARGET = obj_tx_alloc_mt
OBJS = obj_tx_alloc_mt.o

LIBPMEMOBJ=internal-debug

include ../Makefile.inc
