#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2023, Intel Corporation

#
# src/test/obj_tx_alloc_mt/TEST2 -- multithreaded allocator test
#	(medium helgrind version)
#

. ../unittest/unittest.sh

require_fs_type pmem non-pmem
require_test_type medium
require_valgrind 3.10
configure_valgrind helgrind force-enable
setup

PMEM_IS_PMEM_FORCE=1 expect_normal_exit\
	./obj_tx_alloc_mt$EXESUFFIX 4 64 4 $DIR/testfile

pass
