# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/blk_non_zero/Makefile -- build blk_non_zero unit test
#
TARGET = blk_non_zero
OBJS = blk_non_zero.o

LIBPMEMBLK=y

include ../Makefile.inc

INCS += -I../../libpmemblk
