#!/usr/bin/env bash
#
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation
# Copyright (c) 2016, Microsoft Corporation. All rights reserved.
# Copyright 2019, IBM Corporation

#
# src/test/blk_non_zero/TEST13 -- unit test for
# pmemblk_read/write/set_zero/set_error
#
# This test is equivalent of TEST2 for ppc64le platform.
#

. ../unittest/unittest.sh

# doesn't make sense to run in local directory
require_fs_type pmem non-pmem
require_test_type long
require_ppc64

setup

# write re-use test case
create_nonzeroed_file 1G 824M $DIR/testfile1

expect_normal_exit ./blk_non_zero$EXESUFFIX 512 $DIR/testfile1 c 0\
	w:0 w:1 w:2 w:3 w:4 r:4 r:3 r:2 r:1 r:0

expect_normal_exit ./blk_non_zero$EXESUFFIX 512 $DIR/testfile1 o\
	w:0 r:4 r:3 r:2 r:1 r:0 w:0 r:0

check

pass
