#!/usr/bin/env bash
#
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation
# Copyright (c) 2016, Microsoft Corporation. All rights reserved.
# Copyright 2019, IBM Corporation

#
# src/test/blk_non_zero/TEST14 -- unit test for
# pmemblk_read/write/set_zero/set_error
#
# This test is equivalent of TEST3 for ppc64le platform.
#

. ../unittest/unittest.sh

# doesn't make sense to run in local directory
require_fs_type pmem non-pmem
require_test_type long
require_ppc64

setup

# mix writes with set_zero and set_error and check results
create_nonzeroed_file 1G 824M $DIR/testfile1

expect_normal_exit ./blk_non_zero$EXESUFFIX 512 $DIR/testfile1 c 0\
	w:100 w:200 w:300 w:400\
	r:100 r:200 r:300 r:400\
	w:100 z:200 w:300 z:400\
	r:100 r:200 r:300 r:400\
	e:100 w:200 e:300 w:400\
	r:100 r:200 r:300 r:400

check

pass
