#!/usr/bin/env bash
#
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation
# Copyright 2019, IBM Corporation

#
# src/test/blk_non_zero/TEST17 -- unit test for
# pmemblk_read/write/set_zero/set_error
#
# This test is equivalent of TEST6 for ppc64le platform.
#

. $UNITTEST_SH

require_test_type medium

# doesn't make sense to run in local directory
require_fs_type pmem non-pmem
require_ppc64

setup

# single arena write case
FILE_SIZE=$((1024*1024*1024))
require_free_space $FILE_SIZE

expect_normal_exit ./blk_non_zero$EXESUFFIX 512 $DIR/testfile1 c $FILE_SIZE\
	w:0 r:1 r:0 w:1 r:0 r:1 r:2

check

pass
