#!/usr/bin/env bash
#
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation
# Copyright (c) 2016, Microsoft Corporation. All rights reserved.
# Copyright 2019, IBM Corporation

#
# src/test/blk_non_zero/TEST12 -- unit test for
# pmemblk_read/write/set_zero/set_error
#
# This test is equivalent of TEST1 for ppc64le platform.
#

. ../unittest/unittest.sh

# doesn't make sense to run in local directory
require_fs_type pmem non-pmem
require_test_type long
require_ppc64

setup

# single arena write case
create_nonzeroed_file 1G 824K $DIR/testfile1

expect_normal_exit ./blk_non_zero$EXESUFFIX 512 $DIR/testfile1 c 0\
	w:0 r:1 r:0 w:1 r:0 r:1 r:2

check

pass
