#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2019, Intel Corporation
# Copyright 2025, Hewlett Packard Enterprise Development LP
#
#
# pmempool_feature/TEST16 -- unit test for CHECK_BAD_BLOCKS
#

. ../unittest/unittest.sh

require_test_type medium
require_fs_type any

configure_valgrind force-disable

setup

require_sds $PMEMPOOL$EXESUFFIX

. ./common.sh
require_bb_enabled_by_default $PMEMPOOL$EXESUFFIX

pmempool_feature_create_poolset "no_dax_device"
pmempool_feature_test_CHECK_BAD_BLOCKS

check

pass
