#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018, Intel Corporation
# Copyright 2025, Hewlett Packard Enterprise Development LP
#
#
# pmempool_feature/TEST10 -- unit test for CKSUM_2K + dax_device
#

. ../unittest/unittest.sh

require_test_type medium
require_fs_type any
require_dax_devices 1

configure_valgrind force-disable

setup

require_sds $PMEMPOOL$EXESUFFIX

. ./common.sh

pmempool_feature_create_poolset "dax_device"
pmempool_feature_test_CKSUM_2K

check

pass
