#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018, Intel Corporation
#
#
# pmempool_feature/TEST4 -- unit test for CKSUM_2K + memcheck
#

. $UNITTEST_SH

require_test_type medium
require_fs_type any
require_sds $PMEMPOOL$EXESUFFIX

configure_valgrind memcheck force-enable $PMEMPOOL$EXESUFFIX

setup
. ./common.sh

pmempool_feature_create_poolset "no_dax_device"
pmempool_feature_test_CKSUM_2K

check

pass
