#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018-2024, Intel Corporation
# Copyright 2025, Hewlett Packard Enterprise Development LP
#
#
# pmempool_feature/TEST14 -- unit test for SHUTDOWN_STATE + ctl
#

. ../unittest/unittest.sh

require_test_type medium
require_fs_type any

setup

require_sds $PMEMPOOL$EXESUFFIX

. ./common.sh

PMEMOBJ_CONF="${PMEMOBJ_CONF};sds.at_create=0"
pmempool_feature_create_poolset "no_dax_device"
pmempool_feature_query SHUTDOWN_STATE normal

check

pass
