#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018, Intel Corporation
#
#
# pmempool_feature/TEST9 -- unit test for SINGLEHDR + dax_device
#

. $UNITTEST_SH

require_test_type medium
require_fs_type any
require_dax_devices 1

configure_valgrind force-disable

setup
. ./common.sh

pmempool_feature_create_poolset "dax_device"
pmempool_feature_test_SINGLEHDR

check

pass
