#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018, Intel Corporation
#
#
# pmempool_feature/TEST0 -- unit test for SINGLEHDR
#

. $UNITTEST_SH

require_test_type medium
require_fs_type any

configure_valgrind force-disable

setup
. ./common.sh

pmempool_feature_create_poolset "no_dax_device"
pmempool_feature_test_SINGLEHDR

check

pass
