#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018, Intel Corporation
# Copyright 2025, Hewlett Packard Enterprise Development LP
#
#
# pmempool_feature/TEST4 -- unit test for CKSUM_2K + memcheck
#

. ../unittest/unittest.sh

require_test_type medium
require_fs_type any

setup

require_sds $PMEMPOOL$EXESUFFIX

configure_valgrind memcheck force-enable $PMEMPOOL$EXESUFFIX

. ./common.sh

pmempool_feature_create_poolset "no_dax_device"
pmempool_feature_test_CKSUM_2K

check

pass
