#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018, Intel Corporation
#
#
# pmempool_feature/TEST1 -- unit test for CKSUM_2K
#

. ../unittest/unittest.sh

require_test_type medium
require_fs_type any
require_sds $PMEMPOOL$EXESUFFIX

configure_valgrind force-disable

setup
. ./common.sh

pmempool_feature_create_poolset "no_dax_device"
pmempool_feature_test_CKSUM_2K

check

pass
