#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018-2019, Intel Corporation

#
# src/test/pmem_deep_persist/TEST2 -- unit test for pmem_deep_persist
#

. ../unittest/unittest.sh

require_test_type medium
require_fs_type any
require_dax_devices 1

setup

create_poolset $DIR/testset AUTO:${DEVICE_DAX_PATH[0]}

expect_normal_exit ./pmem_deep_persist$EXESUFFIX ${DEVICE_DAX_PATH[0]} p -1 0

count_lines "<libpmemobj>: <15>.*pmem\.c.*pmem_msync.*" pmemobj$UNITTEST_NUM.log > ./grep$UNITTEST_NUM.log
count_lines "<libpmemobj>: <3>.*deep_flush_write.*" pmemobj$UNITTEST_NUM.log >> ./grep$UNITTEST_NUM.log

check

pass
