#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018-2020, Intel Corporation

#
# src/test/pmem_deep_persist/TEST7 -- unit test for pmem_deep_persist
#

. ../unittest/unittest.sh

require_test_type medium
require_fs_type pmem non-pmem

setup

export PMEMOBJ_LOG_LEVEL=15

create_poolset $DIR/testset1 4M:$DIR/testfile1 16M:$DIR/testfile2 8M:$DIR/testfile3

DEEP_PERSIST_SIZE=$(convert_to_bytes 20M)
OFFSET=$(convert_to_bytes 2M)
expect_normal_exit ./pmem_deep_persist$EXESUFFIX $DIR/testset1 o $DEEP_PERSIST_SIZE $OFFSET

count_lines "<libpmemobj>: <3>.*part_deep_common.*" pmemobj$UNITTEST_NUM.log > ./grep$UNITTEST_NUM.log
count_lines "<libpmemobj>: <3>.*deep_sync_write.*" pmemobj$UNITTEST_NUM.log >> ./grep$UNITTEST_NUM.log

check

pass
