# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018, Intel Corporation
#
# Makefile -- Makefile for fallocate detection tool
#

TOP = ../../../..

TARGET = fallocate_detect
OBJS = fallocate_detect.o

LIBPMEM=y
LIBPMEMCOMMON=y

include $(TOP)/src/tools/Makefile.inc
