# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2014-2016, Intel Corporation

#
# src/test/traces_custom_function/Makefile -- build traces unit test
#
TARGET = traces_custom_function
OBJS = traces_custom_function.o

BUILD_STATIC_DEBUG=n
BUILD_STATIC_NONDEBUG=n

LIBPMEMCOMMON=y
include ../Makefile.inc
CFLAGS += -DDEBUG
