#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2014-2019, Intel Corporation

#
# src/test/traces_custom_function/TEST0 -- unit test for traces custom
# print function
#

. ../unittest/unittest.sh

require_test_type medium

require_fs_type none
require_build_type debug

setup

export TRACE_LOG_LEVEL=4
expect_normal_exit ./traces_custom_function$EXESUFFIX p

check

pass
