#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/rpmemd_db/TEST0 -- unit test for remote tests support
#

. $UNITTEST_SH

require_test_type medium

require_fs_type any

setup

ROOT_DIR=$DIR/poolset-dir
PART_DIR=$DIR/parts-dir
LOG_FILE=rpmemd$UNITTEST_NUM.log
rm -f $LOG_FILE

mkdir -p $ROOT_DIR
mkdir -p $PART_DIR

create_poolset $ROOT_DIR/pool0.set\
	8M:$PART_DIR/pool0.part.0:x\
	8M:$PART_DIR/pool0.part.1:x\
	8M:$PART_DIR/pool0.part.2:x\
	8M:$PART_DIR/pool0.part.3:x

create_poolset $ROOT_DIR/pool1.set\
	8M:$PART_DIR/pool1.part.0:x\
	8M:$PART_DIR/pool1.part.1:x\
	8M:$PART_DIR/pool1.part.2:x\
	8M:$PART_DIR/pool1.part.3:x

expect_normal_exit $PMEMPOOL.static-nondebug rm -f -s $ROOT_DIR/pool0.set
expect_normal_exit $PMEMPOOL.static-nondebug rm -f -s $ROOT_DIR/pool1.set

expect_normal_exit ./rpmemd_db$EXESUFFIX $LOG_FILE $ROOT_DIR \
				pool0.set pool1.set

mv rpmem0.log rpmem0_tmp.log
$GREP -e " flock " -e Non-empty rpmem0_tmp.log > rpmem0.log || true

check

pass
