#!/usr/bin/env bash
#
# Copyright 2016-2019, Intel Corporation
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in
#       the documentation and/or other materials provided with the
#       distribution.
#
#     * Neither the name of the copyright holder nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

#
# src/test/rpmemd_db/TEST0 -- unit test for remote tests support
#

. ../unittest/unittest.sh

require_test_type medium

require_fs_type any

setup

ROOT_DIR=$DIR/poolset-dir
PART_DIR=$DIR/parts-dir
LOG_FILE=rpmemd$UNITTEST_NUM.log
rm -f $LOG_FILE

mkdir -p $ROOT_DIR
mkdir -p $PART_DIR

create_poolset $ROOT_DIR/pool0.set\
	8M:$PART_DIR/pool0.part.0:x\
	8M:$PART_DIR/pool0.part.1:x\
	8M:$PART_DIR/pool0.part.2:x\
	8M:$PART_DIR/pool0.part.3:x

create_poolset $ROOT_DIR/pool1.set\
	8M:$PART_DIR/pool1.part.0:x\
	8M:$PART_DIR/pool1.part.1:x\
	8M:$PART_DIR/pool1.part.2:x\
	8M:$PART_DIR/pool1.part.3:x

expect_normal_exit $PMEMPOOL.static-release rm -f -s $ROOT_DIR/pool0.set
expect_normal_exit $PMEMPOOL.static-release rm -f -s $ROOT_DIR/pool1.set

expect_normal_exit ./rpmemd_db$EXESUFFIX $LOG_FILE $ROOT_DIR \
				pool0.set pool1.set

mv rpmem0.log rpmem0_tmp.log
$GREP -e " flock " -e Non-empty rpmem0_tmp.log > rpmem0.log || true

check

pass
