# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2017-2019, Intel Corporation

#
# src/test/obj_ctl_heap_size/Makefile -- build obj_ctl_heap_size test
#
TARGET = obj_ctl_heap_size
OBJS = obj_ctl_heap_size.o

LIBPMEMOBJ=y

include ../Makefile.inc
