# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018, Intel Corporation

#
# src/test/util_is_zeroed/Makefile -- build util_is_zeroed unit test
#
TARGET = util_is_zeroed
OBJS = util_is_zeroed.o

LIBPMEMCOMMON=y

include ../Makefile.inc
