#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018, Intel Corporation

#
# src/test/util_is_zeroed/TEST0 -- unit test for util_is_zeroed
#

. ../unittest/unittest.sh

require_test_type medium

require_fs_type none
require_build_type debug nondebug
# covered by TEST1
configure_valgrind memcheck force-disable

setup

expect_normal_exit ./util_is_zeroed$EXESUFFIX

pass
