# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2023, Intel Corporation

# This playbook is designed to update all installed packages at
# Rocky Linux and reboot the platform if required.
# The playbook description and how to use it are available
# in the README.md file.

    - name: install yum-utils needed to check if reboot is required
      package:
        name: yum-utils
        state: latest

    - name: "Update kernel packages"
      package:
        name: "kernel.x86_64"
        state: latest

    - name: "Update OS packages"
      package:
        name: "*"
        state: latest

    - name: Check if reboot required by running needs-restarting -r
      command: needs-restarting -r
      register: needs_restarting
      changed_when: needs_restarting.rc == 1
      failed_when: needs_restarting.rc != 0 and needs_restarting.rc != 1
      notify: "Reboot platform to apply updates"


