# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2020, Intel Corporation

#
# examples/libpmem2/pmemset/Makefile -- build the set prototype
#
PROGS = main

LIBS = -lpmem2

include ../../Makefile.inc

main: main.o pmemset.o
