# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/obj_fragmentation/Makefile -- build obj_fragmentation test
#
TARGET = obj_fragmentation
OBJS = obj_fragmentation.o

LIBPMEMOBJ=y

include ../Makefile.inc
