#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/mmap/TEST0 -- unit test for memory mapping routines
#

. $UNITTEST_SH

require_test_type medium

require_fs_type any

# XXX disabled for now, to be fixed in pmem/issues#1053.
exit 0

setup

touch $DIR/testfile

expect_normal_exit ./mmap$EXESUFFIX $DIR/testfile

pass
