# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018, Intel Corporation

#
# src/test/util_extent/Makefile -- build util_extent test
#
#
TARGET = util_extent
OBJS = util_extent.o

LIBPMEMCOMMON=y

include ../Makefile.inc
