# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/util_is_absolute/Makefile -- check if path is absolute
#
TARGET = util_is_absolute
OBJS = util_is_absolute.o

LIBPMEMCOMMON=y

include ../Makefile.inc
