# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2017-2019, Intel Corporation

#
# src/test/obj_pmalloc_rand_mt/Makefile -- build obj_pmalloc_rand_mt unit test
#
TARGET = obj_pmalloc_rand_mt
OBJS = obj_pmalloc_rand_mt.o

LIBPMEMOBJ=y
LIBPMEMCOMMON=y

include ../Makefile.inc
