#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2017-2023, Intel Corporation

#
# src/test/obj_pmalloc_rand_mt/TEST0 -- multithreaded allocator test
#

. ../unittest/unittest.sh

require_fs_type pmem
require_test_type long
require_valgrind 3.10
configure_valgrind helgrind force-enable
setup

require_free_space 3G

PMEM_IS_PMEM_FORCE=1 expect_normal_exit\
	./obj_pmalloc_rand_mt$EXESUFFIX $DIR/testfile 8 1000 260000 10000 1234

pass
