#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2017-2019, Intel Corporation

#
# src/test/obj_pmalloc_rand_mt/TEST1 -- multithreaded allocator test
#

. $UNITTEST_SH

require_fs_type pmem
require_test_type medium
setup

require_free_space 3G

PMEM_IS_PMEM_FORCE=1 expect_normal_exit\
	./obj_pmalloc_rand_mt$EXESUFFIX $DIR/testfile 8 1000 260000 1234

pass
