# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2016, Intel Corporation

#
# examples/libpmemobj/pmemblk/Makefile -- build obj implementations of pmemblk
#
PROGS = obj_pmemblk

LIBS = -lpmemobj -lpmem -pthread

include ../../Makefile.inc

obj_pmemblk: obj_pmemblk.o
