# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2017-2019, Intel Corporation

#
# src/test/obj_extend/Makefile -- build obj_extend test
#
TARGET = obj_extend
OBJS = obj_extend.o

LIBPMEMOBJ=y

include ../Makefile.inc
