#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018-2019, Intel Corporation

#
# src/test/obj_extend/TEST6 -- unit test for extending the pool
# negative scenario - missing SINGLEHDR option
# (pmem/issues#822)
#

. ../unittest/unittest.sh

require_test_type medium
require_fs_type any

setup

RESVSIZE=10M

# prepare pool sets
create_poolset $DIR/testset1\
	$RESVSIZE:$DIR/testdir10:d

expect_normal_exit ./obj_extend$EXESUFFIX $DIR/testset1

check

pass
