#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2017-2019, Intel Corporation

#
# src/test/obj_extend/TEST0 -- unit test for extending the pool
#

. $UNITTEST_SH

require_test_type medium
require_fs_type any

setup

RESVSIZE=$(((512 + 8) * 1024 * 1024)) # 512MiB + 8MiB

# prepare pool sets
create_poolset $DIR/testset1\
	$RESVSIZE:$DIR/testdir11:d\
	O SINGLEHDR

expect_normal_exit ./obj_extend$EXESUFFIX $DIR/testset1

check

pass
