# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2019, Intel Corporation

#
# src/test/pmem2_include/Makefile -- compilation test for libpmem2
#
TARGET = pmem2_include
OBJS = pmem2_include.o

LIBPMEM2=y

include ../Makefile.inc
