# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2024, Intel Corporation

#
# src/test/valgrind_check/Makefile -- build valgrind_check unit test
#
TARGET = valgrind_check
OBJS = valgrind_check.o

include ../Makefile.inc
