# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2023, Intel Corporation

#
# src/test/pmem_movnt/Makefile -- build valgrind_check unit test
#
TARGET = valgrind_check
OBJS = valgrind_check.o

LIBPMEM=n

include ../Makefile.inc
