#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2024, Intel Corporation

#
# src/test/valgrind_check/TEST0 -- unit test for valgrind_check
#

. ../unittest/unittest.sh

require_test_type short
require_valgrind

setup

expect_normal_exit ./valgrind_check$EXESUFFIX

pass
