# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_pmalloc_oom_mt/Makefile -- build obj_pmalloc_oom_mt test
#
TARGET = obj_pmalloc_oom_mt
OBJS = obj_pmalloc_oom_mt.o

LIBPMEMOBJ=y

include ../Makefile.inc
