#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

. $UNITTEST_SH

require_test_type medium

setup

export PMEM_IS_PMEM_FORCE=1

expect_normal_exit ./obj_pmalloc_oom_mt$EXESUFFIX $DIR/testfile1

pass
