# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2017, Intel Corporation

#
# src/test/pmem_memmove/Makefile -- build pmem_memmove unit test
#
TARGET = pmem_memmove
OBJS = pmem_memmove.o

LIBPMEM=y
LIBPMEMCOMMON=y

include ../Makefile.inc
