#!/usr/bin/env bash
#
# Copyright 2015-2019, Intel Corporation
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in
#       the documentation and/or other materials provided with the
#       distribution.
#
#     * Neither the name of the copyright holder nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

#
# src/test/out_err_mt/TEST1 -- unit test for error messages
#

. ../unittest/unittest.sh

require_test_type medium
require_fs_type any

require_valgrind 3.7
configure_valgrind drd force-enable

setup

unset PMEM_LOG_LEVEL
unset PMEMLOG_LOG_LEVEL
unset PMEMBLK_LOG_LEVEL
unset PMEMOBJ_LOG_LEVEL
unset VMEM_LOG_LEVEL
unset PMEMPOOL_LOG_LEVEL

unset PMEM_LOG_FILE
unset PMEMLOG_LOG_FILE
unset PMEMBLK_LOG_FILE
unset PMEMOBJ_LOG_FILE
unset VMEM_LOG_FILE
unset PMEMPOOL_LOG_FILE

expect_normal_exit ./out_err_mt$EXESUFFIX $DIR/testfile1\
		$DIR/testfile2 $DIR/testfile3 $DIR/testfile4 $DIR

check

pass
