#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2020, Intel Corporation
#

#
# src/test/out_err_mt/TEST0 -- unit test for error messages
#

. $UNITTEST_SH

require_test_type medium
require_fs_type any
disable_eatmydata

setup

expect_normal_exit ./out_err_mt$EXESUFFIX \
	$DIR/testfile1 $DIR/testfile2 $DIR/testfile3 $DIR/testfile4 $DIR

check

pass
