# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2020, Intel Corporation

#
# examples/libpmem2/basic/Makefile -- build the unsafe_shutdown example
#
PROGS = unsafe_shutdown

LIBS = -lpmem2

include ../../Makefile.inc

unsafe_shutdown: unsafe_shutdown.o
