# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018, Intel Corporation

#
# src/test/obj_mem/Makefile -- build obj_mem test
#
TARGET = obj_mem
OBJS = obj_mem.o

LIBPMEMOBJ=y

include ../Makefile.inc
