# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016, Intel Corporation

#
# src/test/pmem_include/Makefile -- compilation test for libpmem
#
TARGET = pmem_include
OBJS = pmem_include.o

LIBPMEM=y

include ../Makefile.inc
