# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2017-2018, Intel Corporation

#
# src/test/util_vec/Makefile -- build util_vec unit test
#

TARGET = util_vec
OBJS = util_vec.o
LIBPMEMCOMMON=y

include ../Makefile.inc
