#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/out_err/TEST0 -- unit test for out_err()
#

. $UNITTEST_SH

require_test_type medium

require_fs_type none
require_build_type debug

setup

export TRACE_LOG_LEVEL=1
export TRACE_LOG_FILE=./traces$UNITTEST_NUM.log

expect_normal_exit ./out_err$EXESUFFIX

check

pass
