#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/rpmem_obc/TEST0 -- unit test for rpmem_obc_*
# functions which require established connection
#

. ../unittest/unittest.sh

require_test_type medium

require_fs_type none
require_build_type nondebug debug

setup

expect_normal_exit ./rpmem_obc$EXESUFFIX client_enotconn

check

pass
