#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/rpmem_obc/TEST5 -- unit test for rpmem_obc_open function
#

. ../unittest/unittest.sh

require_test_type medium

require_fs_type none
require_build_type nondebug debug

setup

. setup.sh

expect_normal_exit run_on_node 1 ./rpmem_obc$EXESUFFIX\
	client_open ${NODE_ADDR[0]}

pass
