# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018, Intel Corporation

#
# src/test/util_vecq/Makefile -- build util_vecq unit test
#

TARGET = util_vecq
OBJS = util_vecq.o
LIBPMEMCOMMON=y

include ../Makefile.inc
