# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018, Intel Corporation
#
# Makefile -- Makefile for extents tool
#

SCP_TO_REMOTE_NODES = y

TOP = ../../../..

TARGET = extents
OBJS = extents.o

LIBPMEM=y
LIBPMEMCOMMON=y

include $(TOP)/src/tools/Makefile.inc
