# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2014-2018, Intel Corporation

#
# src/test/pmempool_check/Makefile -- build pmempool check unittest
#
USE_PMEMSPOIL=y
USE_PMEMWRITE=y
USE_DDMAP=y

include ../Makefile.inc
