#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2018, Intel Corporation
#
#
# pmempool_check/TEST11 -- test for checking pools with device dax
#

. $UNITTEST_SH

require_test_type medium

require_dax_devices 1
require_fs_type any
# covered by TEST20
configure_valgrind memcheck force-disable $PMEMPOOL$EXESUFFIX

setup

dax_device_zero

LOG=out${UNITTEST_NUM}.log
rm -f $LOG && touch $LOG

POOLSET=$DEVICE_DAX_PATH

expect_normal_exit $PMEMPOOL$EXESUFFIX create obj $POOLSET
expect_normal_exit $PMEMPOOL$EXESUFFIX check -vry $POOLSET >> $LOG
expect_normal_exit $PMEMPOOL$EXESUFFIX info $POOLSET &> /dev/null

pass
