#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018, Intel Corporation
#
#
# pmempool_check/TEST29 -- test for checking pools
#
. $UNITTEST_SH

require_test_type medium
require_fs_type any
require_sds $PMEMPOOL$EXESUFFIX

setup
. ./common.sh

require_usc_permission $DIR

pmempool_check_sds_init enable-sds
pmempool_check_sds fix_first_replica

check
pass
