#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2014-2018, Intel Corporation
#
#
# pmempool_check/TEST3 -- test for checking pools
#

. $UNITTEST_SH

require_test_type medium

require_fs_type pmem non-pmem

setup

POOL=$DIR/file.pool
LOG=out${UNITTEST_NUM}.log
rm -f $LOG && touch $LOG

expect_normal_exit $PMEMPOOL$EXESUFFIX create -w blk 512 $POOL
check_file $POOL
$PMEMSPOIL $POOL pool_hdr.signature=ERROR\
	"pmemblk.arena.btt_map(0)=0xc0000001"\
	"pmemblk.arena.btt_flog(0).seq=5"

expect_normal_exit $PMEMPOOL$EXESUFFIX check -avry $POOL >> $LOG

check

pass
