#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2014-2018, Intel Corporation
#
#
# pmempool_check/TEST7 -- test for checking pools
#

. $UNITTEST_SH

require_test_type medium

require_fs_type pmem non-pmem

setup

POOL=$DIR/file.pool
LOG=out${UNITTEST_NUM}.log
rm -f $LOG && touch $LOG

rm -f $POOL
expect_normal_exit $PMEMPOOL$EXESUFFIX create blk 512 $POOL
check_file $POOL
$PMEMSPOIL -v $POOL pool_hdr.uuid=ERROR >> $LOG
expect_abnormal_exit $PMEMPOOL$EXESUFFIX check $POOL >> $LOG
expect_normal_exit $PMEMPOOL$EXESUFFIX check -vyr $POOL >> $LOG
expect_normal_exit $PMEMPOOL$EXESUFFIX check -v $POOL >> $LOG

rm -f $POOL
expect_normal_exit $PMEMPOOL$EXESUFFIX create blk 512 $POOL
check_file $POOL
$PMEMSPOIL -v $POOL\
	pool_hdr.prev_part_uuid=ERROR_PREV\
	pool_hdr.next_part_uuid=ERROR_NEXT\
	>> $LOG
expect_abnormal_exit $PMEMPOOL$EXESUFFIX check $POOL >> $LOG
expect_abnormal_exit $PMEMPOOL$EXESUFFIX check -vyr $POOL >> $LOG
expect_normal_exit $PMEMPOOL$EXESUFFIX check -avyr $POOL >> $LOG
expect_normal_exit $PMEMPOOL$EXESUFFIX check -v $POOL >> $LOG

rm -f $POOL
expect_normal_exit $PMEMPOOL$EXESUFFIX create blk 512 $POOL
check_file $POOL
$PMEMSPOIL -v $POOL\
	pool_hdr.prev_part_uuid=ERROR_PREV\
	pool_hdr.next_part_uuid=ERROR_NEXT\
	pool_hdr.prev_repl_uuid=ERROR_RPREV\
	pool_hdr.next_repl_uuid=ERROR_RNEXT\
	>> $LOG
expect_abnormal_exit $PMEMPOOL$EXESUFFIX check $POOL >> $LOG
expect_abnormal_exit $PMEMPOOL$EXESUFFIX check -vyr $POOL >> $LOG
expect_normal_exit $PMEMPOOL$EXESUFFIX check -avyr $POOL >> $LOG
expect_normal_exit $PMEMPOOL$EXESUFFIX check -v $POOL >> $LOG

check

pass
