#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2014-2018, Intel Corporation
#
#
# pmempool_check/TEST4 -- test for checking pools
#

. ../unittest/unittest.sh

require_test_type medium

require_fs_type pmem non-pmem

setup

POOL=$DIR/file.pool
LOG=out${UNITTEST_NUM}.log
rm -f $LOG && touch $LOG

expect_normal_exit $PMEMPOOL$EXESUFFIX create -w blk 512 $POOL
check_file $POOL
expect_normal_exit $PMEMPOOL$EXESUFFIX info $POOL > /dev/null
$PMEMSPOIL -v $POOL pool_hdr.checksum=0x0 >> $LOG

expect_abnormal_exit $PMEMPOOL$EXESUFFIX check -vry $POOL >> $LOG
expect_normal_exit $PMEMPOOL$EXESUFFIX check -avry $POOL >> $LOG
expect_normal_exit $PMEMPOOL$EXESUFFIX check $POOL >> $LOG
expect_normal_exit $PMEMPOOL$EXESUFFIX info $POOL &> /dev/null

check

pass
