#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018, Intel Corporation
#
#
# pmempool_check/TEST35 -- test for checking pools
#
. $UNITTEST_SH

require_test_type medium
require_fs_type any
require_no_sds $PMEMPOOL$EXESUFFIX

setup
. ./common.sh

pmempool_check_sds_init # do not enable SHUTDOWN_STATE
pmempool_check_sds fix_no_replicas

check
pass
