#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2014-2018, Intel Corporation
#
#
# pmempool_check/TEST2 -- test for checking pools
#

. $UNITTEST_SH

require_test_type medium

require_fs_type pmem non-pmem

setup

POOL=$DIR/file.pool
POOL_BACKUP=$DIR/file.pool.backup
LOG=out${UNITTEST_NUM}.log
rm -f $LOG && touch $LOG

expect_normal_exit $PMEMPOOL$EXESUFFIX create blk 512 $POOL
check_file $POOL
$PMEMSPOIL $POOL pool_hdr.signature=ERROR
expect_abnormal_exit $PMEMPOOL$EXESUFFIX check -b $POOL_BACKUP -r $POOL &>/dev/null
check_file ${POOL_BACKUP}

pass
