#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2018, Intel Corporation
#
#
# pmempool_check/TEST10 -- test for checking pools with multiple replicas
#

. $UNITTEST_SH

require_test_type medium

require_fs_type pmem non-pmem

setup

POOLSET=$DIR/pool.set
POOL_R1_PART1=$DIR/pool.replica1.part1
POOL_R1_PART2=$DIR/pool.replica1.part2
POOL_R2_PART1=$DIR/pool.replica2.part1
POOL_R2_PART2=$DIR/pool.replica2.part2
PARTS="$POOL_R1_PART1 $POOL_R1_PART2 $POOL_R2_PART1 $POOL_R2_PART2"

LOG=out${UNITTEST_NUM}.log
rm -f $LOG && touch $LOG

create_poolset $POOLSET \
	20M:$POOL_R1_PART1 50M:$POOL_R1_PART2 \
	R \
	40M:$POOL_R2_PART1 20M:$POOL_R2_PART2

expect_normal_exit $PMEMPOOL$EXESUFFIX create obj $POOLSET
check_files $PARTS
$PMEMSPOIL -v $POOL_R2_PART1 pool_hdr.uuid=ERROR >> $LOG
expect_abnormal_exit $PMEMPOOL$EXESUFFIX check -vry $POOLSET >> $LOG
expect_abnormal_exit $PMEMPOOL$EXESUFFIX info $POOLSET 2> /dev/null

check

pass
