# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018, Intel Corporation

#
# src/test/util_pool_hdr/Makefile -- build util_pool_hdr unit test
#
TARGET = util_pool_hdr
OBJS = util_pool_hdr.o

LIBPMEMCOMMON=y

include ../Makefile.inc
