#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018-2019, Intel Corporation

#
# src/test/util_pool_hdr/TEST0 -- unit test for pool_hdr layout
#					and default values
#

. $UNITTEST_SH

require_test_type short

setup

expect_normal_exit ./util_pool_hdr$EXESUFFIX

pass
