# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/obj_ctl_alloc_class_config/Makefile -- build obj_ctl_alloc_class_config test
#
TARGET = obj_ctl_alloc_class_config
OBJS = obj_ctl_alloc_class_config.o

LIBPMEMOBJ=y

include ../Makefile.inc
