#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

. $UNITTEST_SH

require_test_type short
require_fs_type any

setup

PMEMOBJ_CONF_FILE="alloc_class_config"\
	expect_normal_exit ./obj_ctl_alloc_class_config$EXESUFFIX $DIR/testfile

check

pass
