# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018-2019, Intel Corporation

#
# src/test/pmreorder_stack/Makefile -- build pmreorder_stack test
#

TARGET = pmreorder_stack
OBJS = pmreorder_stack.o

LIBPMEM=y

# included for VALGRIND_EMIT_LOG
LIBPMEMCOMMON=y

include ../Makefile.inc
