# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2014-2017, Intel Corporation

#
# src/test/util_map_proc/Makefile -- build util_map_proc unit test
#
TARGET = util_map_proc
OBJS = util_map_proc.o

LIBPMEMCOMMON=y

include ../Makefile.inc
LIBS += $(LIBDL)
