#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/util_map_proc/TEST6 -- unit test for util_map /proc parsing
#

. ../unittest/unittest.sh

require_test_type medium

require_fs_type none
require_procfs
configure_valgrind memcheck force-disable

setup

export PMEM_MMAP_HINT=0

mapfile="mapfile_nonexistent"
expect_normal_exit ./util_map_proc$EXESUFFIX $mapfile 0x12345678

check

pass
