#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2014-2019, Intel Corporation

#
# src/test/util_map_proc/TEST0 -- unit test for util_map /proc parsing
#

. $UNITTEST_SH

require_test_type medium

require_fs_type none
configure_valgrind memcheck force-disable

setup

# there should be an unused region for each length
mapfile="maps_all_"$(uname -s | tr "[:upper:]" "[:lower:]")
expect_normal_exit ./util_map_proc$EXESUFFIX $mapfile\
     0x0000100000\
     0x0001000000\
     0x0040000000\
     0x0400000000\
     0x4000000000

check

pass
