# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2014-2019, Intel Corporation

#
# src/test/log_walker/Makefile -- build log_walker unit test
#
TARGET = log_walker
OBJS = log_walker.o

LIBPMEMLOG=y

include ../Makefile.inc
