#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2014-2019, Intel Corporation

#
# src/test/log_walker/TEST0 -- unit test to verify pool's write-protection
#                              in debug mode
#

. ../unittest/unittest.sh

require_test_type medium

require_build_type debug static-debug

# exits without cleanup
configure_valgrind force-disable

setup

# this test invokes sigsegvs by design
export ASAN_OPTIONS=handle_segv=0

touch $DIR/testfile1

expect_normal_exit ./log_walker$EXESUFFIX $DIR/testfile1

check_pool $DIR/testfile1

check

pass
