# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2020, Intel Corporation

#
# examples/libpmem2/advanced/Makefile -- build the advanced example
#
PROGS = advanced

LIBS = -lpmem2

include ../../Makefile.inc

advanced: advanced.o
