# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2014-2016, Intel Corporation

#
# src/test/traces/Makefile -- build traces unit test
#
TARGET = traces
OBJS = traces.o

BUILD_STATIC_DEBUG=n
BUILD_STATIC_NONDEBUG=n

LIBPMEMCOMMON=y
include ../Makefile.inc
CFLAGS += -DDEBUG
