#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2014-2019, Intel Corporation

#
# src/test/traces/TEST5 -- unit test for traces
#

. $UNITTEST_SH

require_test_type medium

require_fs_type none
require_build_type debug

setup

export UT_LOG_LEVEL=4
expect_normal_exit ./traces$EXESUFFIX 2>redir_stderr$UNITTEST_NUM.log

check

pass
