# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2017, Intel Corporation
#
# Makefile -- Makefile for cmpmap tool
#

TOP = ../../../..

TARGET = cmpmap
OBJS = cmpmap.o

LIBPMEM=y
LIBPMEMCOMMON=y

include $(TOP)/src/tools/Makefile.inc
