# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2014-2019, Intel Corporation

#
# src/test/blk_nblock/Makefile -- build blk_nblock unit test
#
TARGET = blk_nblock
OBJS = blk_nblock.o

LIBPMEMBLK=y

include ../Makefile.inc
