#!/usr/bin/env bash
#
# Copyright 2014-2019, Intel Corporation
# Copyright 2019, IBM Corporation
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in
#       the documentation and/or other materials provided with the
#       distribution.
#
#     * Neither the name of the copyright holder nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

#
# src/test/blk_nblock/TEST3 -- unit test for pmemblk_nblock
#
# This test is equivalent of TEST0 for ppc64le platform.
#

. ../unittest/unittest.sh

require_test_type medium

require_fs_type any
require_unlimited_vm
require_ppc64

# this test creates huge files
configure_valgrind force-disable
setup

#
# Create a gajillion files, each file size created
# has six versions for the six block sizes being tested.
# Except for testfile1, since that should fail because
# it is too small.
#
# These are holey files, so they actually don't take up
# any significant space.
#
truncate -s 2M $DIR/testfile1
truncate -s 2G $DIR/testfile2.512
truncate -s 2G $DIR/testfile2.520
truncate -s 2G $DIR/testfile2.528
truncate -s 2G $DIR/testfile2.4096
truncate -s 2G $DIR/testfile2.4160
truncate -s 2G $DIR/testfile2.4224
truncate -s 512G $DIR/testfile3.512
truncate -s 512G $DIR/testfile3.520
truncate -s 512G $DIR/testfile3.528
truncate -s 512G $DIR/testfile3.4096
truncate -s 512G $DIR/testfile3.4160
truncate -s 512G $DIR/testfile3.4224
truncate -s 549755822080 $DIR/testfile4.512
truncate -s 549755822080 $DIR/testfile4.520
truncate -s 549755822080 $DIR/testfile4.528
truncate -s 549755822080 $DIR/testfile4.4096
truncate -s 549755822080 $DIR/testfile4.4160
truncate -s 549755822080 $DIR/testfile4.4224
truncate -s 513G $DIR/testfile5.512
truncate -s 513G $DIR/testfile5.520
truncate -s 513G $DIR/testfile5.528
truncate -s 513G $DIR/testfile5.4096
truncate -s 513G $DIR/testfile5.4160
truncate -s 513G $DIR/testfile5.4224
truncate -s 514G $DIR/testfile6.512
truncate -s 514G $DIR/testfile6.520
truncate -s 514G $DIR/testfile6.528
truncate -s 514G $DIR/testfile6.4096
truncate -s 514G $DIR/testfile6.4160
truncate -s 514G $DIR/testfile6.4224
# MINIMUM POOL SIZE = 16MB + 8KB
MIN_POOL_SIZE=$((16*1024*1024 + 128*1024))
truncate -s $MIN_POOL_SIZE $DIR/testfile7.512
truncate -s $MIN_POOL_SIZE $DIR/testfile7.520
truncate -s $MIN_POOL_SIZE $DIR/testfile7.528
truncate -s $MIN_POOL_SIZE $DIR/testfile7.4096
truncate -s $MIN_POOL_SIZE $DIR/testfile7.4160
truncate -s $MIN_POOL_SIZE $DIR/testfile7.4224

# should fail:
#	512:$DIR/testfile1 (file is too small)
#	4096:$DIR/testfile2.512 (bsize doesn't match pool)
expect_normal_exit ./blk_nblock$EXESUFFIX\
	512:$DIR/testfile1\
	512:$DIR/testfile2.512\
	4096:$DIR/testfile2.512\
	520:$DIR/testfile2.520\
	528:$DIR/testfile2.528\
	4096:$DIR/testfile2.4096\
	4160:$DIR/testfile2.4160\
	4224:$DIR/testfile2.4224\
	512:$DIR/testfile3.512\
	520:$DIR/testfile3.520\
	528:$DIR/testfile3.528\
	4096:$DIR/testfile3.4096\
	4160:$DIR/testfile3.4160\
	4224:$DIR/testfile3.4224\
	512:$DIR/testfile4.512\
	520:$DIR/testfile4.520\
	528:$DIR/testfile4.528\
	4096:$DIR/testfile4.4096\
	4160:$DIR/testfile4.4160\
	4224:$DIR/testfile4.4224\
	512:$DIR/testfile5.512\
	520:$DIR/testfile5.520\
	528:$DIR/testfile5.528\
	4096:$DIR/testfile5.4096\
	4160:$DIR/testfile5.4160\
	4224:$DIR/testfile5.4224\
	512:$DIR/testfile6.512\
	520:$DIR/testfile6.520\
	528:$DIR/testfile6.528\
	4096:$DIR/testfile6.4096\
	4160:$DIR/testfile6.4160\
	4224:$DIR/testfile6.4224\
	512:$DIR/testfile7.512\
	520:$DIR/testfile7.520\
	528:$DIR/testfile7.528\
	4096:$DIR/testfile7.4096\
	4160:$DIR/testfile7.4160\
	4224:$DIR/testfile7.4224

check_pools $DIR/testfile2.512\
	$DIR/testfile2.512\
	$DIR/testfile2.520\
	$DIR/testfile2.528\
	$DIR/testfile2.4096\
	$DIR/testfile2.4160\
	$DIR/testfile2.4224\
	$DIR/testfile3.512\
	$DIR/testfile3.520\
	$DIR/testfile3.528\
	$DIR/testfile3.4096\
	$DIR/testfile3.4160\
	$DIR/testfile3.4224\
	$DIR/testfile4.512\
	$DIR/testfile4.520\
	$DIR/testfile4.528\
	$DIR/testfile4.4096\
	$DIR/testfile4.4160\
	$DIR/testfile4.4224\
	$DIR/testfile5.512\
	$DIR/testfile5.520\
	$DIR/testfile5.528\
	$DIR/testfile5.4096\
	$DIR/testfile5.4160\
	$DIR/testfile5.4224\
	$DIR/testfile6.512\
	$DIR/testfile6.520\
	$DIR/testfile6.528\
	$DIR/testfile6.4096\
	$DIR/testfile6.4160\
	$DIR/testfile6.4224\
	$DIR/testfile7.512\
	$DIR/testfile7.520\
	$DIR/testfile7.528\
	$DIR/testfile7.4096\
	$DIR/testfile7.4160\
	$DIR/testfile7.4224

check

pass
