#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2014-2019, Intel Corporation

#
# src/test/blk_nblock/TEST2 -- unit test for pmemblk_nblock
#

. ../unittest/unittest.sh

require_test_type medium

require_fs_type any

setup

create_poolset $DIR/testset1 64M:$DIR/testfile11:x
create_poolset $DIR/testset2 64M:$DIR/testfile21:x 64M:$DIR/testfile22:x

expect_normal_exit ./blk_nblock$EXESUFFIX\
	512:$DIR/testset1\
	512:$DIR/testset2

check_pools $DIR/testset1\
	$DIR/testset2
check

pass
