#!/usr/bin/env bash
#
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2014-2019, Intel Corporation
# Copyright 2019, IBM Corporation

#
# src/test/blk_nblock/TEST4 -- unit test for pmemblk_nblock
#
# This test is equivalent of TEST1 for ppc64le platform.
#

. $UNITTEST_SH

require_test_type medium

require_fs_type any
require_ppc64

setup

#
# Create many files with different block sizes - most of
# them corner cases.
#
# These are holey files, so they actually don't take up
# any significant space.
#
truncate -s 1G $DIR/testfile1.2096640
truncate -s 1G $DIR/testfile1.2096641
truncate -s 2G $DIR/testfile2.0
truncate -s 2G $DIR/testfile2.1
truncate -s 2G $DIR/testfile2.17
truncate -s 2G $DIR/testfile2.511
truncate -s 2G $DIR/testfile2.1048576
truncate -s 2G $DIR/testfile2.2097152
truncate -s 2G $DIR/testfile2.4194304
truncate -s 2G $DIR/testfile2.8388608
truncate -s 2G $DIR/testfile2.16777216
truncate -s 2G $DIR/testfile2.33554432
truncate -s 2G $DIR/testfile2.67108864
truncate -s 2G $DIR/testfile2.134217728
truncate -s 2G $DIR/testfile2.268435456
truncate -s 2G $DIR/testfile2.536870912
truncate -s 2G $DIR/testfile2.1073741824
truncate -s 2G $DIR/testfile2.2147483648
truncate -s 2G $DIR/testfile2.-1

expect_normal_exit ./blk_nblock$EXESUFFIX\
	2096640:$DIR/testfile1.2096640\
	2096641:$DIR/testfile1.2096641\
	0:$DIR/testfile2.0\
	1:$DIR/testfile2.1\
	17:$DIR/testfile2.17\
	511:$DIR/testfile2.511\
	1048576:$DIR/testfile2.1048576\
	2097152:$DIR/testfile2.2097152\
	4194304:$DIR/testfile2.4194304\
	8388608:$DIR/testfile2.8388608\
	16777216:$DIR/testfile2.16777216\
	33554432:$DIR/testfile2.33554432\
	67108864:$DIR/testfile2.67108864\
	134217728:$DIR/testfile2.134217728\
	268435456:$DIR/testfile2.268435456\
	536870912:$DIR/testfile2.536870912\
	1073741824:$DIR/testfile2.1073741824\
	2147483648:$DIR/testfile2.2147483648\
	-1:$DIR/testfile2.-1

check_pools $DIR/testfile1.2096640\
	$DIR/testfile1.2096641\
	$DIR/testfile2.1\
	$DIR/testfile2.17\
	$DIR/testfile2.511\
	$DIR/testfile2.1048576\
	$DIR/testfile2.2097152\
	$DIR/testfile2.4194304\
	$DIR/testfile2.8388608\
	$DIR/testfile2.16777216\
	$DIR/testfile2.33554432\
	$DIR/testfile2.67108864\
	$DIR/testfile2.134217728\
	$DIR/testfile2.268435456\
	$DIR/testfile2.536870912\
	$DIR/testfile2.1073741824\
	$DIR/testfile2.2147483648\

check

pass
