# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016, Intel Corporation

#
# src/test/obj_rpmem_basic_integration/Makefile -- unit test for LIBPMEMOBJ
# basic operations using remote replication (LIBRPMEM)
#
SCP_TO_REMOTE_NODES = y
SCP_TARGET = obj_basic_integration
SCP_SRC_DIR = ../obj_basic_integration

include ../obj_basic_integration/Makefile.inc
