#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2017-2019, Intel Corporation
#
#
# obj_rpmem_basic_integration/TEST19 -- minimal pool parts size
#

. ../unittest/unittest.sh

require_test_type medium

setup

require_nodes 2

require_node_libfabric 0 $RPMEM_PROVIDER
require_node_libfabric 1 $RPMEM_PROVIDER

init_rpmem_on_node 1 0

# binary for this test
EXE=obj_basic_integration

# define files and directories
TEST_SET_LOCAL="testset_local"
TEST_SET_REMOTE="testset_remote"

TEST_FILE_LOCAL="testfile_local"
TEST_FILE_REMOTE="testfile_remote"

POOLSET_LOCAL=
TEST_FILES_LOCAL=
POOLSET_REMOTE=
TEST_FILES_REMOTE=
for i in {0..8}; do
	POOLSET_LOCAL="$POOLSET_LOCAL 2M:${NODE_DIR[1]}${TEST_FILE_LOCAL}${i}:x"
	TEST_FILES_LOCAL="$TEST_FILES_LOCAL ${NODE_DIR[1]}${TEST_FILE_LOCAL}${i}"

	POOLSET_REMOTE="$POOLSET_REMOTE 2M:${NODE_DIR[0]}${TEST_FILE_REMOTE}${i}:x"
	TEST_FILES_REMOTE="$TEST_FILES_REMOTE ${NODE_DIR[0]}${TEST_FILE_REMOTE}${i}"
done
POOLSET_LOCAL="$POOLSET_LOCAL m ${NODE_ADDR[0]}:$TEST_SET_REMOTE"

# create and upload poolset files
create_poolset $DIR/$TEST_SET_LOCAL $POOLSET_LOCAL
create_poolset $DIR/$TEST_SET_REMOTE $POOLSET_REMOTE

copy_files_to_node 0 ${NODE_DIR[0]} $DIR/$TEST_SET_REMOTE
copy_files_to_node 1 ${NODE_DIR[1]} $DIR/$TEST_SET_LOCAL

rm_files_from_node 0 $TEST_FILES_REMOTE
rm_files_from_node 1 $TEST_FILES_LOCAL

# execute test
expect_normal_exit run_on_node 1 ./$EXE$EXESUFFIX ${NODE_DIR[1]}$TEST_SET_LOCAL

check

pass
