#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation
#
#
# obj_rpmem_basic_integration/TEST4 -- rpmem replication from single local 8MB
#       part to two remote replicas (10MB and 12MB) on single remote node.
#
# Replica can not have replica of its own so libpmemobj should return an error
# during attempt to open daisy chained poolset files.
#

. ../unittest/unittest.sh

require_test_type medium

setup

require_nodes 2

require_node_libfabric 0 $RPMEM_PROVIDER
require_node_libfabric 1 $RPMEM_PROVIDER

init_rpmem_on_node 1 0

STDERR=stderr${UNITTEST_NUM}.log

# binary for this test
EXE=obj_basic_integration

# define files and directories
TEST_SET_LOCAL="testset_local"
TEST_SET_REMOTE="testset_remote"

TEST_FILE_LOCAL="testfile_local"
TEST_FILE_REMOTE="testfile_remote"

# XXX: Make sum of all parts and replicas sizes equal
# create and upload poolset files
create_poolset $DIR/$TEST_SET_LOCAL \
        16M:${NODE_DIR[1]}/$TEST_FILE_LOCAL:x \
        m ${NODE_ADDR[0]}:$TEST_SET_REMOTE
create_poolset $DIR/$TEST_SET_REMOTE \
        18M:${NODE_DIR[0]}${TEST_FILE_REMOTE}0:x \
        r 20M:${NODE_DIS[0]}${TEST_FILE_REMOTE}1:x

copy_files_to_node 0 ${NODE_DIR[0]} $DIR/$TEST_SET_REMOTE
copy_files_to_node 1 ${NODE_DIR[1]} $DIR/$TEST_SET_LOCAL

rm_files_from_node 0 ${NODE_DIR[0]}$TEST_FILE_REMOTE
rm_files_from_node 1 ${NODE_DIR[1]}$TEST_FILE_LOCAL

# execute test
expect_abnormal_exit run_on_node 1 ./$EXE$EXESUFFIX ${NODE_DIR[1]}$TEST_SET_LOCAL 2>$STDERR

pass
