#!/usr/bin/env bash
#
# Copyright 2016-2019, Intel Corporation
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in
#       the documentation and/or other materials provided with the
#       distribution.
#
#     * Neither the name of the copyright holder nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
#
# obj_rpmem_basic_integration/TEST7 -- rpmem replication from two local parts
#    and single local replica to two remote replicas (one consists of single
#    part and one consists of two parts)
#

. ../unittest/unittest.sh

require_test_type medium

setup

require_nodes 3

require_node_libfabric 0 $RPMEM_PROVIDER
require_node_libfabric 1 $RPMEM_PROVIDER
require_node_libfabric 2 $RPMEM_PROVIDER

init_rpmem_on_node 0 1 2

# binary for this test
EXE=obj_basic_integration

# define files and directories
TEST_SET_LOCAL="testset_local"
TEST_SET_REMOTE="testset_remote"

TEST_FILE_LOCAL="testfile_local"
TEST_FILE_REMOTE="testfile_remote"

# create and upload poolset files
create_poolset $DIR/$TEST_SET_LOCAL \
	8M:${NODE_DIR[0]}/part1:x 8M:${NODE_DIR[0]}/part2:x \
	r 16M:${NODE_DIR[0]}$TEST_FILE_LOCAL:x \
	m ${NODE_ADDR[1]}:${TEST_SET_REMOTE}1 \
	m ${NODE_ADDR[2]}:${TEST_SET_REMOTE}2
create_poolset $DIR/${TEST_SET_REMOTE}1 \
	8M:${NODE_DIR[1]}${TEST_FILE_REMOTE}1_part1:x \
	8M:${NODE_DIR[1]}${TEST_FILE_REMOTE}1_part2:x
create_poolset $DIR/${TEST_SET_REMOTE}2 18M:${NODE_DIR[2]}${TEST_FILE_REMOTE}2:x

copy_files_to_node 0 ${NODE_DIR[0]} $DIR/$TEST_SET_LOCAL
copy_files_to_node 1 ${NODE_DIR[1]} $DIR/${TEST_SET_REMOTE}1
copy_files_to_node 2 ${NODE_DIR[2]} $DIR/${TEST_SET_REMOTE}2

rm_files_from_node 0 ${NODE_DIR[0]}$TEST_FILE_LOCAL ${NODE_DIR[0]}part1 ${NODE_DIR[0]}part2
rm_files_from_node 1 ${NODE_DIR[1]}${TEST_FILE_REMOTE}1_part1 ${NODE_DIR[1]}${TEST_FILE_REMOTE}1_part2
rm_files_from_node 2 ${NODE_DIR[2]}${TEST_FILE_REMOTE}2

# execute test
expect_normal_exit run_on_node 0 ./$EXE$EXESUFFIX ${NODE_DIR[0]}$TEST_SET_LOCAL

check

# download pools and compare them
copy_files_from_node 2 $DIR ${NODE_DIR[2]}${TEST_FILE_REMOTE}2
# XXX: Travis does not support copying multiple files at once. Join this calls
# after fixing the function.
copy_files_from_node 1 $DIR ${NODE_DIR[1]}${TEST_FILE_REMOTE}1_part1
copy_files_from_node 1 $DIR ${NODE_DIR[1]}${TEST_FILE_REMOTE}1_part2
copy_files_from_node 0 $DIR ${NODE_DIR[0]}$TEST_FILE_LOCAL
copy_files_from_node 0 $DIR ${NODE_DIR[0]}part1
copy_files_from_node 0 $DIR ${NODE_DIR[0]}part2

compare_replicas "-soOaAb -l -Z -H -C" \
	$DIR/$TEST_FILE_LOCAL $DIR/${TEST_FILE_REMOTE}2 > diff$UNITTEST_NUM.log

compare_replicas "-soOaAb -l -Z -H -C" \
	$DIR/part1 $DIR/${TEST_FILE_REMOTE}1_part1 >> diff$UNITTEST_NUM.log

compare_replicas "-soOaAb -l -Z -H -C" \
	$DIR/part2 $DIR/${TEST_FILE_REMOTE}1_part2 >> diff$UNITTEST_NUM.log

check_local

pass
