# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2014-2016, Intel Corporation

#
# src/test/util_file_open/Makefile -- build util_file_open unit test
#
TARGET = util_file_open
OBJS = util_file_open.o

LIBPMEMCOMMON=y
include ../Makefile.inc
