#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2018, Intel Corporation
#
#
# libpmempool_bttdev/TEST2 -- test for checking btt
#

. ../unittest/unittest.sh

require_test_type medium

require_fs_type any

setup

POOL=$DIR/file.pool
LOG=out${UNITTEST_NUM}.log
LOG_TEMP=out${UNITTEST_NUM}_part.log
rm -f $LOG && touch $LOG
rm -f $LOG_TEMP && touch $LOG_TEMP
EXE=../libpmempool_api/libpmempool_test

expect_normal_exit $BTTCREATE $POOL >> $LOG

$PMEMSPOIL $POOL "bttdevice.arena(0).btt_info_backup.sig=ERROR"
expect_normal_exit $EXE$EXESUFFIX -r 1 -t btt $POOL >> $LOG
cat $LOG >> $LOG_TEMP

$PMEMSPOIL $POOL "bttdevice.arena(0).btt_info.sig=ERROR"
expect_normal_exit $EXE$EXESUFFIX -r 1 -t btt $POOL >> $LOG
cat $LOG >> $LOG_TEMP

mv $LOG_TEMP $LOG

check_file $POOL

check

pass
