# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2014-2016, Intel Corporation

#
# src/test/util_file_create/Makefile -- build util_file_create unit test
#
TARGET = util_file_create
OBJS = util_file_create.o

LIBPMEMCOMMON=y
include ../Makefile.inc
