#!/bin/bash -e
#
# Copyright 2016-2017, Intel Corporation
# Copyright (c) 2016, Microsoft Corporation. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in
#       the documentation and/or other materials provided with the
#       distribution.
#
#     * Neither the name of the copyright holder nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
#
# obj_rpmem_constructor/TEST0 -- remote test for obj_constructor
#

export UNITTEST_NAME=obj_rpmem_constructor/TEST0
export UNITTEST_NUM=0

# standard unit test setup
. ../unittest/unittest.sh

require_test_type medium

configure_valgrind memcheck force-disable

setup

require_nodes 2

require_node_libfabric 0 $RPMEM_PROVIDER
require_node_libfabric 1 $RPMEM_PROVIDER

init_rpmem_on_node 1 0

# This is a pretty length test on non-pmem devices, so force clflushes.
export PMEM_IS_PMEM_FORCE=1
export_vars_node 1 PMEM_IS_PMEM_FORCE

# binary for this test
EXE=obj_constructor

# define files and directories
TEST_SET_LOCAL="testset_local"
TEST_SET_REMOTE="testset_remote"

TEST_FILE_LOCAL="testfile_local"
TEST_FILE_REMOTE="testfile_remote"

NODE_DIRS=($(get_node_dir 0) $(get_node_dir 1))

rm_files_from_node 0 $TEST_FILE_REMOTE
rm_files_from_node 1 $TEST_FILE_LOCAL

# XXX: Make sum of all parts and replicas sizes equal
# create and upload poolset files
create_poolset $DIR/$TEST_SET_LOCAL 16M:${NODE_DIRS[1]}/$TEST_FILE_LOCAL:x \
        m ${NODE_ADDR[0]}:$TEST_SET_REMOTE
create_poolset $DIR/$TEST_SET_REMOTE 17M:${NODE_DIRS[0]}/$TEST_FILE_REMOTE:x

copy_files_to_node 0 . $DIR/$TEST_SET_REMOTE
copy_files_to_node 1 . $DIR/$TEST_SET_LOCAL

# create remote holey pool files
create_holey_file_on_node 1 16M ${NODE_DIRS[1]}/$TEST_FILE_LOCAL
create_holey_file_on_node 0 17M ${NODE_DIRS[0]}/$TEST_FILE_REMOTE

# execute test
# XXX: --big-alloc is required because remote replication on Travis is too slow
# to replicate a great number of allocations in assumed timeout. --big-alloc
# will be obsolete when either Travis speed up significantly or remote
# replication would require less remote operations to replicate the same number
# of allocations.
expect_normal_exit run_on_node 1 ./$EXE$EXESUFFIX $TEST_SET_LOCAL --big-alloc

check

# download pools and compare them
copy_files_from_node 0 $DIR $TEST_FILE_REMOTE
copy_files_from_node 1 $DIR $TEST_FILE_LOCAL

compare_replicas "-soOaAb -l -Z -H -C" \
	$DIR/$TEST_FILE_LOCAL $DIR/$TEST_FILE_REMOTE > diff$UNITTEST_NUM.log

check_local

pass
