# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2024, Intel Corporation
#

name: DAOS

on:
  push:

permissions: {}

jobs:
  clear_caches:
    name: Clear caches
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ref: [master, release/2.6]
    permissions:
      actions: write
    steps:
      - run: |
          curl -L \
            -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/pmem/pmdk/actions/caches?key=opt_daos-${{ matrix.ref }}"
  daos_tests:
    name: DAOS
    needs: clear_caches
    strategy:
      matrix:
        ref: [master, release/2.6]
    uses: pmem/pmdk/.github/workflows/daos_tests.yml@DAOS-tests
    with:
      DAOS_REF: ${{ matrix.ref }}
