name: Documentation

on:
  schedule:
    # run this job at 00:00 UTC every Saturday
    - cron: '0 0 * * 6'

jobs:
  linux:
    name: Documentation
    if: github.repository == 'pmem/pmdk'
    runs-on: ubuntu-latest
    env:
      WORKDIR: utils/gha-runners
      SCRIPT: utils/check_docs/split_manpage_tests.py

    steps:
        - name: clone PMDK repository
          uses: actions/checkout@v2

        - name: Install necessary packages
          run: |
            sudo apt-get install -y build-essential cmake libndctl-dev libdaxctl-dev pandoc pkg-config

        - name: Build
          run: |
            ./$WORKDIR/build-pmdk-documentation.sh

        - name: Run tests
          run: python3 ${SCRIPT} --with-pmem2 -r $(pwd) -i $(pwd)/../install -v
