name: unittest_linux

on:
    workflow_dispatch:
        inputs:
            label:
                description: 'label of execution machine, for example dell004 or fedora34, remember to manually add labels on gha runners page.'
                required: true
                default: 'dell004'

jobs:
  linux:
    name: Linux
    runs-on: [self-hosted, linux, x64, '${{ github.event.inputs.label }}' ]
   
    steps:
        
        - name: Clone the git repo
          uses: actions/checkout@v2
        
        - name: Build
          run: |
            ./utils/gha-runners/buildPmdk.sh
            