# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018-2019, Intel Corporation

#
# src/test/obj_pmemcheck/Makefile -- build obj_pmemcheck unit test
#
TARGET = obj_pmemcheck
OBJS = obj_pmemcheck.o

LIBPMEMOBJ=internal-debug

include ../Makefile.inc

