# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_list_macro/Makefile -- build obj_list_macro unit test
#

TARGET = obj_list_macro
OBJS = obj_list_macro.o

LIBPMEMOBJ=y

include ../Makefile.inc
