#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_list_macro/TEST7 -- unit test for list API
#

. ../unittest/unittest.sh

require_test_type medium

setup

expect_normal_exit ../obj_list_macro/obj_list_macro$EXESUFFIX $DIR/testfile\
	n:0:0:1 P:1 P:2\
	n:0:0:2 P:1 P:2\
	n:0:0:3 P:1 P:2\
	n:0:0:4 P:1 P:2\
	n:0:0:5 P:1 P:2\
	n:0:0:6 P:1 P:2\
	m:3:1:0 P:1 P:2\
	m:2:1:0 P:1 P:2\
	r:1:1 P:1 P:2\
	m:1:1:1 P:1 P:2\
	n:0:0:7 P:1 P:2\
	n:0:0:8 P:1 P:2\
	n:0:0:9 P:1 P:2\
	n:0:0:10 P:1 P:2\
	n:0:0:11 P:1 P:2\
	f:1:6 P:1 P:2\
	f:1:5 P:1 P:2\
	m:1:-1:1 P:1 P:2\
	m:1:1:4 P:1 P:2\
	m:2:-1:3 P:1 P:2\
	r:2:2 P:1 P:2\
	m:1:1:0 P:1 P:2\
	f:2:2 P:1 P:2\
	m:0:1:1 P:1 P:2

check

pass
