# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018, Intel Corporation
#
# Makefile -- Makefile for fallocate detection tool
#

TOP = ../../../..

TARGET = usc_permission_check
OBJS = usc_permission_check.o

LIBPMEM=y
LIBPMEMCOMMON=y

include $(TOP)/src/tools/Makefile.inc
