#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation

#
# src/test/obj_critnib/TEST1 -- multithreaded test for critnib
#

. ../unittest/unittest.sh

require_test_type long
require_fs_type none
configure_valgrind helgrind force-enable

setup

expect_normal_exit ./obj_critnib_mt$EXESUFFIX

pass
