#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/obj_memblock/TEST0 -- unit test for memblock interface
#

. $UNITTEST_SH

require_test_type medium
require_fs_type none

setup

expect_normal_exit ./obj_memblock$EXESUFFIX

pass
