# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2019-2020, Intel Corporation

#
# src/test/ex_libpmem2/Makefile -- build ex_libpmem2 unittest
#

all: $(EXAMPLES)
	$(MAKE) -C $(EX_LIBPMEM2)

include ../Makefile.inc

EXAMPLES=$(EX_LIBPMEM2)/basic\
	$(EX_LIBPMEM2)/advanced\
	$(EX_LIBPMEM2)/log
