# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016, Intel Corporation

#
# src/test/util_uuid_generate/Makefile -- create a uuid and verify it
#
TARGET = util_uuid_generate
OBJS = util_uuid_generate.o

LIBPMEMCOMMON=y
include ../Makefile.inc
