#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/util_uuid_generate/TEST0 -- unit test for util_uuid_generate.
# No uuid string specified.
#

. ../unittest/unittest.sh

require_test_type medium

require_fs_type non-pmem

setup

expect_normal_exit ./util_uuid_generate$EXESUFFIX

check

pass
