#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2019, Intel Corporation

#
# src/test/util_uuid_generate/TEST1 -- unit test for util_uuid_generate.
# Valid uuid string specified.
#

. $UNITTEST_SH

require_test_type medium

require_fs_type non-pmem

setup

# valid uuid string
expect_normal_exit ./util_uuid_generate$EXESUFFIX \
	563bb872-0d1d-441e-ac28-579c463be0a5 valid

check

pass
